// ==========================================================================
// This is auto-generated by gf cli tool. DO NOT EDIT THIS FILE MANUALLY.
// ==========================================================================

package internal

import (
	"context"
	"database/sql"
	"errors"
	"reflect"
	"strings"
	"time"

	"github.com/gogf/gf/container/gvar"
	"github.com/gogf/gf/database/gdb"
	"github.com/gogf/gf/frame/g"
	"github.com/gogf/gf/frame/gmvc"
	"github.com/gogf/gf/util/gconv"

	//	"banban/app/model"
	"banban/app/pb"
)

// XsBannerDao is the manager for logic model data accessing
// and custom defined data operations functions management.
type XsBannerDao struct {
	gmvc.M
	DB      gdb.DB
	Table   string
	Columns xsBannerColumns
}

// XsBannerColumns defines and stores column names for table xs_banner.
type xsBannerColumns struct {
	ID                 string //
	AppID              string //
	Type               string // 默认web外部网页，app内部页
	Stype              string // app、pc
	Position           string // 位置
	Title              string // 标题
	Icon               string // banner图
	URL                string // app：页面名称, web:完整url
	Data               string // app：json序列化数据，web无用
	Ordering           string // 排序，数值越大越靠前
	Deleted            string // 是否已删除，1为删除
	BeginTime          string // 开始时间
	EndTime            string // 结束时间
	Dateline           string // 创建时间
	Role               string // 角色，0为所有人，1为大神可看，2为用户可看
	Cid                string // 可看的分类id
	Duration           string // 显示时长，app决定是否使用
	RoomType           string // position为chatroom时使用 房间广告类型 对应xs_chatroom中的types 多个用逗号分隔
	RoomIDs            string // 限定其可展示的房间,为空不限制,多个房间用逗号分隔
	SettlementChannel  string // position为chatroom时使 用 对应xs_chatroom中的settlement_channel 多个用逗号分隔
	RoomFactoryType    string // position为chatroom时使用 对应xs_chatroom中的room_factory_type 多个用逗号分隔
	IconType           string // banner图片类型，0为图片，1为h5链接
	Width              string // banner图宽度
	Height             string // banner图高度
	ShowClose          string // 是否可关闭，0为不可关闭，1为可关闭
	SubApp             string // 子APP:  默认0 没有, 1 嗨歌
	VipLevel           string // vip等级过滤，小于该等级不展示
	ShowOutRoom        string // 是否仅在房间外展示
	Property           string // position为chatroom时使用, 可选值同xs_chatroom.property
	ChannelTag         string // position=title_top对应的渠道tag
	VipLevelMax        string // vip等级上限过滤，大于该等级不展示
	ConsumeMin         string // 历史消费统计下限(单位:分)
	ConsumeMax         string // 历史消息统计上限(单位:分)
	CenterIcon         string // 活动中心对应的大图标,横排时用
	ActivityCenterType string // 活动中心类型,逗号分割 1:我的 2:活动 3:充值 4:节目 5:公告
	ShowInCenter       string // 0:既在对应position展示也在center展示, 1:只在活动中心展示
	WhitelistID        string // 是否使用白名单 0:不使用用户白名单 >0 表示白名单id
}

var (
	// XsBanner is globally public accessible object for table xs_banner operations.
	XsBanner = XsBannerDao{
		M:     g.DB("default").Model("xs_banner").Safe(),
		DB:    g.DB("default"),
		Table: "xs_banner",
		Columns: xsBannerColumns{
			ID:                 "id",
			AppID:              "app_id",
			Type:               "type",
			Stype:              "stype",
			Position:           "position",
			Title:              "title",
			Icon:               "icon",
			URL:                "url",
			Data:               "data",
			Ordering:           "ordering",
			Deleted:            "deleted",
			BeginTime:          "begin_time",
			EndTime:            "end_time",
			Dateline:           "dateline",
			Role:               "role",
			Cid:                "cid",
			Duration:           "duration",
			RoomType:           "room_type",
			RoomIDs:            "room_ids",
			SettlementChannel:  "settlement_channel",
			RoomFactoryType:    "room_factory_type",
			IconType:           "icon_type",
			Width:              "width",
			Height:             "height",
			ShowClose:          "show_close",
			SubApp:             "sub_app",
			VipLevel:           "vip_level",
			ShowOutRoom:        "show_out_room",
			Property:           "property",
			ChannelTag:         "channel_tag",
			VipLevelMax:        "vip_level_max",
			ConsumeMin:         "consume_min",
			ConsumeMax:         "consume_max",
			CenterIcon:         "center_icon",
			ActivityCenterType: "activity_center_type",
			ShowInCenter:       "show_in_center",
			WhitelistID:        "whitelist_id",
		},
	}
)

// Ctx is a chaining function, which creates and returns a new DB that is a shallow copy
// of current DB object and with given context in it.
// Note that this returned DB object can be used only once, so do not assign it to
// a global or package variable for long using.
func (d *XsBannerDao) Ctx(ctx context.Context) *XsBannerDao {
	return &XsBannerDao{M: d.M.Ctx(ctx)}
}

// As sets an alias name for current table.
func (d *XsBannerDao) As(as string) *XsBannerDao {
	return &XsBannerDao{M: d.M.As(as)}
}

// TX sets the transaction for current operation.
func (d *XsBannerDao) TX(tx *gdb.TX) *XsBannerDao {
	return &XsBannerDao{M: d.M.TX(tx)}
}

// Master marks the following operation on master node.
func (d *XsBannerDao) Master() *XsBannerDao {
	return &XsBannerDao{M: d.M.Master()}
}

// Slave marks the following operation on slave node.
// Note that it makes sense only if there's any slave node configured.
func (d *XsBannerDao) Slave() *XsBannerDao {
	return &XsBannerDao{M: d.M.Slave()}
}

// Args sets custom arguments for model operation.
func (d *XsBannerDao) Args(args ...interface{}) *XsBannerDao {
	return &XsBannerDao{M: d.M.Args(args...)}
}

// LeftJoin does "LEFT JOIN ... ON ..." statement on the model.
// The parameter <table> can be joined table and its joined condition,
// and also with its alias name, like:
// Table("user").LeftJoin("user_detail", "user_detail.uid=user.uid")
// Table("user", "u").LeftJoin("user_detail", "ud", "ud.uid=u.uid")
func (d *XsBannerDao) LeftJoin(table ...string) *XsBannerDao {
	return &XsBannerDao{M: d.M.LeftJoin(table...)}
}

// RightJoin does "RIGHT JOIN ... ON ..." statement on the model.
// The parameter <table> can be joined table and its joined condition,
// and also with its alias name, like:
// Table("user").RightJoin("user_detail", "user_detail.uid=user.uid")
// Table("user", "u").RightJoin("user_detail", "ud", "ud.uid=u.uid")
func (d *XsBannerDao) RightJoin(table ...string) *XsBannerDao {
	return &XsBannerDao{M: d.M.RightJoin(table...)}
}

// InnerJoin does "INNER JOIN ... ON ..." statement on the model.
// The parameter <table> can be joined table and its joined condition,
// and also with its alias name, like:
// Table("user").InnerJoin("user_detail", "user_detail.uid=user.uid")
// Table("user", "u").InnerJoin("user_detail", "ud", "ud.uid=u.uid")
func (d *XsBannerDao) InnerJoin(table ...string) *XsBannerDao {
	return &XsBannerDao{M: d.M.InnerJoin(table...)}
}

// Fields sets the operation fields of the model, multiple fields joined using char ','.
// The parameter <fieldNamesOrMapStruct> can be type of string/map/*map/struct/*struct.
func (d *XsBannerDao) Fields(fieldNamesOrMapStruct ...interface{}) *XsBannerDao {
	return &XsBannerDao{M: d.M.Fields(fieldNamesOrMapStruct...)}
}

// FieldsEx sets the excluded operation fields of the model, multiple fields joined using char ','.
// The parameter <fieldNamesOrMapStruct> can be type of string/map/*map/struct/*struct.
func (d *XsBannerDao) FieldsEx(fieldNamesOrMapStruct ...interface{}) *XsBannerDao {
	return &XsBannerDao{M: d.M.FieldsEx(fieldNamesOrMapStruct...)}
}

// Option sets the extra operation option for the model.
func (d *XsBannerDao) Option(option int) *XsBannerDao {
	return &XsBannerDao{M: d.M.Option(option)}
}

// OmitEmpty sets OPTION_OMITEMPTY option for the model, which automatically filers
// the data and where attributes for empty values.
func (d *XsBannerDao) OmitEmpty() *XsBannerDao {
	return &XsBannerDao{M: d.M.OmitEmpty()}
}

// Filter marks filtering the fields which does not exist in the fields of the operated table.
func (d *XsBannerDao) Filter() *XsBannerDao {
	return &XsBannerDao{M: d.M.Filter()}
}

// Where sets the condition statement for the model. The parameter <where> can be type of
// string/map/gmap/slice/struct/*struct, etc. Note that, if it's called more than one times,
// multiple conditions will be joined into where statement using "AND".
// Eg:
// Where("uid=10000")
// Where("uid", 10000)
// Where("money>? AND name like ?", 99999, "vip_%")
// Where("uid", 1).Where("name", "john")
// Where("status IN (?)", g.Slice{1,2,3})
// Where("age IN(?,?)", 18, 50)
// Where(User{ Id : 1, UserName : "john"})
func (d *XsBannerDao) Where(where interface{}, args ...interface{}) *XsBannerDao {
	return &XsBannerDao{M: d.M.Where(where, args...)}
}

// WherePri does the same logic as M.Where except that if the parameter <where>
// is a single condition like int/string/float/slice, it treats the condition as the primary
// key value. That is, if primary key is "id" and given <where> parameter as "123", the
// WherePri function treats the condition as "id=123", but M.Where treats the condition
// as string "123".
func (d *XsBannerDao) WherePri(where interface{}, args ...interface{}) *XsBannerDao {
	return &XsBannerDao{M: d.M.WherePri(where, args...)}
}

// And adds "AND" condition to the where statement.
func (d *XsBannerDao) And(where interface{}, args ...interface{}) *XsBannerDao {
	return &XsBannerDao{M: d.M.And(where, args...)}
}

// Or adds "OR" condition to the where statement.
func (d *XsBannerDao) Or(where interface{}, args ...interface{}) *XsBannerDao {
	return &XsBannerDao{M: d.M.Or(where, args...)}
}

// Group sets the "GROUP BY" statement for the model.
func (d *XsBannerDao) Group(groupBy string) *XsBannerDao {
	return &XsBannerDao{M: d.M.Group(groupBy)}
}

// Order sets the "ORDER BY" statement for the model.
func (d *XsBannerDao) Order(orderBy ...string) *XsBannerDao {
	return &XsBannerDao{M: d.M.Order(orderBy...)}
}

// Limit sets the "LIMIT" statement for the model.
// The parameter <limit> can be either one or two number, if passed two number is passed,
// it then sets "LIMIT limit[0],limit[1]" statement for the model, or else it sets "LIMIT limit[0]"
// statement.
func (d *XsBannerDao) Limit(limit ...int) *XsBannerDao {
	return &XsBannerDao{M: d.M.Limit(limit...)}
}

// Offset sets the "OFFSET" statement for the model.
// It only makes sense for some databases like SQLServer, PostgreSQL, etc.
func (d *XsBannerDao) Offset(offset int) *XsBannerDao {
	return &XsBannerDao{M: d.M.Offset(offset)}
}

// Page sets the paging number for the model.
// The parameter <page> is started from 1 for paging.
// Note that, it differs that the Limit function start from 0 for "LIMIT" statement.
func (d *XsBannerDao) Page(page, limit int) *XsBannerDao {
	return &XsBannerDao{M: d.M.Page(page, limit)}
}

// Batch sets the batch operation number for the model.
func (d *XsBannerDao) Batch(batch int) *XsBannerDao {
	return &XsBannerDao{M: d.M.Batch(batch)}
}

// Cache sets the cache feature for the model. It caches the result of the sql, which means
// if there's another same sql request, it just reads and returns the result from cache, it
// but not committed and executed into the database.
//
// If the parameter <duration> < 0, which means it clear the cache with given <name>.
// If the parameter <duration> = 0, which means it never expires.
// If the parameter <duration> > 0, which means it expires after <duration>.
//
// The optional parameter <name> is used to bind a name to the cache, which means you can later
// control the cache like changing the <duration> or clearing the cache with specified <name>.
//
// Note that, the cache feature is disabled if the model is operating on a transaction.
func (d *XsBannerDao) Cache(duration time.Duration, name ...string) *XsBannerDao {
	return &XsBannerDao{M: d.M.Cache(duration, name...)}
}

// Data sets the operation data for the model.
// The parameter <data> can be type of string/map/gmap/slice/struct/*struct, etc.
// Eg:
// Data("uid=10000")
// Data("uid", 10000)
// Data(g.Map{"uid": 10000, "name":"john"})
// Data(g.Slice{g.Map{"uid": 10000, "name":"john"}, g.Map{"uid": 20000, "name":"smith"})
func (d *XsBannerDao) Data(data ...interface{}) *XsBannerDao {
	return &XsBannerDao{M: d.M.Data(data...)}
}

// All does "SELECT FROM ..." statement for the model.
// It retrieves the records from table and returns the result as []*pb.EntityXsBanner.
// It returns nil if there's no record retrieved with the given conditions from table.
//
// The optional parameter <where> is the same as the parameter of M.Where function,
// see M.Where.
func (d *XsBannerDao) All(where ...interface{}) ([]*pb.EntityXsBanner, error) {
	all, err := d.M.All(where...)
	if err != nil {
		return nil, err
	}
	var entities []*pb.EntityXsBanner
	//if err = all.Structs(&entities); err != nil && err != sql.ErrNoRows {
	//	return nil, err
	//}
	if err = d.scan(all, &entities); err != nil && err != sql.ErrNoRows {
		return nil, err
	}
	return entities, nil
}

// One retrieves one record from table and returns the result as *pb.EntityXsBanner.
// It returns nil if there's no record retrieved with the given conditions from table.
//
// The optional parameter <where> is the same as the parameter of M.Where function,
// see M.Where.
func (d *XsBannerDao) One(where ...interface{}) (*pb.EntityXsBanner, error) {
	one, err := d.M.One(where...)
	if err != nil {
		return nil, err
	}
	var entity *pb.EntityXsBanner
	if err = one.Struct(&entity); err != nil && err != sql.ErrNoRows {
		return nil, err
	}
	return entity, nil
}

// FindOne retrieves and returns a single Record by M.WherePri and M.One.
// Also see M.WherePri and M.One.
func (d *XsBannerDao) FindOne(where ...interface{}) (*pb.EntityXsBanner, error) {
	one, err := d.M.FindOne(where...)
	if err != nil {
		return nil, err
	}
	var entity *pb.EntityXsBanner
	if err = one.Struct(&entity); err != nil && err != sql.ErrNoRows {
		return nil, err
	}
	return entity, nil
}

// FindAll retrieves and returns Result by by M.WherePri and M.All.
// Also see M.WherePri and M.All.
func (d *XsBannerDao) FindAll(where ...interface{}) ([]*pb.EntityXsBanner, error) {
	all, err := d.M.FindAll(where...)
	if err != nil {
		return nil, err
	}
	var entities []*pb.EntityXsBanner
	//if err = all.Structs(&entities); err != nil && err != sql.ErrNoRows {
	//	return nil, err
	//}
	if err = d.scan(all, &entities); err != nil && err != sql.ErrNoRows {
		return nil, err
	}
	return entities, nil
}

// Struct retrieves one record from table and converts it into given struct.
// The parameter <pointer> should be type of *struct/**struct. If type **struct is given,
// it can create the struct internally during converting.
//
// The optional parameter <where> is the same as the parameter of Model.Where function,
// see Model.Where.
//
// Note that it returns sql.ErrNoRows if there's no record retrieved with the given conditions
// from table and <pointer> is not nil.
//
// Eg:
// user := new(User)
// err  := dao.User.Where("id", 1).Struct(user)
//
// user := (*User)(nil)
// err  := dao.User.Where("id", 1).Struct(&user)
func (d *XsBannerDao) Struct(pointer interface{}, where ...interface{}) error {
	return d.M.Struct(pointer, where...)
}

// Structs retrieves records from table and converts them into given struct slice.
// The parameter <pointer> should be type of *[]struct/*[]*struct. It can create and fill the struct
// slice internally during converting.
//
// The optional parameter <where> is the same as the parameter of Model.Where function,
// see Model.Where.
//
// Note that it returns sql.ErrNoRows if there's no record retrieved with the given conditions
// from table and <pointer> is not empty.
//
// Eg:
// users := ([]User)(nil)
// err   := dao.User.Structs(&users)
//
// users := ([]*User)(nil)
// err   := dao.User.Structs(&users)
func (d *XsBannerDao) Structs(pointer interface{}, where ...interface{}) error {
	return d.M.Structs(pointer, where...)
}

// Scan automatically calls Struct or Structs function according to the type of parameter <pointer>.
// It calls function Struct if <pointer> is type of *struct/**struct.
// It calls function Structs if <pointer> is type of *[]struct/*[]*struct.
//
// The optional parameter <where> is the same as the parameter of Model.Where function,
// see Model.Where.
//
// Note that it returns sql.ErrNoRows if there's no record retrieved and given pointer is not empty or nil.
//
// Eg:
// user  := new(User)
// err   := dao.User.Where("id", 1).Scan(user)
//
// user  := (*User)(nil)
// err   := dao.User.Where("id", 1).Scan(&user)
//
// users := ([]User)(nil)
// err   := dao.User.Scan(&users)
//
// users := ([]*User)(nil)
// err   := dao.User.Scan(&users)
func (d *XsBannerDao) Scan(pointer interface{}, where ...interface{}) error {
	return d.M.Scan(pointer, where...)
}

// Chunk iterates the table with given size and callback function.
func (d *XsBannerDao) Chunk(limit int, callback func(entities []*pb.EntityXsBanner, err error) bool) {
	d.M.Chunk(limit, func(result gdb.Result, err error) bool {
		var entities []*pb.EntityXsBanner
		err = result.Structs(&entities)
		if err == sql.ErrNoRows {
			return false
		}
		return callback(entities, err)
	})
}

// LockUpdate sets the lock for update for current operation.
func (d *XsBannerDao) LockUpdate() *XsBannerDao {
	return &XsBannerDao{M: d.M.LockUpdate()}
}

// LockShared sets the lock in share mode for current operation.
func (d *XsBannerDao) LockShared() *XsBannerDao {
	return &XsBannerDao{M: d.M.LockShared()}
}

// Unscoped enables/disables the soft deleting feature.
func (d *XsBannerDao) Unscoped() *XsBannerDao {
	return &XsBannerDao{M: d.M.Unscoped()}
}

func (d *XsBannerDao) scan(res gdb.Result, in interface{}) error {
	length := res.Len()
	if length == 0 {
		return sql.ErrNoRows
	}
	v := reflect.ValueOf(in).Elem()
	newv := reflect.MakeSlice(v.Type(), 0, length)
	v.Set(newv)
	v.SetLen(length)

	index := 0
	var fieldToTag []string
	for i := 0; i < length; i++ {
		k := v.Type().Elem().Elem()
		newObj := reflect.New(k)
		if i == 0 {
			fieldToTag = d.getFieldTag(newObj)
		}
		err := d.mapping(res[i], newObj, fieldToTag)
		if err != nil {
			return err
		}
		v.Index(index).Set(newObj)
		index++
	}
	v.SetLen(index)
	return nil
}

func (d *XsBannerDao) getFieldTag(v reflect.Value) []string {
	t := v.Type()
	typ := t.Elem()
	val := v.Elem()
	vTypeOfT := val.Type()
	length := val.NumField()
	fieldToTag := make([]string, length)
	for j := 0; j < length; j++ {
		name := vTypeOfT.Field(j).Name
		if name[0] < 'A' || name[0] > 'Z' {
			continue
		}
		value := val.Field(j)
		tagVal := typ.Field(j).Tag.Get("orm")
		if !value.CanSet() || len(tagVal) == 0 {
			continue
		}
		index := strings.Index(tagVal, ",")
		if index > -1 {
			fieldToTag[j] = tagVal[0:index]
		} else {
			fieldToTag[j] = tagVal
		}
	}
	return fieldToTag
}

func (d *XsBannerDao) mapping(m map[string]*gvar.Var, v reflect.Value, fieldToTag []string) error {
	val := v.Elem()
	length := val.NumField()
	for i := 0; i < length; i++ {
		tag := fieldToTag[i]
		if len(tag) == 0 {
			continue
		}

		meta, ok := m[tag]
		if !ok {
			continue
		}
		value := val.Field(i)
		kind := value.Kind()
		switch kind {
		case reflect.String:
			value.SetString(meta.String())
			break
		case reflect.Float32, reflect.Float64:
			value.SetFloat(gconv.Float64(meta.String()))
			break
		case reflect.Int64, reflect.Int, reflect.Int8, reflect.Int16, reflect.Int32:
			value.SetInt(meta.Int64())
			break
		case reflect.Uint64, reflect.Uint, reflect.Uint8, reflect.Uint16, reflect.Uint32:
			value.SetUint(meta.Uint64())
			break
		case reflect.Bool:
			value.SetBool(meta.Bool())
			break
		default:
			return errors.New("unknown kind " + kind.String())
			break
		}
	}
	return nil
}
