// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.23.4
// source: rpc/user/auth/message.proto

package auth

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 验证用户登录令牌合法性
type ReqUserAuth struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 当前登录用户令牌
	Token string `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
}

func (x *ReqUserAuth) Reset() {
	*x = ReqUserAuth{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_user_auth_message_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqUserAuth) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqUserAuth) ProtoMessage() {}

func (x *ReqUserAuth) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_user_auth_message_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqUserAuth.ProtoReflect.Descriptor instead.
func (*ReqUserAuth) Descriptor() ([]byte, []int) {
	return file_rpc_user_auth_message_proto_rawDescGZIP(), []int{0}
}

func (x *ReqUserAuth) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

// 返回验证用户信息
type RepUserAuth struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uid      uint32 `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Time     uint32 `protobuf:"varint,2,opt,name=time,proto3" json:"time,omitempty"`
	AppId    uint32 `protobuf:"varint,3,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	Salt     string `protobuf:"bytes,4,opt,name=salt,proto3" json:"salt,omitempty"`
	Platform string `protobuf:"bytes,5,opt,name=platform,proto3" json:"platform,omitempty"`
	Channel  string `protobuf:"bytes,6,opt,name=channel,proto3" json:"channel,omitempty"`
}

func (x *RepUserAuth) Reset() {
	*x = RepUserAuth{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_user_auth_message_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RepUserAuth) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RepUserAuth) ProtoMessage() {}

func (x *RepUserAuth) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_user_auth_message_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RepUserAuth.ProtoReflect.Descriptor instead.
func (*RepUserAuth) Descriptor() ([]byte, []int) {
	return file_rpc_user_auth_message_proto_rawDescGZIP(), []int{1}
}

func (x *RepUserAuth) GetUid() uint32 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *RepUserAuth) GetTime() uint32 {
	if x != nil {
		return x.Time
	}
	return 0
}

func (x *RepUserAuth) GetAppId() uint32 {
	if x != nil {
		return x.AppId
	}
	return 0
}

func (x *RepUserAuth) GetSalt() string {
	if x != nil {
		return x.Salt
	}
	return ""
}

func (x *RepUserAuth) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *RepUserAuth) GetChannel() string {
	if x != nil {
		return x.Channel
	}
	return ""
}

var File_rpc_user_auth_message_proto protoreflect.FileDescriptor

var file_rpc_user_auth_message_proto_rawDesc = []byte{
	0x0a, 0x1b, 0x72, 0x70, 0x63, 0x2f, 0x75, 0x73, 0x65, 0x72, 0x2f, 0x61, 0x75, 0x74, 0x68, 0x2f,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0c, 0x72,
	0x62, 0x70, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x22, 0x23, 0x0a, 0x0b, 0x52,
	0x65, 0x71, 0x55, 0x73, 0x65, 0x72, 0x41, 0x75, 0x74, 0x68, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f,
	0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e,
	0x22, 0x94, 0x01, 0x0a, 0x0b, 0x52, 0x65, 0x70, 0x55, 0x73, 0x65, 0x72, 0x41, 0x75, 0x74, 0x68,
	0x12, 0x10, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x03, 0x75,
	0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x04, 0x74, 0x69, 0x6d, 0x65, 0x12, 0x15, 0x0a, 0x06, 0x61, 0x70, 0x70, 0x5f, 0x69, 0x64,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x61, 0x70, 0x70, 0x49, 0x64, 0x12, 0x12, 0x0a,
	0x04, 0x73, 0x61, 0x6c, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x73, 0x61, 0x6c,
	0x74, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x12, 0x18, 0x0a,
	0x07, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x42, 0x37, 0x5a, 0x35, 0x67, 0x69, 0x74, 0x68, 0x75,
	0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6f, 0x6c, 0x61, 0x6f, 0x6c, 0x61, 0x2d, 0x63, 0x68, 0x61,
	0x74, 0x2f, 0x72, 0x62, 0x70, 0x2d, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x67, 0x65, 0x6e, 0x5f,
	0x70, 0x62, 0x2f, 0x72, 0x70, 0x63, 0x2f, 0x75, 0x73, 0x65, 0x72, 0x2f, 0x61, 0x75, 0x74, 0x68,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_rpc_user_auth_message_proto_rawDescOnce sync.Once
	file_rpc_user_auth_message_proto_rawDescData = file_rpc_user_auth_message_proto_rawDesc
)

func file_rpc_user_auth_message_proto_rawDescGZIP() []byte {
	file_rpc_user_auth_message_proto_rawDescOnce.Do(func() {
		file_rpc_user_auth_message_proto_rawDescData = protoimpl.X.CompressGZIP(file_rpc_user_auth_message_proto_rawDescData)
	})
	return file_rpc_user_auth_message_proto_rawDescData
}

var file_rpc_user_auth_message_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_rpc_user_auth_message_proto_goTypes = []interface{}{
	(*ReqUserAuth)(nil), // 0: rbp.rpc.user.ReqUserAuth
	(*RepUserAuth)(nil), // 1: rbp.rpc.user.RepUserAuth
}
var file_rpc_user_auth_message_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_rpc_user_auth_message_proto_init() }
func file_rpc_user_auth_message_proto_init() {
	if File_rpc_user_auth_message_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_rpc_user_auth_message_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReqUserAuth); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_user_auth_message_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RepUserAuth); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_rpc_user_auth_message_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_rpc_user_auth_message_proto_goTypes,
		DependencyIndexes: file_rpc_user_auth_message_proto_depIdxs,
		MessageInfos:      file_rpc_user_auth_message_proto_msgTypes,
	}.Build()
	File_rpc_user_auth_message_proto = out.File
	file_rpc_user_auth_message_proto_rawDesc = nil
	file_rpc_user_auth_message_proto_goTypes = nil
	file_rpc_user_auth_message_proto_depIdxs = nil
}
