
GOCMD=go
GOBUILD=$(GOCMD) build
GOTEST=$(GOCMD) test
GOFMT=gofmt
SHELL=/bin/bash #解决ubuntu下编译报错问题

fmt:
	$(GOFMT) -l -s -w .

lint:
	golangci-lint run ./app/... ./logic/... ./service/... ./db/... ./library/...
	golangci-lint run ./cmd/... ./rpc/...
	go vet ./app/... ./logic/... ./service/... ./library/...
	go vet ./cmd/... ./rpc/...
	go vet ./db/helper/... ./db/cacheobj/...
	go vet ./db/user/... ./db/room/... ./db/gift/... ./db/pay/... ./db/games/... ./db/admin/...
	go vet ./db/activity/... ./db/gs/... ./db/circle/... ./db/im/... ./db/rank/...

test:
	$(GOTEST) -v -count=1 ./... 

