// ============================================================================
// This is auto-generated by gf cli tool only once. Fill this file as you wish.
// ============================================================================

package dao

import (
	"banban/app/dao/internal"
)

// xsAttributionRewardUserDao is the manager for logic model data accessing
// and custom defined data operations functions management. You can define
// methods on it to extend its functionality as you wish.
type xsAttributionRewardUserDao struct {
	internal.XsAttributionRewardUserDao
}

var (
	// XsAttributionRewardUser is globally public accessible object for table xs_attribution_reward_user operations.
	XsAttributionRewardUser = xsAttributionRewardUserDao{
		internal.XsAttributionRewardUser,
	}
)

// Fill with you ideas below.
