// ============================================================================
// This is auto-generated by gf cli tool only once. Fill this file as you wish.
// ============================================================================

package dao

import (
	"banban/app/dao/internal"
)

// xsBenefitUserCardDao is the manager for logic model data accessing
// and custom defined data operations functions management. You can define
// methods on it to extend its functionality as you wish.
type xsBenefitUserCardDao struct {
	internal.XsBenefitUserCardDao
}

var (
	// XsBenefitUserCard is globally public accessible object for table xs_benefit_user_card operations.
	XsBenefitUserCard = xsBenefitUserCardDao{
		internal.XsBenefitUserCard,
	}
)

// Fill with you ideas below.
