// ============================================================================
// This is auto-generated by gf cli tool only once. Fill this file as you wish.
// ============================================================================

package dao

import (
	"banban/app/dao/internal"
)

// xsBenefitDayLogDao is the manager for logic model data accessing
// and custom defined data operations functions management. You can define
// methods on it to extend its functionality as you wish.
type xsBenefitDayLogDao struct {
	internal.XsBenefitDayLogDao
}

var (
	// XsBenefitDayLog is globally public accessible object for table xs_benefit_day_log operations.
	XsBenefitDayLog = xsBenefitDayLogDao{
		internal.XsBenefitDayLog,
	}
)

// Fill with you ideas below.
