// ============================================================================
// This is auto-generated by gf cli tool only once. Fill this file as you wish.
// ============================================================================

package dao

import (
	"banban/app/dao/internal"
)

// xsChatroomUnityGamingDao is the manager for logic model data accessing
// and custom defined data operations functions management. You can define
// methods on it to extend its functionality as you wish.
type xsChatroomUnityGamingDao struct {
	internal.XsChatroomUnityGamingDao
}

var (
	// XsChatroomUnityGaming is globally public accessible object for table xs_chatroom_unity_gaming operations.
	XsChatroomUnityGaming = xsChatroomUnityGamingDao{
		internal.XsChatroomUnityGaming,
	}
)

// Fill with you ideas below.
