// ============================================================================
// This is auto-generated by gf cli tool only once. Fill this file as you wish.
// ============================================================================

package dao

import (
	"banban/app/dao/internal"
)

// xsConsumeLotteryStockDao is the manager for logic model data accessing
// and custom defined data operations functions management. You can define
// methods on it to extend its functionality as you wish.
type xsConsumeLotteryStockDao struct {
	internal.XsConsumeLotteryStockDao
}

var (
	// XsConsumeLotteryStock is globally public accessible object for table xs_consume_lottery_stock operations.
	XsConsumeLotteryStock = xsConsumeLotteryStockDao{
		internal.XsConsumeLotteryStock,
	}
)

// Fill with you ideas below.
