// ============================================================================
// This is auto-generated by gf cli tool only once. Fill this file as you wish.
// ============================================================================

package dao

import (
	"banban/app/dao/internal"
	"banban/app/pb"
	"context"
	"strconv"
	"time"
)

// xsChatroomCharmDayDao is the manager for logic model data accessing
// and custom defined data operations functions management. You can define
// methods on it to extend its functionality as you wish.
type xsChatroomCharmDayDao struct {
	internal.XsChatroomCharmDayDao
}

var (
	// XsChatroomCharmDay is globally public accessible object for table xs_chatroom_charm_day operations.
	XsChatroomCharmDay = xsChatroomCharmDayDao{
		internal.XsChatroomCharmDay,
	}
)

// Fill with you ideas below.
func (d *xsChatroomCharmDayDao) GetTopThreeRecords(ctx context.Context, listType string) []*pb.EntityXsChatroomCharmDay {
	timestamp := time.Now().Unix()
	nowTime := time.Unix(timestamp, 0)
	dayIdx := nowTime.Format("20060102")
	day, err := strconv.ParseInt(dayIdx, 10, 64)

	if err != nil {
		return nil
	}

	records, err := XsChatroomCharmDay.Ctx(ctx).Fields("rid").Order("charm desc").Limit(3).All("day = ? and type = ?", day, listType)
	if err != nil {
		return nil
	}

	return records
}
