// ============================================================================
// This is auto-generated by gf cli tool only once. Fill this file as you wish.
// ============================================================================

package dao

import (
	"banban/app/dao/internal"
)

// xsChatroomAccompanySettingDao is the manager for logic model data accessing
// and custom defined data operations functions management. You can define
// methods on it to extend its functionality as you wish.
type xsChatroomAccompanySettingDao struct {
	internal.XsChatroomAccompanySettingDao
}

var (
	// XsChatroomAccompanySetting is globally public accessible object for table xs_chatroom_accompany_setting operations.
	XsChatroomAccompanySetting = xsChatroomAccompanySettingDao{
		internal.XsChatroomAccompanySetting,
	}
)

// Fill with you ideas below.
