// ============================================================================
// This is auto-generated by gf cli tool only once. Fill this file as you wish.
// ============================================================================

package dao

import (
	"banban/app/dao/internal"
)

// xsChatroomExtendUnderDao is the manager for logic model data accessing
// and custom defined data operations functions management. You can define
// methods on it to extend its functionality as you wish.
type xsChatroomExtendUnderDao struct {
	internal.XsChatroomExtendUnderDao
}

var (
	// XsChatroomExtendUnder is globally public accessible object for table xs_chatroom_extend_under operations.
	XsChatroomExtendUnder = xsChatroomExtendUnderDao{
		internal.XsChatroomExtendUnder,
	}
)

// Fill with you ideas below.
