// ============================================================================
// This is auto-generated by gf cli tool only once. Fill this file as you wish.
// ============================================================================

package dao

import (
	"banban/app/dao/internal"
)

// xsFcardVideoDetailDao is the manager for logic model data accessing
// and custom defined data operations functions management. You can define
// methods on it to extend its functionality as you wish.
type xsFcardVideoDetailDao struct {
	internal.XsFcardVideoDetailDao
}

var (
	// XsFcardVideoDetail is globally public accessible object for table xs_fcard_video_detail operations.
	XsFcardVideoDetail = xsFcardVideoDetailDao{
		internal.XsFcardVideoDetail,
	}
)

// Fill with you ideas below.
