// ============================================================================
// This is auto-generated by gf cli tool only once. Fill this file as you wish.
// ============================================================================

package xianshi

import (
	"github.com/olaola-chat/slp-proto/dao/xianshi/internal"
)

// xsGiftWallDetailDao is the manager for logic model data accessing
// and custom defined data operations functions management. You can define
// methods on it to extend its functionality as you wish.
type xsGiftWallDetailDao struct {
	internal.XsGiftWallDetailDao
}

var (
	// XsGiftWallDetail is globally public accessible object for table xs_gift_wall_detail operations.
	XsGiftWallDetail = xsGiftWallDetailDao{
		internal.XsGiftWallDetail,
	}
)

// Fill with you ideas below.
