// ============================================================================
// This is auto-generated by gf cli tool only once. Fill this file as you wish.
// ============================================================================

package dao

import (
	"banban/app/dao/internal"
)

// xsGlobalBoxDao is the manager for logic model data accessing
// and custom defined data operations functions management. You can define
// methods on it to extend its functionality as you wish.
type xsGlobalBoxDao struct {
	internal.XsGlobalBoxDao
}

var (
	// XsGlobalBox is globally public accessible object for table xs_global_box operations.
	XsGlobalBox = xsGlobalBoxDao{
		internal.XsGlobalBox,
	}
)

// Fill with you ideas below.
