// ============================================================================
// This is auto-generated by gf cli tool only once. Fill this file as you wish.
// ============================================================================

package dao

import (
	"banban/app/dao/internal"
)

// xsGroupApplyDao is the manager for logic model data accessing
// and custom defined data operations functions management. You can define
// methods on it to extend its functionality as you wish.
type xsGroupApplyDao struct {
	internal.XsGroupApplyDao
}

var (
	// XsGroupApply is globally public accessible object for table xs_group_apply operations.
	XsGroupApply = xsGroupApplyDao{
		internal.XsGroupApply,
	}
)

// Fill with you ideas below.
