// ============================================================================
// This is auto-generated by gf cli tool only once. Fill this file as you wish.
// ============================================================================

package dao

import (
	"banban/app/dao/internal"
)

// xsQuickReplyGroupDao is the manager for logic model data accessing
// and custom defined data operations functions management. You can define
// methods on it to extend its functionality as you wish.
type xsQuickReplyGroupDao struct {
	internal.XsQuickReplyGroupDao
}

var (
	// XsQuickReplyGroup is globally public accessible object for table xs_quick_reply_group operations.
	XsQuickReplyGroup = xsQuickReplyGroupDao{
		internal.XsQuickReplyGroup,
	}
)

// Fill with you ideas below.
