// ============================================================================
// This is auto-generated by gf cli tool only once. Fill this file as you wish.
// ============================================================================

package dao

import (
	"banban/app/dao/internal"
)

// xsRelationDefendDao is the manager for logic model data accessing
// and custom defined data operations functions management. You can define
// methods on it to extend its functionality as you wish.
type xsRelationDefendDao struct {
	internal.XsRelationDefendDao
}

var (
	// XsRelationDefend is globally public accessible object for table xs_relation_defend operations.
	XsRelationDefend = xsRelationDefendDao{
		internal.XsRelationDefend,
	}
)

// Fill with you ideas below.
