// ============================================================================
// This is auto-generated by gf cli tool only once. Fill this file as you wish.
// ============================================================================

package dao

import (
	"banban/app/dao/internal"
)

// xsTagMatchFloatingWindowTimestampDao is the manager for logic model data accessing
// and custom defined data operations functions management. You can define
// methods on it to extend its functionality as you wish.
type xsTagMatchFloatingWindowTimestampDao struct {
	internal.XsTagMatchFloatingWindowTimestampDao
}

var (
	// XsTagMatchFloatingWindowTimestamp is globally public accessible object for table xs_tag_match_floating_window_timestamp operations.
	XsTagMatchFloatingWindowTimestamp = xsTagMatchFloatingWindowTimestampDao{
		internal.XsTagMatchFloatingWindowTimestamp,
	}
)

// Fill with you ideas below.
