// ============================================================================
// This is auto-generated by gf cli tool only once. Fill this file as you wish.
// ============================================================================

package dao

import (
	"banban/app/dao/internal"
)

// xsTagDetailDao is the manager for logic model data accessing
// and custom defined data operations functions management. You can define
// methods on it to extend its functionality as you wish.
type xsTagDetailDao struct {
	internal.XsTagDetailDao
}

var (
	// XsTagDetail is globally public accessible object for table xs_tag_detail operations.
	XsTagDetail = xsTagDetailDao{
		internal.XsTagDetail,
	}
)

// Fill with you ideas below.
