// ============================================================================
// This is auto-generated by gf cli tool only once. Fill this file as you wish.
// ============================================================================

package dao

import (
	"banban/app/dao/internal"
)

// xsUserAddrBookDao is the manager for logic model data accessing
// and custom defined data operations functions management. You can define
// methods on it to extend its functionality as you wish.
type xsUserAddrBookDao struct {
	internal.XsUserAddrBookDao
}

var (
	// XsUserAddrBook is globally public accessible object for table xs_user_addr_book operations.
	XsUserAddrBook = xsUserAddrBookDao{
		internal.XsUserAddrBook,
	}
)

// Fill with you ideas below.
