// ============================================================================
// This is auto-generated by gf cli tool only once. Fill this file as you wish.
// ============================================================================

package dao

import (
	"banban/app/dao/internal"
)

// xsUnityUserRecordDao is the manager for logic model data accessing
// and custom defined data operations functions management. You can define
// methods on it to extend its functionality as you wish.
type xsUnityUserRecordDao struct {
	internal.XsUnityUserRecordDao
}

var (
	// XsUnityUserRecord is globally public accessible object for table xs_unity_user_record operations.
	XsUnityUserRecord = xsUnityUserRecordDao{
		internal.XsUnityUserRecord,
	}
)

// Fill with you ideas below.
