// ============================================================================
// This is auto-generated by gf cli tool only once. Fill this file as you wish.
// ============================================================================

package dao

import (
	"banban/app/dao/internal"
)

// xsUserJubenProfileDao is the manager for logic model data accessing
// and custom defined data operations functions management. You can define
// methods on it to extend its functionality as you wish.
type xsUserJubenProfileDao struct {
	internal.XsUserJubenProfileDao
}

var (
	// XsUserJubenProfile is globally public accessible object for table xs_user_juben_profile operations.
	XsUserJubenProfile = xsUserJubenProfileDao{
		internal.XsUserJubenProfile,
	}
)

// Fill with you ideas below.
