// ============================================================================
// This is auto-generated by gf cli tool only once. Fill this file as you wish.
// ============================================================================

package dao

import (
	"banban/app/dao/internal"
)

// xsUserMoneyDao is the manager for logic model data accessing
// and custom defined data operations functions management. You can define
// methods on it to extend its functionality as you wish.
type xsUserMoneyDao struct {
	internal.XsUserMoneyDao
}

var (
	// XsUserMoney is globally public accessible object for table xs_user_money operations.
	XsUserMoney = xsUserMoneyDao{
		internal.XsUserMoney,
	}
)

// Fill with you ideas below.
