// ============================================================================
// This is auto-generated by gf cli tool only once. Fill this file as you wish.
// ============================================================================

package dao

import (
	"banban/app/dao/internal"
)

// xsUserPhotoMarkDao is the manager for logic model data accessing
// and custom defined data operations functions management. You can define
// methods on it to extend its functionality as you wish.
type xsUserPhotoMarkDao struct {
	internal.XsUserPhotoMarkDao
}

var (
	// XsUserPhotoMark is globally public accessible object for table xs_user_photo_mark operations.
	XsUserPhotoMark = xsUserPhotoMarkDao{
		internal.XsUserPhotoMark,
	}
)

// Fill with you ideas below.
