// ============================================================================
// This is auto-generated by gf cli tool only once. Fill this file as you wish.
// ============================================================================

package dao

import (
	"banban/app/dao/internal"
)

// xsWbkPickRecordDao is the manager for logic model data accessing
// and custom defined data operations functions management. You can define
// methods on it to extend its functionality as you wish.
type xsWbkPickRecordDao struct {
	internal.XsWbkPickRecordDao
}

var (
	// XsWbkPickRecord is globally public accessible object for table xs_wbk_pick_record operations.
	XsWbkPickRecord = xsWbkPickRecordDao{
		internal.XsWbkPickRecord,
	}
)

// Fill with you ideas below.
