// ============================================================================
// This is auto-generated by gf cli tool only once. Fill this file as you wish.
// ============================================================================

package functor

import (
	"github.com/olaola-chat/rbp-proto/dao/functor/internal"
)

// voiceLoverAwardPackageDao is the manager for logic model data accessing
// and custom defined data operations functions management. You can define
// methods on it to extend its functionality as you wish.
type voiceLoverAwardPackageDao struct {
	internal.VoiceLoverAwardPackageDao
}

var (
	// VoiceLoverAwardPackage is globally public accessible object for table voice_lover_award_package operations.
	VoiceLoverAwardPackage = voiceLoverAwardPackageDao{
		internal.VoiceLoverAwardPackage,
	}
)

// Fill with you ideas below.
