// ============================================================================
// This is auto-generated by gf cli tool only once. Fill this file as you wish.
// ============================================================================

package functor

import (
	"github.com/olaola-chat/slp-proto/dao/functor/internal"
)

// voiceLoverAlbumSubjectDao is the manager for logic model data accessing
// and custom defined data operations functions management. You can define
// methods on it to extend its functionality as you wish.
type voiceLoverAlbumSubjectDao struct {
	internal.VoiceLoverAlbumSubjectDao
}

var (
	// VoiceLoverAlbumSubject is globally public accessible object for table voice_lover_album_subject operations.
	VoiceLoverAlbumSubject = voiceLoverAlbumSubjectDao{
		internal.VoiceLoverAlbumSubject,
	}
)

// Fill with you ideas below.
