# HTTP Server.
[server]
	Address        = ":9090"
	ServerRoot     = "public"
	ServerAgent    = "we are family"
	LogPath        = "/tmp/log/server"
	AccessLogEnabled = true
	ErrorLogEnabled = true
	PProfEnabled   = true
	Graceful	       = true
	RunMode	       = "dev"
	Language		   = ["zh-cn"]
	TraceName	   = "test"

# Logger configurations.
[logger]
    Path   = "/tmp/log/server"
    Level  = "all"
    Stdout = true
    CtxKeys = ["TraceId"]

# Template view configurations.
[viewer]
    Path        = "template"
    DefaultFile = "index.html"

# Database configurations.
[database]
	#xianshi库
    [[database.xianshi]]
        type = "bbsql"
        link = "root:123456@tcp(127.0.0.1:3306)/xianshi"
        charset = "utf8mb4"
        debug = true
        maxIdle = 1
        maxOpen = 100
        maxLifetime = 30
    # 数据库日志对象配置
    [database.logger]
        Path   = "/tmp/log/sql"
        Level  = "all"
        Stdout = true
	#rush库
	[[database.rush]]
		type = "bbsql"
		link = "root:123456@tcp(127.0.0.1:3306)/rush"
		charset = "utf8mb4"
		debug = true
		maxIdle = 1
		maxOpen = 100
		maxLifetime  = 30
	#联盟库
	[[database.bbu]]
		type = "bbsql"
		link = "root:123456@tcp(127.0.0.1:3306)/banban_union"
		charset = "utf8mb4"
		debug = true
		maxIdle = 1
		maxOpen = 100
		maxLifetime  = 30
	#数据统计库
	[[database.banban]]
		type = "bbsql"
		link = "root:123456@tcp(127.0.0.1:3306)/banban"
		charset = "utf8mb4"
		debug = true
		maxIdle = 1
		maxOpen = 100
		maxLifetime  = 30
	#配置库
	[[database.config]]
		type = "bbsql"
		link = "root:123456@tcp(127.0.0.1:3306)/config"
		charset = "utf8mb4"
		debug = true
		maxIdle = 1
		maxOpen = 100
		maxLifetime  = 30
	#xsst库
	[[database.xsst]]
		type = "bbsql"
		link = "root:123456@tcp(127.0.0.1:3306)/xsst"
		charset = "utf8mb4"
		debug = true
		maxIdle = 1
		maxOpen = 100
		maxLifetime  = 30
    #朋友圈主库
    [[database.circle]]
        type = "bbsql"
        link = "root:123456@tcp(127.0.0.1:3306)/circle_dev"
        charset = "utf8mb4"
        debug = true
        maxIdle = 1
        maxOpen = 100
        maxLifetime = 30
        role = "master"
    #朋友圈从库
    [[database.circle]]
        type = "bbsql"
        link = "root:123456@tcp(127.0.0.1:3306)/circle_dev"
        charset = "utf8mb4"
        debug = true
        maxIdle = 1
        maxOpen = 100
        maxLifetime = 30
        role = "slave"

[rpc]
	[rpc.discover]
		Type = "consul"
		Addr = ["127.0.0.1:8500"]
		Path = "/banban"


# GF-CLI工具配置
[gfcli]
    # 自定义DAO生成配置(默认是读取database配置)
    [[gfcli.gen.dao]]
		link   = "mysql:root:123456@tcp(172.16.1.63:3306)/config"
		#link   = "mysql:root:123456@tcp(172.16.1.63:3306)/xianshi"
		jsonCase = "Snake"
	[[gfcli.gen.pbentity]]
		link    = "mysql:root:123456@tcp(172.16.1.63:3306)/config"
		#link    = "mysql:root:123456@tcp(172.16.1.63:3306)/xianshi"
		path    = "proto"
		jsonCase = "Snake"
		package = "pb"
		option 	= "option go_package = \"../app/pb\";"
