# Database configurations.
[database]
	#xianshi库
    [[database.xianshi]]
        type = "mysql"
        link = "root:123456@tcp(114.55.3.96:8547)/xianshi"
        charset = "utf8mb4"
        debug = true
        maxIdle = 1
        maxOpen = 100
        maxLifetime = 30
    # 数据库日志对象配置
    [database.logger]
        Path   = "/tmp/log/sql"
        Level  = "all"
        Stdout = true
	#rush库
	[[database.rush]]
		type = "bbsql"
		link = "root:123456@tcp(114.55.3.96:8547)/rush"
		charset = "utf8mb4"
		debug = true
		maxIdle = 1
		maxOpen = 100
		maxLifetime  = 30
	#联盟库
	[[database.bbu]]
		type = "bbsql"
		link = "root:123456@tcp(114.55.3.96:8547)/banban_union"
		charset = "utf8mb4"
		debug = true
		maxIdle = 1
		maxOpen = 100
		maxLifetime  = 30
	#数据统计库
	[[database.banban]]
		type = "bbsql"
		link = "root:123456@tcp(114.55.3.96:8547)/banban"
		charset = "utf8mb4"
		debug = true
		maxIdle = 1
		maxOpen = 100
		maxLifetime  = 30
	#配置库
	[[database.config]]
		type = "bbsql"
		link = "root:123456@tcp(114.55.3.96:8547)/config"
		charset = "utf8mb4"
		debug = true
		maxIdle = 1
		maxOpen = 100
		maxLifetime  = 30
    #朋友圈主库
    [[database.circle]]
        type = "bbsql"
        link = "root:123456@tcp(114.55.3.96:8547)/circle_dev"
        charset = "utf8mb4"
        debug = true
        maxIdle = 1
        maxOpen = 100
        maxLifetime = 30
    [[database.activity]]
        type = "bbsql"
        link = "root:123456@tcp(114.55.3.96:8547)/activity"
        charset = "utf8mb4"
        debug = true
        maxIdle = 1
        maxOpen = 100
        maxLifetime = 30

[rpc]
	[rpc.discover]
		Type = "consul"
		Addr = ["127.0.0.1:8500"]
		Path = "/slp"


