# Database configurations.
[database]
    [[database.default]]
        type = "bbsql"
        link = "root:123456@tcp(127.0.0.1:3306)/xianshi"
        charset = "utf8mb4"
        debug = true
        maxIdle = 1
        maxOpen = 100
        maxLifetime = 30
	#xianshi库
    [[database.xianshi]]
        type = "bbsql"
        link = "root:123456@tcp(127.0.0.1:3306)/xianshi"
        charset = "utf8mb4"
        debug = true
        maxIdle = 1
        maxOpen = 100
        maxLifetime = 30
    # 数据库日志对象配置
    [database.logger]
        Path   = "/tmp/log/sql"
        Level  = "all"
        Stdout = true
	#rush库
	[[database.rush]]
		type = "bbsql"
		link = "root:123456@tcp(127.0.0.1:3306)/rush"
		charset = "utf8mb4"
		debug = true
		maxIdle = 1
		maxOpen = 100
		maxLifetime  = 30
	#联盟库
	[[database.bbu]]
		type = "bbsql"
		link = "root:123456@tcp(127.0.0.1:3306)/banban_union"
		charset = "utf8mb4"
		debug = true
		maxIdle = 1
		maxOpen = 100
		maxLifetime  = 30
	#数据统计库
	[[database.banban]]
		type = "bbsql"
		link = "root:123456@tcp(127.0.0.1:3306)/banban"
		charset = "utf8mb4"
		debug = true
		maxIdle = 1
		maxOpen = 100
		maxLifetime  = 30
	#配置库
	[[database.config]]
		type = "bbsql"
		link = "root:123456@tcp(127.0.0.1:3306)/config"
		charset = "utf8mb4"
		debug = true
		maxIdle = 1
		maxOpen = 100
		maxLifetime  = 30
    #朋友圈主库
    [[database.circle]]
        type = "bbsql"
        link = "root:123456@tcp(127.0.0.1:3306)/circle_dev"
        charset = "utf8mb4"
        debug = true
        maxIdle = 1
        maxOpen = 100
        maxLifetime = 30

# GF-CLI工具配置
[gfcli]
    # 自定义DAO生成配置(默认是读取database配置)
    [[gfcli.gen.dao]]
		mod = "github.com/olaola-chat/rbp-proto"
        jsonCase = "Snake"
		path = "./"
        tplDaoIndex = "daoindex.tpl"
        tplModelIndex = "modelindex.tpl"
	[[gfcli.gen.pbentity]]
		path    = "../proto"
		jsonCase = "Snake"
		package = "pb"
		option 	= "option go_package = \"./pb\";"
