# Database configurations.
[database]
    [[database.default]]
        type = "bbsql"
        link = "root:root@tcp(47.99.171.114:3306)/xianshi"
        charset = "utf8mb4"
        debug = true
        maxIdle = 1
        maxOpen = 100
        maxLifetime = 30
	#xianshi库
    [[database.xianshi]]
        type = "bbsql"
        link = "root:root@tcp(47.99.171.114:3306)/xianshi"
        charset = "utf8mb4"
        debug = true
        maxIdle = 1
        maxOpen = 100
        maxLifetime = 30
    # 数据库日志对象配置
    [database.logger]
        Path   = "/tmp/log/sql"
        Level  = "all"
        Stdout = true
	#rush库
	[[database.rush]]
		type = "bbsql"
		link = "root:root@tcp(47.99.171.114:3306)/rush"
		charset = "utf8mb4"
		debug = true
		maxIdle = 1
		maxOpen = 100
		maxLifetime  = 30
	#联盟库
	[[database.bbu]]
		type = "bbsql"
		link = "root:root@tcp(47.99.171.114:3306)/banban_union"
		charset = "utf8mb4"
		debug = true
		maxIdle = 1
		maxOpen = 100
		maxLifetime  = 30
	#数据统计库
	[[database.banban]]
		type = "bbsql"
		link = "root:root@tcp(47.99.171.114:3306)/banban"
		charset = "utf8mb4"
		debug = true
		maxIdle = 1
		maxOpen = 100
		maxLifetime  = 30
	#配置库
	[[database.config]]
		type = "bbsql"
		link = "root:root@tcp(47.99.171.114:3306)/config"
		charset = "utf8mb4"
		debug = true
		maxIdle = 1
		maxOpen = 100
		maxLifetime  = 30
    #朋友圈主库
    [[database.circle]]
        type = "bbsql"
        link = "root:root@tcp(47.99.171.114:3306)/circle_dev"
        charset = "utf8mb4"
        debug = true
        maxIdle = 1
        maxOpen = 100
        maxLifetime = 30
    [[database.activity]]
        type = "bbsql"
        link = "root:root@tcp(47.99.171.114:3306)/activity"
        charset = "utf8mb4"
        debug = true
        maxIdle = 1
        maxOpen = 100
        maxLifetime = 30
    [[database.functor]]
        type = "bbsql"
        link = "root:root@tcp(47.99.171.114:3306)/functor"
        charset = "utf8mb4"
        debug = true
        maxIdle = 1
        maxOpen = 100
        maxLifetime = 30

# GF-CLI工具配置
[gfcli]
    # 自定义DAO生成配置(默认是读取database配置)
    [[gfcli.gen.dao]]
        link = "mysql:root:root@tcp(47.99.171.114:3306)/functor"
        mod = "github.com/olaola-chat/slp-proto"
        jsonCase = "Snake"
        path = "./"
        tplDaoIndex = "config/daoindex.tpl"
        tplDaoInternal = "config/dao_internal.tpl"
    [[gfcli.gen.pbentity]]
        link = "mysql:root:root@tcp(47.99.171.114:3306)/functor"
        jsonCase = "Snake"
        package = "pb"
        option 	= "option go_package = \"./gen_pb\";"
