// ==========================================================================   
// This is auto-generated by gf cli tool. Fill this file as you wish.              
// ==========================================================================   
                                                                                   
package model                                                                      
                                                                                   
import (                                                                           
    "{TplImportPrefix}/model/dbname/internal"                                             
)                                                                                  
                                                                                   
// {TplTableNameCamelCase} is the golang structure for table {TplTableName}.       
type {TplTableNameCamelCase} internal.{TplTableNameCamelCase}                      
                                                                                   
// Fill with you ideas below.
