// ==========================================================================
// This is auto-generated by gf cli tool. Fill this file as you wish.
// ==========================================================================

package model

import (
	"banban/app/model/internal"
)

// XsAgoraMusic is the golang structure for table xs_agora_music.
type XsAgoraMusic internal.XsAgoraMusic

// Fill with you ideas below.
