// ==========================================================================
// This is auto-generated by gf cli tool. Fill this file as you wish.
// ==========================================================================

package model

import (
	"banban/app/model/internal"
)

// XsAnchorGsCredit is the golang structure for table xs_anchor_gs_credit.
type XsAnchorGsCredit internal.XsAnchorGsCredit

// Fill with you ideas below.
