// ==========================================================================
// This is auto-generated by gf cli tool. Fill this file as you wish.
// ==========================================================================

package model

import (
	"banban/app/model/internal"
)

// XsAnchorGsCreditChangeRecord is the golang structure for table xs_anchor_gs_credit_change_record.
type XsAnchorGsCreditChangeRecord internal.XsAnchorGsCreditChangeRecord

// Fill with you ideas below.
