// ==========================================================================
// This is auto-generated by gf cli tool. Fill this file as you wish.
// ==========================================================================

package model

import (
	"banban/app/model/internal"
)

// XsCommodityGroup is the golang structure for table xs_commodity_group.
type XsCommodityGroup internal.XsCommodityGroup

// Fill with you ideas below.
