// ==========================================================================
// This is auto-generated by gf cli tool. Fill this file as you wish.
// ==========================================================================

package model

import (
	"banban/app/model/internal"
)

// XsDiyGiftConfig is the golang structure for table xs_diy_gift_config.
type XsDiyGiftConfig internal.XsDiyGiftConfig

// Fill with you ideas below.
