// ==========================================================================
// This is auto-generated by gf cli tool. Fill this file as you wish.
// ==========================================================================

package model

import (
	"banban/app/model/internal"
)

// XsFcardTagDetail is the golang structure for table xs_fcard_tag_detail.
type XsFcardTagDetail internal.XsFcardTagDetail

// Fill with you ideas below.
