// ==========================================================================
// This is auto-generated by gf cli tool. Fill this file as you wish.
// ==========================================================================

package model

import (
	"banban/app/model/internal"
)

// XsGift is the golang structure for table xs_gift.
type XsGift internal.XsGift

// Fill with you ideas below.
