// ==========================================================================
// This is auto-generated by gf cli tool. Fill this file as you wish.
// ==========================================================================

package model

import (
	"banban/app/model/internal"
)

// XsGiftWallRecord is the golang structure for table xs_gift_wall_record.
type XsGiftWallRecord internal.XsGiftWallRecord

// Fill with you ideas below.
