// ==========================================================================
// This is auto-generated by gf cli tool. Fill this file as you wish.
// ==========================================================================

package model

import (
	"banban/app/model/internal"
)

// XsGroupApply is the golang structure for table xs_group_apply.
type XsGroupApply internal.XsGroupApply

// Fill with you ideas below.
