// ==========================================================================
// This is auto-generated by gf cli tool. Fill this file as you wish.
// ==========================================================================

package model

import (
	"banban/app/model/internal"
)

// XsGiftNaming is the golang structure for table xs_gift_naming.
type XsGiftNaming internal.XsGiftNaming

// Fill with you ideas below.
