// ==========================================================================
// This is auto-generated by gf cli tool. Fill this file as you wish.
// ==========================================================================

package model

import (
	"banban/app/model/internal"
)

// XsHeartflipRecord is the golang structure for table xs_heartflip_record.
type XsHeartflipRecord internal.XsHeartflipRecord

// Fill with you ideas below.
