// ==========================================================================
// This is auto-generated by gf cli tool. Fill this file as you wish.
// ==========================================================================

package model

import (
	"banban/app/model/internal"
)

// XsJubenTitle is the golang structure for table xs_juben_title.
type XsJubenTitle internal.XsJubenTitle

// Fill with you ideas below.
