// ==========================================================================
// This is auto-generated by gf cli tool. Fill this file as you wish.
// ==========================================================================

package model

import (
	"banban/app/model/internal"
)

// XsOrderGift is the golang structure for table xs_order_gift.
type XsOrderGift internal.XsOrderGift

// Fill with you ideas below.
