// ==========================================================================
// This is auto-generated by gf cli tool. Fill this file as you wish.
// ==========================================================================

package model

import (
	"banban/app/model/internal"
)

// XsPushToken is the golang structure for table xs_push_token.
type XsPushToken internal.XsPushToken

// Fill with you ideas below.
