// ==========================================================================
// This is auto-generated by gf cli tool. Fill this file as you wish.
// ==========================================================================

package model

import (
	"banban/app/model/internal"
)

// XsPuzzleScoreAll is the golang structure for table xs_puzzle_score_all.
type XsPuzzleScoreAll internal.XsPuzzleScoreAll

// Fill with you ideas below.
