// ==========================================================================
// This is auto-generated by gf cli tool. Fill this file as you wish.
// ==========================================================================

package model

import (
	"banban/app/model/internal"
)

// XsRelationDefend is the golang structure for table xs_relation_defend.
type XsRelationDefend internal.XsRelationDefend

// Fill with you ideas below.
