// ==========================================================================
// This is auto-generated by gf cli tool. Fill this file as you wish.
// ==========================================================================

package model

import (
	"banban/app/model/internal"
)

// XsRoomVipCardDesc is the golang structure for table xs_room_vip_card_desc.
type XsRoomVipCardDesc internal.XsRoomVipCardDesc

// Fill with you ideas below.
