// ==========================================================================
// This is auto-generated by gf cli tool. Fill this file as you wish.
// ==========================================================================

package model

import (
	"banban/app/model/internal"
)

// XsUserCommodity is the golang structure for table xs_user_commodity.
type XsUserCommodity internal.XsUserCommodity

// Fill with you ideas below.
