// ==========================================================================
// This is auto-generated by gf cli tool. Fill this file as you wish.
// ==========================================================================

package model

import (
	"banban/app/model/internal"
)

// XsUserCpHouseInvite is the golang structure for table xs_user_cp_house_invite.
type XsUserCpHouseInvite internal.XsUserCpHouseInvite

// Fill with you ideas below.
