// ==========================================================================
// This is auto-generated by gf cli tool. Fill this file as you wish.
// ==========================================================================

package model

import (
	"banban/app/model/internal"
)

// XsUserChatGift is the golang structure for table xs_user_chat_gift.
type XsUserChatGift internal.XsUserChatGift

// Fill with you ideas below.
