// ==========================================================================
// This is auto-generated by gf cli tool. Fill this file as you wish.
// ==========================================================================

package model

import (
	"banban/app/model/internal"
)

// XsUserPiadramaOrder is the golang structure for table xs_user_piadrama_order.
type XsUserPiadramaOrder internal.XsUserPiadramaOrder

// Fill with you ideas below.
