// ==========================================================================
// This is auto-generated by gf cli tool. Fill this file as you wish.
// ==========================================================================

package model

import (
	"banban/app/model/internal"
)

// XsUserHot is the golang structure for table xs_user_hot.
type XsUserHot internal.XsUserHot

// Fill with you ideas below.
