// ==========================================================================
// This is auto-generated by gf cli tool. Fill this file as you wish.
// ==========================================================================

package model

import (
	"banban/app/model/internal"
)

// XsUserBox is the golang structure for table xs_user_box.
type XsUserBox internal.XsUserBox

// Fill with you ideas below.
