// ==========================================================================
// This is auto-generated by gf cli tool. Fill this file as you wish.
// ==========================================================================

package model

import (
	"banban/app/model/internal"
)

// XsUserFamiliarNew is the golang structure for table xs_user_familiar_new.
type XsUserFamiliarNew internal.XsUserFamiliarNew

// Fill with you ideas below.
