// ==========================================================================
// This is auto-generated by gf cli tool. Fill this file as you wish.
// ==========================================================================

package model

import (
	"banban/app/model/internal"
)

// XsUserAntiAuction is the golang structure for table xs_user_anti_auction.
type XsUserAntiAuction internal.XsUserAntiAuction

// Fill with you ideas below.
