// ==========================================================================
// This is auto-generated by gf cli tool. Fill this file as you wish.
// ==========================================================================

package model

import (
	"banban/app/model/internal"
)

// XsUnityUserRecord is the golang structure for table xs_unity_user_record.
type XsUnityUserRecord internal.XsUnityUserRecord

// Fill with you ideas below.
