// ==========================================================================
// This is auto-generated by gf cli tool. Fill this file as you wish.
// ==========================================================================

package model

import (
	"banban/app/model/internal"
)

// XsUserRoomTagInfo is the golang structure for table xs_user_room_tag_info.
type XsUserRoomTagInfo internal.XsUserRoomTagInfo

// Fill with you ideas below.
