// ==========================================================================
// This is auto-generated by gf cli tool. Fill this file as you wish.
// ==========================================================================

package model

import (
	"banban/app/model/internal"
)

// XsUserJubenHistory is the golang structure for table xs_user_juben_history.
type XsUserJubenHistory internal.XsUserJubenHistory

// Fill with you ideas below.
