// ==========================================================================
// This is auto-generated by gf cli tool. Fill this file as you wish.
// ==========================================================================

package model

import (
	"banban/app/model/internal"
)

// XsUserSafeMobile is the golang structure for table xs_user_safe_mobile.
type XsUserSafeMobile internal.XsUserSafeMobile

// Fill with you ideas below.
