// ==========================================================================
// This is auto-generated by gf cli tool. Fill this file as you wish.
// ==========================================================================

package model

import (
	"banban/app/model/internal"
)

// XsUserAnonymousPermission is the golang structure for table xs_user_anonymous_permission.
type XsUserAnonymousPermission internal.XsUserAnonymousPermission

// Fill with you ideas below.
