// ==========================================================================
// This is auto-generated by gf cli tool. Fill this file as you wish.
// ==========================================================================

package model

import (
	"banban/app/model/internal"
)

// XsUserTransferReason is the golang structure for table xs_user_transfer_reason.
type XsUserTransferReason internal.XsUserTransferReason

// Fill with you ideas below.
