// ==========================================================================
// This is auto-generated by gf cli tool. Fill this file as you wish.
// ==========================================================================

package model

import (
	"banban/app/model/internal"
)

// XsVehicleTeamTitle is the golang structure for table xs_vehicle_team_title.
type XsVehicleTeamTitle internal.XsVehicleTeamTitle

// Fill with you ideas below.
