// ==========================================================================
// This is auto-generated by gf cli tool. DO NOT EDIT THIS FILE MANUALLY.
// 重要! 增加数据库字段，只能向后增加，否则不能使用工具生成proto
// ==========================================================================

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.23.0
// 	protoc        v3.15.5
// source: db/config/entity_voice_lover_award_package.proto

package config

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type EntityVoiceLoverAwardPackage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	//@inject_tag: orm:"id,primary"
	Id uint32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty" orm:"id,primary"` //
	//@inject_tag: orm:"name"
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty" orm:"name"` // 名称
	//@inject_tag: orm:"awards"
	Awards string `protobuf:"bytes,3,opt,name=awards,proto3" json:"awards,omitempty" orm:"awards"` // 奖励内容，json格式
	//@inject_tag: orm:"create_time"
	CreateTime uint32 `protobuf:"varint,4,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty" orm:"create_time"` //
	//@inject_tag: orm:"update_time"
	UpdateTime uint32 `protobuf:"varint,5,opt,name=update_time,json=updateTime,proto3" json:"update_time,omitempty" orm:"update_time"` //
}

func (x *EntityVoiceLoverAwardPackage) Reset() {
	*x = EntityVoiceLoverAwardPackage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_db_config_entity_voice_lover_award_package_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EntityVoiceLoverAwardPackage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EntityVoiceLoverAwardPackage) ProtoMessage() {}

func (x *EntityVoiceLoverAwardPackage) ProtoReflect() protoreflect.Message {
	mi := &file_db_config_entity_voice_lover_award_package_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EntityVoiceLoverAwardPackage.ProtoReflect.Descriptor instead.
func (*EntityVoiceLoverAwardPackage) Descriptor() ([]byte, []int) {
	return file_db_config_entity_voice_lover_award_package_proto_rawDescGZIP(), []int{0}
}

func (x *EntityVoiceLoverAwardPackage) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *EntityVoiceLoverAwardPackage) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *EntityVoiceLoverAwardPackage) GetAwards() string {
	if x != nil {
		return x.Awards
	}
	return ""
}

func (x *EntityVoiceLoverAwardPackage) GetCreateTime() uint32 {
	if x != nil {
		return x.CreateTime
	}
	return 0
}

func (x *EntityVoiceLoverAwardPackage) GetUpdateTime() uint32 {
	if x != nil {
		return x.UpdateTime
	}
	return 0
}

var File_db_config_entity_voice_lover_award_package_proto protoreflect.FileDescriptor

var file_db_config_entity_voice_lover_award_package_proto_rawDesc = []byte{
	0x0a, 0x30, 0x64, 0x62, 0x2f, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2f, 0x65, 0x6e, 0x74, 0x69,
	0x74, 0x79, 0x5f, 0x76, 0x6f, 0x69, 0x63, 0x65, 0x5f, 0x6c, 0x6f, 0x76, 0x65, 0x72, 0x5f, 0x61,
	0x77, 0x61, 0x72, 0x64, 0x5f, 0x70, 0x61, 0x63, 0x6b, 0x61, 0x67, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x09, 0x64, 0x62, 0x2e, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x22, 0x9c, 0x01,
	0x0a, 0x1c, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x56, 0x6f, 0x69, 0x63, 0x65, 0x4c, 0x6f, 0x76,
	0x65, 0x72, 0x41, 0x77, 0x61, 0x72, 0x64, 0x50, 0x61, 0x63, 0x6b, 0x61, 0x67, 0x65, 0x12, 0x0e,
	0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12,
	0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x77, 0x61, 0x72, 0x64, 0x73, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x61, 0x77, 0x61, 0x72, 0x64, 0x73, 0x12, 0x1f, 0x0a, 0x0b, 0x63, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0d, 0x52,
	0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x75,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x0a, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x42, 0x33, 0x5a, 0x31,
	0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6f, 0x6c, 0x61, 0x6f, 0x6c,
	0x61, 0x2d, 0x63, 0x68, 0x61, 0x74, 0x2f, 0x72, 0x62, 0x70, 0x2d, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2f, 0x67, 0x65, 0x6e, 0x5f, 0x70, 0x62, 0x2f, 0x64, 0x62, 0x2f, 0x63, 0x6f, 0x6e, 0x66, 0x69,
	0x67, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_db_config_entity_voice_lover_award_package_proto_rawDescOnce sync.Once
	file_db_config_entity_voice_lover_award_package_proto_rawDescData = file_db_config_entity_voice_lover_award_package_proto_rawDesc
)

func file_db_config_entity_voice_lover_award_package_proto_rawDescGZIP() []byte {
	file_db_config_entity_voice_lover_award_package_proto_rawDescOnce.Do(func() {
		file_db_config_entity_voice_lover_award_package_proto_rawDescData = protoimpl.X.CompressGZIP(file_db_config_entity_voice_lover_award_package_proto_rawDescData)
	})
	return file_db_config_entity_voice_lover_award_package_proto_rawDescData
}

var file_db_config_entity_voice_lover_award_package_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_db_config_entity_voice_lover_award_package_proto_goTypes = []interface{}{
	(*EntityVoiceLoverAwardPackage)(nil), // 0: db.config.EntityVoiceLoverAwardPackage
}
var file_db_config_entity_voice_lover_award_package_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_db_config_entity_voice_lover_award_package_proto_init() }
func file_db_config_entity_voice_lover_award_package_proto_init() {
	if File_db_config_entity_voice_lover_award_package_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_db_config_entity_voice_lover_award_package_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EntityVoiceLoverAwardPackage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_db_config_entity_voice_lover_award_package_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_db_config_entity_voice_lover_award_package_proto_goTypes,
		DependencyIndexes: file_db_config_entity_voice_lover_award_package_proto_depIdxs,
		MessageInfos:      file_db_config_entity_voice_lover_award_package_proto_msgTypes,
	}.Build()
	File_db_config_entity_voice_lover_award_package_proto = out.File
	file_db_config_entity_voice_lover_award_package_proto_rawDesc = nil
	file_db_config_entity_voice_lover_award_package_proto_goTypes = nil
	file_db_config_entity_voice_lover_award_package_proto_depIdxs = nil
}
