// ==========================================================================
// This is auto-generated by gf cli tool. DO NOT EDIT THIS FILE MANUALLY.
// 重要! 增加数据库字段，只能向后增加，否则不能使用工具生成proto
// ==========================================================================

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.23.0
// 	protoc        v3.15.5
// source: entity_xs_benefit_upgrade_log.proto

package pb

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type EntityXsBenefitUpgradeLog struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	//@inject_tag: orm:"id,primary"
	Id uint32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty" orm:"id,primary"` //
	//@inject_tag: orm:"uid"
	Uid uint32 `protobuf:"varint,2,opt,name=uid,proto3" json:"uid,omitempty" orm:"uid"` // 用户的uid
	//@inject_tag: orm:"last_left_day"
	LastLeftDay uint32 `protobuf:"varint,3,opt,name=last_left_day,json=lastLeftDay,proto3" json:"last_left_day,omitempty" orm:"last_left_day"` // 上一级剩余的天数
	//@inject_tag: orm:"new_card_id"
	NewCardId uint32 `protobuf:"varint,4,opt,name=new_card_id,json=newCardId,proto3" json:"new_card_id,omitempty" orm:"new_card_id"` // 升级后的card_id
	//@inject_tag: orm:"old_car_id"
	OldCarId uint32 `protobuf:"varint,5,opt,name=old_car_id,json=oldCarId,proto3" json:"old_car_id,omitempty" orm:"old_car_id"` //
	//@inject_tag: orm:"card_type"
	CardType string `protobuf:"bytes,6,opt,name=card_type,json=cardType,proto3" json:"card_type,omitempty" orm:"card_type"` //
	//@inject_tag: orm:"extra"
	Extra string `protobuf:"bytes,7,opt,name=extra,proto3" json:"extra,omitempty" orm:"extra"` // 礼物等其他用的字段
	//@inject_tag: orm:"desc"
	Desc string `protobuf:"bytes,8,opt,name=desc,proto3" json:"desc,omitempty" orm:"desc"` // 升级提示语描述
	//@inject_tag: orm:"is_read"
	IsRead uint32 `protobuf:"varint,9,opt,name=is_read,json=isRead,proto3" json:"is_read,omitempty" orm:"is_read"` // 是否已读
	//@inject_tag: orm:"create_time"
	CreateTime uint32 `protobuf:"varint,10,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty" orm:"create_time"` //
	//@inject_tag: orm:"update_time"
	UpdateTime uint32 `protobuf:"varint,11,opt,name=update_time,json=updateTime,proto3" json:"update_time,omitempty" orm:"update_time"` //
}

func (x *EntityXsBenefitUpgradeLog) Reset() {
	*x = EntityXsBenefitUpgradeLog{}
	if protoimpl.UnsafeEnabled {
		mi := &file_entity_xs_benefit_upgrade_log_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EntityXsBenefitUpgradeLog) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EntityXsBenefitUpgradeLog) ProtoMessage() {}

func (x *EntityXsBenefitUpgradeLog) ProtoReflect() protoreflect.Message {
	mi := &file_entity_xs_benefit_upgrade_log_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EntityXsBenefitUpgradeLog.ProtoReflect.Descriptor instead.
func (*EntityXsBenefitUpgradeLog) Descriptor() ([]byte, []int) {
	return file_entity_xs_benefit_upgrade_log_proto_rawDescGZIP(), []int{0}
}

func (x *EntityXsBenefitUpgradeLog) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *EntityXsBenefitUpgradeLog) GetUid() uint32 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *EntityXsBenefitUpgradeLog) GetLastLeftDay() uint32 {
	if x != nil {
		return x.LastLeftDay
	}
	return 0
}

func (x *EntityXsBenefitUpgradeLog) GetNewCardId() uint32 {
	if x != nil {
		return x.NewCardId
	}
	return 0
}

func (x *EntityXsBenefitUpgradeLog) GetOldCarId() uint32 {
	if x != nil {
		return x.OldCarId
	}
	return 0
}

func (x *EntityXsBenefitUpgradeLog) GetCardType() string {
	if x != nil {
		return x.CardType
	}
	return ""
}

func (x *EntityXsBenefitUpgradeLog) GetExtra() string {
	if x != nil {
		return x.Extra
	}
	return ""
}

func (x *EntityXsBenefitUpgradeLog) GetDesc() string {
	if x != nil {
		return x.Desc
	}
	return ""
}

func (x *EntityXsBenefitUpgradeLog) GetIsRead() uint32 {
	if x != nil {
		return x.IsRead
	}
	return 0
}

func (x *EntityXsBenefitUpgradeLog) GetCreateTime() uint32 {
	if x != nil {
		return x.CreateTime
	}
	return 0
}

func (x *EntityXsBenefitUpgradeLog) GetUpdateTime() uint32 {
	if x != nil {
		return x.UpdateTime
	}
	return 0
}

var File_entity_xs_benefit_upgrade_log_proto protoreflect.FileDescriptor

var file_entity_xs_benefit_upgrade_log_proto_rawDesc = []byte{
	0x0a, 0x23, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x5f, 0x78, 0x73, 0x5f, 0x62, 0x65, 0x6e, 0x65,
	0x66, 0x69, 0x74, 0x5f, 0x75, 0x70, 0x67, 0x72, 0x61, 0x64, 0x65, 0x5f, 0x6c, 0x6f, 0x67, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70, 0x62, 0x22, 0xc1, 0x02, 0x0a, 0x19, 0x45, 0x6e,
	0x74, 0x69, 0x74, 0x79, 0x58, 0x73, 0x42, 0x65, 0x6e, 0x65, 0x66, 0x69, 0x74, 0x55, 0x70, 0x67,
	0x72, 0x61, 0x64, 0x65, 0x4c, 0x6f, 0x67, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x02, 0x69, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x03, 0x75, 0x69, 0x64, 0x12, 0x22, 0x0a, 0x0d, 0x6c, 0x61, 0x73,
	0x74, 0x5f, 0x6c, 0x65, 0x66, 0x74, 0x5f, 0x64, 0x61, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x0b, 0x6c, 0x61, 0x73, 0x74, 0x4c, 0x65, 0x66, 0x74, 0x44, 0x61, 0x79, 0x12, 0x1e, 0x0a,
	0x0b, 0x6e, 0x65, 0x77, 0x5f, 0x63, 0x61, 0x72, 0x64, 0x5f, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x09, 0x6e, 0x65, 0x77, 0x43, 0x61, 0x72, 0x64, 0x49, 0x64, 0x12, 0x1c, 0x0a,
	0x0a, 0x6f, 0x6c, 0x64, 0x5f, 0x63, 0x61, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x08, 0x6f, 0x6c, 0x64, 0x43, 0x61, 0x72, 0x49, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x63,
	0x61, 0x72, 0x64, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x63, 0x61, 0x72, 0x64, 0x54, 0x79, 0x70, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x78, 0x74, 0x72,
	0x61, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x78, 0x74, 0x72, 0x61, 0x12, 0x12,
	0x0a, 0x04, 0x64, 0x65, 0x73, 0x63, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x64, 0x65,
	0x73, 0x63, 0x12, 0x17, 0x0a, 0x07, 0x69, 0x73, 0x5f, 0x72, 0x65, 0x61, 0x64, 0x18, 0x09, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x06, 0x69, 0x73, 0x52, 0x65, 0x61, 0x64, 0x12, 0x1f, 0x0a, 0x0b, 0x63,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x1f, 0x0a, 0x0b,
	0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x0b, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x0a, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x42, 0x0b, 0x5a,
	0x09, 0x2e, 0x2e, 0x2f, 0x61, 0x70, 0x70, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_entity_xs_benefit_upgrade_log_proto_rawDescOnce sync.Once
	file_entity_xs_benefit_upgrade_log_proto_rawDescData = file_entity_xs_benefit_upgrade_log_proto_rawDesc
)

func file_entity_xs_benefit_upgrade_log_proto_rawDescGZIP() []byte {
	file_entity_xs_benefit_upgrade_log_proto_rawDescOnce.Do(func() {
		file_entity_xs_benefit_upgrade_log_proto_rawDescData = protoimpl.X.CompressGZIP(file_entity_xs_benefit_upgrade_log_proto_rawDescData)
	})
	return file_entity_xs_benefit_upgrade_log_proto_rawDescData
}

var file_entity_xs_benefit_upgrade_log_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_entity_xs_benefit_upgrade_log_proto_goTypes = []interface{}{
	(*EntityXsBenefitUpgradeLog)(nil), // 0: pb.EntityXsBenefitUpgradeLog
}
var file_entity_xs_benefit_upgrade_log_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_entity_xs_benefit_upgrade_log_proto_init() }
func file_entity_xs_benefit_upgrade_log_proto_init() {
	if File_entity_xs_benefit_upgrade_log_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_entity_xs_benefit_upgrade_log_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EntityXsBenefitUpgradeLog); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_entity_xs_benefit_upgrade_log_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_entity_xs_benefit_upgrade_log_proto_goTypes,
		DependencyIndexes: file_entity_xs_benefit_upgrade_log_proto_depIdxs,
		MessageInfos:      file_entity_xs_benefit_upgrade_log_proto_msgTypes,
	}.Build()
	File_entity_xs_benefit_upgrade_log_proto = out.File
	file_entity_xs_benefit_upgrade_log_proto_rawDesc = nil
	file_entity_xs_benefit_upgrade_log_proto_goTypes = nil
	file_entity_xs_benefit_upgrade_log_proto_depIdxs = nil
}
