// ==========================================================================
// This is auto-generated by gf cli tool. DO NOT EDIT THIS FILE MANUALLY.
// 重要! 增加数据库字段，只能向后增加，否则不能使用工具生成proto
// ==========================================================================

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.15.5
// source: entity_xs_tem_order.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EntityXsTemOrder struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	//@inject_tag: orm:"id,primary"
	Id uint32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty" orm:"id,primary"` //
	//@inject_tag: orm:"uid"
	Uid uint32 `protobuf:"varint,2,opt,name=uid,proto3" json:"uid,omitempty" orm:"uid"` // banban的uid
	//@inject_tag: orm:"tem_uid"
	TemUid string `protobuf:"bytes,3,opt,name=tem_uid,json=temUid,proto3" json:"tem_uid,omitempty" orm:"tem_uid"` // tem的uid
	//@inject_tag: orm:"status"
	Status uint32 `protobuf:"varint,4,opt,name=status,proto3" json:"status,omitempty" orm:"status"` // 充值是否成功 1表示成功
	//@inject_tag: orm:"vip_days"
	VipDays uint32 `protobuf:"varint,5,opt,name=vip_days,json=vipDays,proto3" json:"vip_days,omitempty" orm:"vip_days"` // 充值的多少天
	//@inject_tag: orm:"create_time"
	CreateTime int32 `protobuf:"varint,6,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty" orm:"create_time"` // 创建的时间
}

func (x *EntityXsTemOrder) Reset() {
	*x = EntityXsTemOrder{}
	if protoimpl.UnsafeEnabled {
		mi := &file_entity_xs_tem_order_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EntityXsTemOrder) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EntityXsTemOrder) ProtoMessage() {}

func (x *EntityXsTemOrder) ProtoReflect() protoreflect.Message {
	mi := &file_entity_xs_tem_order_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EntityXsTemOrder.ProtoReflect.Descriptor instead.
func (*EntityXsTemOrder) Descriptor() ([]byte, []int) {
	return file_entity_xs_tem_order_proto_rawDescGZIP(), []int{0}
}

func (x *EntityXsTemOrder) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *EntityXsTemOrder) GetUid() uint32 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *EntityXsTemOrder) GetTemUid() string {
	if x != nil {
		return x.TemUid
	}
	return ""
}

func (x *EntityXsTemOrder) GetStatus() uint32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *EntityXsTemOrder) GetVipDays() uint32 {
	if x != nil {
		return x.VipDays
	}
	return 0
}

func (x *EntityXsTemOrder) GetCreateTime() int32 {
	if x != nil {
		return x.CreateTime
	}
	return 0
}

var File_entity_xs_tem_order_proto protoreflect.FileDescriptor

var file_entity_xs_tem_order_proto_rawDesc = []byte{
	0x0a, 0x19, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x5f, 0x78, 0x73, 0x5f, 0x74, 0x65, 0x6d, 0x5f,
	0x6f, 0x72, 0x64, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70, 0x62, 0x22,
	0xa1, 0x01, 0x0a, 0x10, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x58, 0x73, 0x54, 0x65, 0x6d, 0x4f,
	0x72, 0x64, 0x65, 0x72, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x02, 0x69, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x03, 0x75, 0x69, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x74, 0x65, 0x6d, 0x5f, 0x75, 0x69,
	0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x74, 0x65, 0x6d, 0x55, 0x69, 0x64, 0x12,
	0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0d, 0x52,
	0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x19, 0x0a, 0x08, 0x76, 0x69, 0x70, 0x5f, 0x64,
	0x61, 0x79, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x07, 0x76, 0x69, 0x70, 0x44, 0x61,
	0x79, 0x73, 0x12, 0x1f, 0x0a, 0x0b, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x5f, 0x74, 0x69, 0x6d,
	0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54,
	0x69, 0x6d, 0x65, 0x42, 0x0b, 0x5a, 0x09, 0x2e, 0x2e, 0x2f, 0x61, 0x70, 0x70, 0x2f, 0x70, 0x62,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_entity_xs_tem_order_proto_rawDescOnce sync.Once
	file_entity_xs_tem_order_proto_rawDescData = file_entity_xs_tem_order_proto_rawDesc
)

func file_entity_xs_tem_order_proto_rawDescGZIP() []byte {
	file_entity_xs_tem_order_proto_rawDescOnce.Do(func() {
		file_entity_xs_tem_order_proto_rawDescData = protoimpl.X.CompressGZIP(file_entity_xs_tem_order_proto_rawDescData)
	})
	return file_entity_xs_tem_order_proto_rawDescData
}

var file_entity_xs_tem_order_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_entity_xs_tem_order_proto_goTypes = []interface{}{
	(*EntityXsTemOrder)(nil), // 0: pb.EntityXsTemOrder
}
var file_entity_xs_tem_order_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_entity_xs_tem_order_proto_init() }
func file_entity_xs_tem_order_proto_init() {
	if File_entity_xs_tem_order_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_entity_xs_tem_order_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EntityXsTemOrder); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_entity_xs_tem_order_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_entity_xs_tem_order_proto_goTypes,
		DependencyIndexes: file_entity_xs_tem_order_proto_depIdxs,
		MessageInfos:      file_entity_xs_tem_order_proto_msgTypes,
	}.Build()
	File_entity_xs_tem_order_proto = out.File
	file_entity_xs_tem_order_proto_rawDesc = nil
	file_entity_xs_tem_order_proto_goTypes = nil
	file_entity_xs_tem_order_proto_depIdxs = nil
}
