// ==========================================================================
// This is auto-generated by gf cli tool. DO NOT EDIT THIS FILE MANUALLY.
// 重要! 增加数据库字段，只能向后增加，否则不能使用工具生成proto
// ==========================================================================

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.17.3
// source: entity_xs_chatroom_content.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EntityXsChatroomContent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	//@inject_tag: orm:"id,primary"
	Id uint32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"` // 自增ID
	//@inject_tag: orm:"app_id"
	AppId uint32 `protobuf:"varint,2,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"` // 推荐app_id。0表示所有app通用
	//@inject_tag: orm:"language"
	Language string `protobuf:"bytes,3,opt,name=language,proto3" json:"language,omitempty"` // 语言(cn, tw, en, ar, ms, th, id, vi, ko, jp)
	//@inject_tag: orm:"type"
	Type string `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"` // 推荐类型(welcome:欢迎, hi:打招呼, message:消息, commodity:礼物, wizard:引导)
	//@inject_tag: orm:"ext_id"
	ExtId uint32 `protobuf:"varint,5,opt,name=ext_id,json=extId,proto3" json:"ext_id,omitempty"` // 关联ID(type=commodity时为物品ID, type=message时为关联频道ID)
	//@inject_tag: orm:"ext_type"
	ExtType string `protobuf:"bytes,6,opt,name=ext_type,json=extType,proto3" json:"ext_type,omitempty"` // 关联类型(type=welcome时使用, business商业房, vip个人房)
	//@inject_tag: orm:"content"
	Content string `protobuf:"bytes,7,opt,name=content,proto3" json:"content,omitempty"` // 推荐内容
	//@inject_tag: orm:"weight"
	Weight uint32 `protobuf:"varint,8,opt,name=weight,proto3" json:"weight,omitempty"` // 权重
	//@inject_tag: orm:"isvalid"
	Isvalid uint32 `protobuf:"varint,9,opt,name=isvalid,proto3" json:"isvalid,omitempty"` // 是否有效(0无效, 1有效)
	//@inject_tag: orm:"dateline"
	Dateline uint32 `protobuf:"varint,10,opt,name=dateline,proto3" json:"dateline,omitempty"` // 记录创建时间
	//@inject_tag: orm:"updateline"
	Updateline uint32 `protobuf:"varint,11,opt,name=updateline,proto3" json:"updateline,omitempty"` // 记录更新时间
}

func (x *EntityXsChatroomContent) Reset() {
	*x = EntityXsChatroomContent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_entity_xs_chatroom_content_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EntityXsChatroomContent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EntityXsChatroomContent) ProtoMessage() {}

func (x *EntityXsChatroomContent) ProtoReflect() protoreflect.Message {
	mi := &file_entity_xs_chatroom_content_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EntityXsChatroomContent.ProtoReflect.Descriptor instead.
func (*EntityXsChatroomContent) Descriptor() ([]byte, []int) {
	return file_entity_xs_chatroom_content_proto_rawDescGZIP(), []int{0}
}

func (x *EntityXsChatroomContent) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *EntityXsChatroomContent) GetAppId() uint32 {
	if x != nil {
		return x.AppId
	}
	return 0
}

func (x *EntityXsChatroomContent) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *EntityXsChatroomContent) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *EntityXsChatroomContent) GetExtId() uint32 {
	if x != nil {
		return x.ExtId
	}
	return 0
}

func (x *EntityXsChatroomContent) GetExtType() string {
	if x != nil {
		return x.ExtType
	}
	return ""
}

func (x *EntityXsChatroomContent) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *EntityXsChatroomContent) GetWeight() uint32 {
	if x != nil {
		return x.Weight
	}
	return 0
}

func (x *EntityXsChatroomContent) GetIsvalid() uint32 {
	if x != nil {
		return x.Isvalid
	}
	return 0
}

func (x *EntityXsChatroomContent) GetDateline() uint32 {
	if x != nil {
		return x.Dateline
	}
	return 0
}

func (x *EntityXsChatroomContent) GetUpdateline() uint32 {
	if x != nil {
		return x.Updateline
	}
	return 0
}

var File_entity_xs_chatroom_content_proto protoreflect.FileDescriptor

var file_entity_xs_chatroom_content_proto_rawDesc = []byte{
	0x0a, 0x20, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x5f, 0x78, 0x73, 0x5f, 0x63, 0x68, 0x61, 0x74,
	0x72, 0x6f, 0x6f, 0x6d, 0x5f, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x02, 0x70, 0x62, 0x22, 0xaa, 0x02, 0x0a, 0x17, 0x45, 0x6e, 0x74, 0x69, 0x74,
	0x79, 0x58, 0x73, 0x43, 0x68, 0x61, 0x74, 0x72, 0x6f, 0x6f, 0x6d, 0x43, 0x6f, 0x6e, 0x74, 0x65,
	0x6e, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x02,
	0x69, 0x64, 0x12, 0x15, 0x0a, 0x06, 0x61, 0x70, 0x70, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x05, 0x61, 0x70, 0x70, 0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x6c, 0x61, 0x6e,
	0x67, 0x75, 0x61, 0x67, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6c, 0x61, 0x6e,
	0x67, 0x75, 0x61, 0x67, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x15, 0x0a, 0x06, 0x65, 0x78, 0x74,
	0x5f, 0x69, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x65, 0x78, 0x74, 0x49, 0x64,
	0x12, 0x19, 0x0a, 0x08, 0x65, 0x78, 0x74, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x06, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x65, 0x78, 0x74, 0x54, 0x79, 0x70, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x63,
	0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f,
	0x6e, 0x74, 0x65, 0x6e, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x77, 0x65, 0x69, 0x67, 0x68, 0x74, 0x18,
	0x08, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x77, 0x65, 0x69, 0x67, 0x68, 0x74, 0x12, 0x18, 0x0a,
	0x07, 0x69, 0x73, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x18, 0x09, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x07,
	0x69, 0x73, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x64, 0x61, 0x74, 0x65, 0x6c,
	0x69, 0x6e, 0x65, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x08, 0x64, 0x61, 0x74, 0x65, 0x6c,
	0x69, 0x6e, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x6c, 0x69, 0x6e,
	0x65, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0a, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x6c,
	0x69, 0x6e, 0x65, 0x42, 0x0b, 0x5a, 0x09, 0x2e, 0x2e, 0x2f, 0x61, 0x70, 0x70, 0x2f, 0x70, 0x62,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_entity_xs_chatroom_content_proto_rawDescOnce sync.Once
	file_entity_xs_chatroom_content_proto_rawDescData = file_entity_xs_chatroom_content_proto_rawDesc
)

func file_entity_xs_chatroom_content_proto_rawDescGZIP() []byte {
	file_entity_xs_chatroom_content_proto_rawDescOnce.Do(func() {
		file_entity_xs_chatroom_content_proto_rawDescData = protoimpl.X.CompressGZIP(file_entity_xs_chatroom_content_proto_rawDescData)
	})
	return file_entity_xs_chatroom_content_proto_rawDescData
}

var file_entity_xs_chatroom_content_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_entity_xs_chatroom_content_proto_goTypes = []interface{}{
	(*EntityXsChatroomContent)(nil), // 0: pb.EntityXsChatroomContent
}
var file_entity_xs_chatroom_content_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_entity_xs_chatroom_content_proto_init() }
func file_entity_xs_chatroom_content_proto_init() {
	if File_entity_xs_chatroom_content_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_entity_xs_chatroom_content_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EntityXsChatroomContent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_entity_xs_chatroom_content_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_entity_xs_chatroom_content_proto_goTypes,
		DependencyIndexes: file_entity_xs_chatroom_content_proto_depIdxs,
		MessageInfos:      file_entity_xs_chatroom_content_proto_msgTypes,
	}.Build()
	File_entity_xs_chatroom_content_proto = out.File
	file_entity_xs_chatroom_content_proto_rawDesc = nil
	file_entity_xs_chatroom_content_proto_goTypes = nil
	file_entity_xs_chatroom_content_proto_depIdxs = nil
}
