// ==========================================================================
// This is auto-generated by gf cli tool. DO NOT EDIT THIS FILE MANUALLY.
// 重要! 增加数据库字段，只能向后增加，否则不能使用工具生成proto
// ==========================================================================

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.15.5
// source: entity_xs_user_juben_profile.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EntityXsUserJubenProfile struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	//@inject_tag: orm:"id,primary"
	Id int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty" orm:"id,primary"` //
	//@inject_tag: orm:"uid,unique"
	Uid int32 `protobuf:"varint,2,opt,name=uid,proto3" json:"uid,omitempty" orm:"uid,unique"` //
	//@inject_tag: orm:"isAuth"
	IsAuth int32 `protobuf:"varint,3,opt,name=isAuth,proto3" json:"isAuth,omitempty" orm:"isAuth"` // 是否认证
	//@inject_tag: orm:"level"
	Level int32 `protobuf:"varint,4,opt,name=level,proto3" json:"level,omitempty" orm:"level"` // 等级
	//@inject_tag: orm:"score"
	Score int32 `protobuf:"varint,5,opt,name=score,proto3" json:"score,omitempty" orm:"score"` // 得分
	//@inject_tag: orm:"all"
	All int32 `protobuf:"varint,6,opt,name=all,proto3" json:"all,omitempty" orm:"all"` // 总次数
	//@inject_tag: orm:"again_all"
	AgainAll int32 `protobuf:"varint,7,opt,name=again_all,json=againAll,proto3" json:"again_all,omitempty" orm:"again_all"` // 复刷总次数
	//@inject_tag: orm:"win"
	Win int32 `protobuf:"varint,8,opt,name=win,proto3" json:"win,omitempty" orm:"win"` // 胜利次数
	//@inject_tag: orm:"again_win"
	AgainWin int32 `protobuf:"varint,9,opt,name=again_win,json=againWin,proto3" json:"again_win,omitempty" orm:"again_win"` // 复刷胜利次数
	//@inject_tag: orm:"run"
	Run int32 `protobuf:"varint,10,opt,name=run,proto3" json:"run,omitempty" orm:"run"` // 跳车次数
	//@inject_tag: orm:"outTime"
	OutTime uint32 `protobuf:"varint,11,opt,name=outTime,proto3" json:"outTime,omitempty" orm:"outTime"` // 跳车时间
	//@inject_tag: orm:"dateline"
	Dateline uint32 `protobuf:"varint,12,opt,name=dateline,proto3" json:"dateline,omitempty" orm:"dateline"` //
	//@inject_tag: orm:"updateTime"
	UpdateTime uint32 `protobuf:"varint,13,opt,name=updateTime,proto3" json:"updateTime,omitempty" orm:"updateTime"` //
	//@inject_tag: orm:"iscargod"
	Iscargod int32 `protobuf:"varint,14,opt,name=iscargod,proto3" json:"iscargod,omitempty" orm:"iscargod"` // 是否车神
}

func (x *EntityXsUserJubenProfile) Reset() {
	*x = EntityXsUserJubenProfile{}
	if protoimpl.UnsafeEnabled {
		mi := &file_entity_xs_user_juben_profile_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EntityXsUserJubenProfile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EntityXsUserJubenProfile) ProtoMessage() {}

func (x *EntityXsUserJubenProfile) ProtoReflect() protoreflect.Message {
	mi := &file_entity_xs_user_juben_profile_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EntityXsUserJubenProfile.ProtoReflect.Descriptor instead.
func (*EntityXsUserJubenProfile) Descriptor() ([]byte, []int) {
	return file_entity_xs_user_juben_profile_proto_rawDescGZIP(), []int{0}
}

func (x *EntityXsUserJubenProfile) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *EntityXsUserJubenProfile) GetUid() int32 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *EntityXsUserJubenProfile) GetIsAuth() int32 {
	if x != nil {
		return x.IsAuth
	}
	return 0
}

func (x *EntityXsUserJubenProfile) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *EntityXsUserJubenProfile) GetScore() int32 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *EntityXsUserJubenProfile) GetAll() int32 {
	if x != nil {
		return x.All
	}
	return 0
}

func (x *EntityXsUserJubenProfile) GetAgainAll() int32 {
	if x != nil {
		return x.AgainAll
	}
	return 0
}

func (x *EntityXsUserJubenProfile) GetWin() int32 {
	if x != nil {
		return x.Win
	}
	return 0
}

func (x *EntityXsUserJubenProfile) GetAgainWin() int32 {
	if x != nil {
		return x.AgainWin
	}
	return 0
}

func (x *EntityXsUserJubenProfile) GetRun() int32 {
	if x != nil {
		return x.Run
	}
	return 0
}

func (x *EntityXsUserJubenProfile) GetOutTime() uint32 {
	if x != nil {
		return x.OutTime
	}
	return 0
}

func (x *EntityXsUserJubenProfile) GetDateline() uint32 {
	if x != nil {
		return x.Dateline
	}
	return 0
}

func (x *EntityXsUserJubenProfile) GetUpdateTime() uint32 {
	if x != nil {
		return x.UpdateTime
	}
	return 0
}

func (x *EntityXsUserJubenProfile) GetIscargod() int32 {
	if x != nil {
		return x.Iscargod
	}
	return 0
}

var File_entity_xs_user_juben_profile_proto protoreflect.FileDescriptor

var file_entity_xs_user_juben_profile_proto_rawDesc = []byte{
	0x0a, 0x22, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x5f, 0x78, 0x73, 0x5f, 0x75, 0x73, 0x65, 0x72,
	0x5f, 0x6a, 0x75, 0x62, 0x65, 0x6e, 0x5f, 0x70, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70, 0x62, 0x22, 0xe2, 0x02, 0x0a, 0x18, 0x45, 0x6e, 0x74,
	0x69, 0x74, 0x79, 0x58, 0x73, 0x55, 0x73, 0x65, 0x72, 0x4a, 0x75, 0x62, 0x65, 0x6e, 0x50, 0x72,
	0x6f, 0x66, 0x69, 0x6c, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x02, 0x69, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x03, 0x75, 0x69, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x69, 0x73, 0x41, 0x75, 0x74,
	0x68, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x69, 0x73, 0x41, 0x75, 0x74, 0x68, 0x12,
	0x14, 0x0a, 0x05, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05,
	0x6c, 0x65, 0x76, 0x65, 0x6c, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x63, 0x6f, 0x72, 0x65, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x73, 0x63, 0x6f, 0x72, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x61,
	0x6c, 0x6c, 0x18, 0x06, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x61, 0x6c, 0x6c, 0x12, 0x1b, 0x0a,
	0x09, 0x61, 0x67, 0x61, 0x69, 0x6e, 0x5f, 0x61, 0x6c, 0x6c, 0x18, 0x07, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x08, 0x61, 0x67, 0x61, 0x69, 0x6e, 0x41, 0x6c, 0x6c, 0x12, 0x10, 0x0a, 0x03, 0x77, 0x69,
	0x6e, 0x18, 0x08, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x77, 0x69, 0x6e, 0x12, 0x1b, 0x0a, 0x09,
	0x61, 0x67, 0x61, 0x69, 0x6e, 0x5f, 0x77, 0x69, 0x6e, 0x18, 0x09, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x08, 0x61, 0x67, 0x61, 0x69, 0x6e, 0x57, 0x69, 0x6e, 0x12, 0x10, 0x0a, 0x03, 0x72, 0x75, 0x6e,
	0x18, 0x0a, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x72, 0x75, 0x6e, 0x12, 0x18, 0x0a, 0x07, 0x6f,
	0x75, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x07, 0x6f, 0x75,
	0x74, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x64, 0x61, 0x74, 0x65, 0x6c, 0x69, 0x6e,
	0x65, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x08, 0x64, 0x61, 0x74, 0x65, 0x6c, 0x69, 0x6e,
	0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x18,
	0x0d, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0a, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d,
	0x65, 0x12, 0x1a, 0x0a, 0x08, 0x69, 0x73, 0x63, 0x61, 0x72, 0x67, 0x6f, 0x64, 0x18, 0x0e, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x08, 0x69, 0x73, 0x63, 0x61, 0x72, 0x67, 0x6f, 0x64, 0x42, 0x0b, 0x5a,
	0x09, 0x2e, 0x2e, 0x2f, 0x61, 0x70, 0x70, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_entity_xs_user_juben_profile_proto_rawDescOnce sync.Once
	file_entity_xs_user_juben_profile_proto_rawDescData = file_entity_xs_user_juben_profile_proto_rawDesc
)

func file_entity_xs_user_juben_profile_proto_rawDescGZIP() []byte {
	file_entity_xs_user_juben_profile_proto_rawDescOnce.Do(func() {
		file_entity_xs_user_juben_profile_proto_rawDescData = protoimpl.X.CompressGZIP(file_entity_xs_user_juben_profile_proto_rawDescData)
	})
	return file_entity_xs_user_juben_profile_proto_rawDescData
}

var file_entity_xs_user_juben_profile_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_entity_xs_user_juben_profile_proto_goTypes = []interface{}{
	(*EntityXsUserJubenProfile)(nil), // 0: pb.EntityXsUserJubenProfile
}
var file_entity_xs_user_juben_profile_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_entity_xs_user_juben_profile_proto_init() }
func file_entity_xs_user_juben_profile_proto_init() {
	if File_entity_xs_user_juben_profile_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_entity_xs_user_juben_profile_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EntityXsUserJubenProfile); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_entity_xs_user_juben_profile_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_entity_xs_user_juben_profile_proto_goTypes,
		DependencyIndexes: file_entity_xs_user_juben_profile_proto_depIdxs,
		MessageInfos:      file_entity_xs_user_juben_profile_proto_msgTypes,
	}.Build()
	File_entity_xs_user_juben_profile_proto = out.File
	file_entity_xs_user_juben_profile_proto_rawDesc = nil
	file_entity_xs_user_juben_profile_proto_goTypes = nil
	file_entity_xs_user_juben_profile_proto_depIdxs = nil
}
