// ==========================================================================
// This is auto-generated by gf cli tool. DO NOT EDIT THIS FILE MANUALLY.
// 重要! 增加数据库字段，只能向后增加，否则不能使用工具生成proto
// ==========================================================================

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.15.5
// source: entity_xs_room_relation.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EntityXsRoomRelation struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	//@inject_tag: orm:"id,primary"
	Id uint32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty" orm:"id,primary"` // 自增id
	//@inject_tag: orm:"master_rid"
	MasterRid uint32 `protobuf:"varint,2,opt,name=master_rid,json=masterRid,proto3" json:"master_rid,omitempty" orm:"master_rid"` // 父房间
	//@inject_tag: orm:"rid"
	Rid uint32 `protobuf:"varint,3,opt,name=rid,proto3" json:"rid,omitempty" orm:"rid"` // 子房间
	//@inject_tag: orm:"app_id"
	AppId uint32 `protobuf:"varint,4,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty" orm:"app_id"` // app_id
	//@inject_tag: orm:"start_time"
	StartTime uint64 `protobuf:"varint,5,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty" orm:"start_time"` // 开始时间, 如果为0说明没有时间限制
	//@inject_tag: orm:"end_time"
	EndTime uint64 `protobuf:"varint,6,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty" orm:"end_time"` // 结束时间，如果为0说明没有时间限制
}

func (x *EntityXsRoomRelation) Reset() {
	*x = EntityXsRoomRelation{}
	if protoimpl.UnsafeEnabled {
		mi := &file_entity_xs_room_relation_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EntityXsRoomRelation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EntityXsRoomRelation) ProtoMessage() {}

func (x *EntityXsRoomRelation) ProtoReflect() protoreflect.Message {
	mi := &file_entity_xs_room_relation_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EntityXsRoomRelation.ProtoReflect.Descriptor instead.
func (*EntityXsRoomRelation) Descriptor() ([]byte, []int) {
	return file_entity_xs_room_relation_proto_rawDescGZIP(), []int{0}
}

func (x *EntityXsRoomRelation) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *EntityXsRoomRelation) GetMasterRid() uint32 {
	if x != nil {
		return x.MasterRid
	}
	return 0
}

func (x *EntityXsRoomRelation) GetRid() uint32 {
	if x != nil {
		return x.Rid
	}
	return 0
}

func (x *EntityXsRoomRelation) GetAppId() uint32 {
	if x != nil {
		return x.AppId
	}
	return 0
}

func (x *EntityXsRoomRelation) GetStartTime() uint64 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

func (x *EntityXsRoomRelation) GetEndTime() uint64 {
	if x != nil {
		return x.EndTime
	}
	return 0
}

var File_entity_xs_room_relation_proto protoreflect.FileDescriptor

var file_entity_xs_room_relation_proto_rawDesc = []byte{
	0x0a, 0x1d, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x5f, 0x78, 0x73, 0x5f, 0x72, 0x6f, 0x6f, 0x6d,
	0x5f, 0x72, 0x65, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x02, 0x70, 0x62, 0x22, 0xa8, 0x01, 0x0a, 0x14, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x58, 0x73,
	0x52, 0x6f, 0x6f, 0x6d, 0x52, 0x65, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x0e, 0x0a, 0x02,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1d, 0x0a, 0x0a,
	0x6d, 0x61, 0x73, 0x74, 0x65, 0x72, 0x5f, 0x72, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x09, 0x6d, 0x61, 0x73, 0x74, 0x65, 0x72, 0x52, 0x69, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x72,
	0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x03, 0x72, 0x69, 0x64, 0x12, 0x15, 0x0a,
	0x06, 0x61, 0x70, 0x70, 0x5f, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x61,
	0x70, 0x70, 0x49, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x74, 0x61, 0x72, 0x74, 0x5f, 0x74, 0x69,
	0x6d, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x04, 0x52, 0x09, 0x73, 0x74, 0x61, 0x72, 0x74, 0x54,
	0x69, 0x6d, 0x65, 0x12, 0x19, 0x0a, 0x08, 0x65, 0x6e, 0x64, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18,
	0x06, 0x20, 0x01, 0x28, 0x04, 0x52, 0x07, 0x65, 0x6e, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x42, 0x0b,
	0x5a, 0x09, 0x2e, 0x2e, 0x2f, 0x61, 0x70, 0x70, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_entity_xs_room_relation_proto_rawDescOnce sync.Once
	file_entity_xs_room_relation_proto_rawDescData = file_entity_xs_room_relation_proto_rawDesc
)

func file_entity_xs_room_relation_proto_rawDescGZIP() []byte {
	file_entity_xs_room_relation_proto_rawDescOnce.Do(func() {
		file_entity_xs_room_relation_proto_rawDescData = protoimpl.X.CompressGZIP(file_entity_xs_room_relation_proto_rawDescData)
	})
	return file_entity_xs_room_relation_proto_rawDescData
}

var file_entity_xs_room_relation_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_entity_xs_room_relation_proto_goTypes = []interface{}{
	(*EntityXsRoomRelation)(nil), // 0: pb.EntityXsRoomRelation
}
var file_entity_xs_room_relation_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_entity_xs_room_relation_proto_init() }
func file_entity_xs_room_relation_proto_init() {
	if File_entity_xs_room_relation_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_entity_xs_room_relation_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EntityXsRoomRelation); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_entity_xs_room_relation_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_entity_xs_room_relation_proto_goTypes,
		DependencyIndexes: file_entity_xs_room_relation_proto_depIdxs,
		MessageInfos:      file_entity_xs_room_relation_proto_msgTypes,
	}.Build()
	File_entity_xs_room_relation_proto = out.File
	file_entity_xs_room_relation_proto_rawDesc = nil
	file_entity_xs_room_relation_proto_goTypes = nil
	file_entity_xs_room_relation_proto_depIdxs = nil
}
