// ==========================================================================
// This is auto-generated by gf cli tool. DO NOT EDIT THIS FILE MANUALLY.
// 重要! 增加数据库字段，只能向后增加，否则不能使用工具生成proto
// ==========================================================================

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.15.5
// source: entity_xs_ka_giftbag_send.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EntityXsKaGiftbagSend struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	//@inject_tag: orm:"id,primary"
	Id uint32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty" orm:"id,primary"` // 记录ID
	//@inject_tag: orm:"bag_id"
	BagId uint32 `protobuf:"varint,2,opt,name=bag_id,json=bagId,proto3" json:"bag_id,omitempty" orm:"bag_id"` // 礼包id
	//@inject_tag: orm:"uid"
	Uid uint32 `protobuf:"varint,3,opt,name=uid,proto3" json:"uid,omitempty" orm:"uid"` // 用户uid
	//@inject_tag: orm:"mark"
	Mark string `protobuf:"bytes,4,opt,name=mark,proto3" json:"mark,omitempty" orm:"mark"` // 备注
	//@inject_tag: orm:"is_send"
	IsSend int32 `protobuf:"varint,5,opt,name=is_send,json=isSend,proto3" json:"is_send,omitempty" orm:"is_send"` // 是否已发放:0 否;1 是
	//@inject_tag: orm:"begin_time"
	BeginTime uint32 `protobuf:"varint,6,opt,name=begin_time,json=beginTime,proto3" json:"begin_time,omitempty" orm:"begin_time"` // 开始时间
	//@inject_tag: orm:"expire_time"
	ExpireTime uint32 `protobuf:"varint,7,opt,name=expire_time,json=expireTime,proto3" json:"expire_time,omitempty" orm:"expire_time"` // 结束时间
	//@inject_tag: orm:"admin"
	Admin uint32 `protobuf:"varint,8,opt,name=admin,proto3" json:"admin,omitempty" orm:"admin"` // 创建人
	//@inject_tag: orm:"dateline"
	Dateline uint32 `protobuf:"varint,9,opt,name=dateline,proto3" json:"dateline,omitempty" orm:"dateline"` // 创建时间
	//@inject_tag: orm:"state"
	State uint32 `protobuf:"varint,10,opt,name=state,proto3" json:"state,omitempty" orm:"state"` // 状态 0 待审核 1正常 2废弃
}

func (x *EntityXsKaGiftbagSend) Reset() {
	*x = EntityXsKaGiftbagSend{}
	if protoimpl.UnsafeEnabled {
		mi := &file_entity_xs_ka_giftbag_send_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EntityXsKaGiftbagSend) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EntityXsKaGiftbagSend) ProtoMessage() {}

func (x *EntityXsKaGiftbagSend) ProtoReflect() protoreflect.Message {
	mi := &file_entity_xs_ka_giftbag_send_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EntityXsKaGiftbagSend.ProtoReflect.Descriptor instead.
func (*EntityXsKaGiftbagSend) Descriptor() ([]byte, []int) {
	return file_entity_xs_ka_giftbag_send_proto_rawDescGZIP(), []int{0}
}

func (x *EntityXsKaGiftbagSend) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *EntityXsKaGiftbagSend) GetBagId() uint32 {
	if x != nil {
		return x.BagId
	}
	return 0
}

func (x *EntityXsKaGiftbagSend) GetUid() uint32 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *EntityXsKaGiftbagSend) GetMark() string {
	if x != nil {
		return x.Mark
	}
	return ""
}

func (x *EntityXsKaGiftbagSend) GetIsSend() int32 {
	if x != nil {
		return x.IsSend
	}
	return 0
}

func (x *EntityXsKaGiftbagSend) GetBeginTime() uint32 {
	if x != nil {
		return x.BeginTime
	}
	return 0
}

func (x *EntityXsKaGiftbagSend) GetExpireTime() uint32 {
	if x != nil {
		return x.ExpireTime
	}
	return 0
}

func (x *EntityXsKaGiftbagSend) GetAdmin() uint32 {
	if x != nil {
		return x.Admin
	}
	return 0
}

func (x *EntityXsKaGiftbagSend) GetDateline() uint32 {
	if x != nil {
		return x.Dateline
	}
	return 0
}

func (x *EntityXsKaGiftbagSend) GetState() uint32 {
	if x != nil {
		return x.State
	}
	return 0
}

var File_entity_xs_ka_giftbag_send_proto protoreflect.FileDescriptor

var file_entity_xs_ka_giftbag_send_proto_rawDesc = []byte{
	0x0a, 0x1f, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x5f, 0x78, 0x73, 0x5f, 0x6b, 0x61, 0x5f, 0x67,
	0x69, 0x66, 0x74, 0x62, 0x61, 0x67, 0x5f, 0x73, 0x65, 0x6e, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x02, 0x70, 0x62, 0x22, 0x85, 0x02, 0x0a, 0x15, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x79,
	0x58, 0x73, 0x4b, 0x61, 0x47, 0x69, 0x66, 0x74, 0x62, 0x61, 0x67, 0x53, 0x65, 0x6e, 0x64, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x02, 0x69, 0x64, 0x12,
	0x15, 0x0a, 0x06, 0x62, 0x61, 0x67, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52,
	0x05, 0x62, 0x61, 0x67, 0x49, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x03, 0x75, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6d, 0x61, 0x72, 0x6b,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6d, 0x61, 0x72, 0x6b, 0x12, 0x17, 0x0a, 0x07,
	0x69, 0x73, 0x5f, 0x73, 0x65, 0x6e, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x69,
	0x73, 0x53, 0x65, 0x6e, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x62, 0x65, 0x67, 0x69, 0x6e, 0x5f, 0x74,
	0x69, 0x6d, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x09, 0x62, 0x65, 0x67, 0x69, 0x6e,
	0x54, 0x69, 0x6d, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x65, 0x78, 0x70, 0x69, 0x72, 0x65, 0x5f, 0x74,
	0x69, 0x6d, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0a, 0x65, 0x78, 0x70, 0x69, 0x72,
	0x65, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x18, 0x08,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x12, 0x1a, 0x0a, 0x08, 0x64,
	0x61, 0x74, 0x65, 0x6c, 0x69, 0x6e, 0x65, 0x18, 0x09, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x08, 0x64,
	0x61, 0x74, 0x65, 0x6c, 0x69, 0x6e, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65,
	0x18, 0x0a, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x42, 0x0b, 0x5a,
	0x09, 0x2e, 0x2e, 0x2f, 0x61, 0x70, 0x70, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_entity_xs_ka_giftbag_send_proto_rawDescOnce sync.Once
	file_entity_xs_ka_giftbag_send_proto_rawDescData = file_entity_xs_ka_giftbag_send_proto_rawDesc
)

func file_entity_xs_ka_giftbag_send_proto_rawDescGZIP() []byte {
	file_entity_xs_ka_giftbag_send_proto_rawDescOnce.Do(func() {
		file_entity_xs_ka_giftbag_send_proto_rawDescData = protoimpl.X.CompressGZIP(file_entity_xs_ka_giftbag_send_proto_rawDescData)
	})
	return file_entity_xs_ka_giftbag_send_proto_rawDescData
}

var file_entity_xs_ka_giftbag_send_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_entity_xs_ka_giftbag_send_proto_goTypes = []interface{}{
	(*EntityXsKaGiftbagSend)(nil), // 0: pb.EntityXsKaGiftbagSend
}
var file_entity_xs_ka_giftbag_send_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_entity_xs_ka_giftbag_send_proto_init() }
func file_entity_xs_ka_giftbag_send_proto_init() {
	if File_entity_xs_ka_giftbag_send_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_entity_xs_ka_giftbag_send_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EntityXsKaGiftbagSend); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_entity_xs_ka_giftbag_send_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_entity_xs_ka_giftbag_send_proto_goTypes,
		DependencyIndexes: file_entity_xs_ka_giftbag_send_proto_depIdxs,
		MessageInfos:      file_entity_xs_ka_giftbag_send_proto_msgTypes,
	}.Build()
	File_entity_xs_ka_giftbag_send_proto = out.File
	file_entity_xs_ka_giftbag_send_proto_rawDesc = nil
	file_entity_xs_ka_giftbag_send_proto_goTypes = nil
	file_entity_xs_ka_giftbag_send_proto_depIdxs = nil
}
