// ==========================================================================
// This is auto-generated by gf cli tool. DO NOT EDIT THIS FILE MANUALLY.
// 重要! 增加数据库字段，只能向后增加，否则不能使用工具生成proto
// ==========================================================================

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.9.1
// source: entity_xs_fleet.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EntityXsFleet struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	//@inject_tag: orm:"gid,primary"
	Gid int32 `protobuf:"varint,1,opt,name=gid,proto3" json:"gid,omitempty" orm:"gid,primary"` //
	//@inject_tag: orm:"uid"
	Uid int32 `protobuf:"varint,2,opt,name=uid,proto3" json:"uid,omitempty" orm:"uid"` // 车队创始人
	//@inject_tag: orm:"prefix"
	Prefix string `protobuf:"bytes,3,opt,name=prefix,proto3" json:"prefix,omitempty" orm:"prefix"` // 车队名字
	//@inject_tag: orm:"name"
	Name string `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty" orm:"name"` // 车队名字
	//@inject_tag: orm:"icon"
	Icon string `protobuf:"bytes,5,opt,name=icon,proto3" json:"icon,omitempty" orm:"icon"` // 车队封面
	//@inject_tag: orm:"tag"
	Tag string `protobuf:"bytes,6,opt,name=tag,proto3" json:"tag,omitempty" orm:"tag"` // 车队标签
	//@inject_tag: orm:"description"
	Description string `protobuf:"bytes,7,opt,name=description,proto3" json:"description,omitempty" orm:"description"` // 车队介绍
	//@inject_tag: orm:"allow_manage"
	AllowManage int32 `protobuf:"varint,8,opt,name=allow_manage,json=allowManage,proto3" json:"allow_manage,omitempty" orm:"allow_manage"` // 允许车队成员管理
	//@inject_tag: orm:"allow_invite"
	AllowInvite int32 `protobuf:"varint,9,opt,name=allow_invite,json=allowInvite,proto3" json:"allow_invite,omitempty" orm:"allow_invite"` // 允许通过邀请加入
	//@inject_tag: orm:"allow_search"
	AllowSearch int32 `protobuf:"varint,10,opt,name=allow_search,json=allowSearch,proto3" json:"allow_search,omitempty" orm:"allow_search"` // 允许通过搜索加入
	//@inject_tag: orm:"quiet"
	Quiet int32 `protobuf:"varint,11,opt,name=quiet,proto3" json:"quiet,omitempty" orm:"quiet"` // 是否开启禁言
	//@inject_tag: orm:"dateline"
	Dateline int32 `protobuf:"varint,12,opt,name=dateline,proto3" json:"dateline,omitempty" orm:"dateline"` // 创建时间
	//@inject_tag: orm:"total"
	Total int32 `protobuf:"varint,13,opt,name=total,proto3" json:"total,omitempty" orm:"total"` // 已加入人数
	//@inject_tag: orm:"total_wait"
	TotalWait int32 `protobuf:"varint,14,opt,name=total_wait,json=totalWait,proto3" json:"total_wait,omitempty" orm:"total_wait"` // 等待审核人数
	//@inject_tag: orm:"version"
	Version int32 `protobuf:"varint,15,opt,name=version,proto3" json:"version,omitempty" orm:"version"` // 版本
	//@inject_tag: orm:"deleted"
	Deleted int32 `protobuf:"varint,16,opt,name=deleted,proto3" json:"deleted,omitempty" orm:"deleted"` // 是否已经解散， 0 正常, 1 创始人解散，2 系统解散
	//@inject_tag: orm:"money"
	Money int32 `protobuf:"varint,17,opt,name=money,proto3" json:"money,omitempty" orm:"money"` // 车队红包
	//@inject_tag: orm:"money_week"
	MoneyWeek int32 `protobuf:"varint,18,opt,name=money_week,json=moneyWeek,proto3" json:"money_week,omitempty" orm:"money_week"` // 车队本周红包
	//@inject_tag: orm:"online_enough"
	OnlineEnough int32 `protobuf:"varint,19,opt,name=online_enough,json=onlineEnough,proto3" json:"online_enough,omitempty" orm:"online_enough"` // 满足当日三人在线的时间
	//@inject_tag: orm:"tmp_icon"
	TmpIcon string `protobuf:"bytes,20,opt,name=tmp_icon,json=tmpIcon,proto3" json:"tmp_icon,omitempty" orm:"tmp_icon"` // 待审封面
	//@inject_tag: orm:"tmp_name"
	TmpName string `protobuf:"bytes,21,opt,name=tmp_name,json=tmpName,proto3" json:"tmp_name,omitempty" orm:"tmp_name"` // 最近通过的名称
	//@inject_tag: orm:"tmp_description"
	TmpDescription string `protobuf:"bytes,22,opt,name=tmp_description,json=tmpDescription,proto3" json:"tmp_description,omitempty" orm:"tmp_description"` // 最近通过的车队介绍
}

func (x *EntityXsFleet) Reset() {
	*x = EntityXsFleet{}
	if protoimpl.UnsafeEnabled {
		mi := &file_entity_xs_fleet_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EntityXsFleet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EntityXsFleet) ProtoMessage() {}

func (x *EntityXsFleet) ProtoReflect() protoreflect.Message {
	mi := &file_entity_xs_fleet_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EntityXsFleet.ProtoReflect.Descriptor instead.
func (*EntityXsFleet) Descriptor() ([]byte, []int) {
	return file_entity_xs_fleet_proto_rawDescGZIP(), []int{0}
}

func (x *EntityXsFleet) GetGid() int32 {
	if x != nil {
		return x.Gid
	}
	return 0
}

func (x *EntityXsFleet) GetUid() int32 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *EntityXsFleet) GetPrefix() string {
	if x != nil {
		return x.Prefix
	}
	return ""
}

func (x *EntityXsFleet) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *EntityXsFleet) GetIcon() string {
	if x != nil {
		return x.Icon
	}
	return ""
}

func (x *EntityXsFleet) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

func (x *EntityXsFleet) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *EntityXsFleet) GetAllowManage() int32 {
	if x != nil {
		return x.AllowManage
	}
	return 0
}

func (x *EntityXsFleet) GetAllowInvite() int32 {
	if x != nil {
		return x.AllowInvite
	}
	return 0
}

func (x *EntityXsFleet) GetAllowSearch() int32 {
	if x != nil {
		return x.AllowSearch
	}
	return 0
}

func (x *EntityXsFleet) GetQuiet() int32 {
	if x != nil {
		return x.Quiet
	}
	return 0
}

func (x *EntityXsFleet) GetDateline() int32 {
	if x != nil {
		return x.Dateline
	}
	return 0
}

func (x *EntityXsFleet) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *EntityXsFleet) GetTotalWait() int32 {
	if x != nil {
		return x.TotalWait
	}
	return 0
}

func (x *EntityXsFleet) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *EntityXsFleet) GetDeleted() int32 {
	if x != nil {
		return x.Deleted
	}
	return 0
}

func (x *EntityXsFleet) GetMoney() int32 {
	if x != nil {
		return x.Money
	}
	return 0
}

func (x *EntityXsFleet) GetMoneyWeek() int32 {
	if x != nil {
		return x.MoneyWeek
	}
	return 0
}

func (x *EntityXsFleet) GetOnlineEnough() int32 {
	if x != nil {
		return x.OnlineEnough
	}
	return 0
}

func (x *EntityXsFleet) GetTmpIcon() string {
	if x != nil {
		return x.TmpIcon
	}
	return ""
}

func (x *EntityXsFleet) GetTmpName() string {
	if x != nil {
		return x.TmpName
	}
	return ""
}

func (x *EntityXsFleet) GetTmpDescription() string {
	if x != nil {
		return x.TmpDescription
	}
	return ""
}

var File_entity_xs_fleet_proto protoreflect.FileDescriptor

var file_entity_xs_fleet_proto_rawDesc = []byte{
	0x0a, 0x15, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x5f, 0x78, 0x73, 0x5f, 0x66, 0x6c, 0x65, 0x65,
	0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70, 0x62, 0x22, 0xe4, 0x04, 0x0a, 0x0d,
	0x45, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x58, 0x73, 0x46, 0x6c, 0x65, 0x65, 0x74, 0x12, 0x10, 0x0a,
	0x03, 0x67, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x67, 0x69, 0x64, 0x12,
	0x10, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x75, 0x69,
	0x64, 0x12, 0x16, 0x0a, 0x06, 0x70, 0x72, 0x65, 0x66, 0x69, 0x78, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x70, 0x72, 0x65, 0x66, 0x69, 0x78, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a,
	0x04, 0x69, 0x63, 0x6f, 0x6e, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x69, 0x63, 0x6f,
	0x6e, 0x12, 0x10, 0x0a, 0x03, 0x74, 0x61, 0x67, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03,
	0x74, 0x61, 0x67, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69,
	0x6f, 0x6e, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69,
	0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x21, 0x0a, 0x0c, 0x61, 0x6c, 0x6c, 0x6f, 0x77, 0x5f, 0x6d,
	0x61, 0x6e, 0x61, 0x67, 0x65, 0x18, 0x08, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0b, 0x61, 0x6c, 0x6c,
	0x6f, 0x77, 0x4d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x12, 0x21, 0x0a, 0x0c, 0x61, 0x6c, 0x6c, 0x6f,
	0x77, 0x5f, 0x69, 0x6e, 0x76, 0x69, 0x74, 0x65, 0x18, 0x09, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0b,
	0x61, 0x6c, 0x6c, 0x6f, 0x77, 0x49, 0x6e, 0x76, 0x69, 0x74, 0x65, 0x12, 0x21, 0x0a, 0x0c, 0x61,
	0x6c, 0x6c, 0x6f, 0x77, 0x5f, 0x73, 0x65, 0x61, 0x72, 0x63, 0x68, 0x18, 0x0a, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x0b, 0x61, 0x6c, 0x6c, 0x6f, 0x77, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x12, 0x14,
	0x0a, 0x05, 0x71, 0x75, 0x69, 0x65, 0x74, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x71,
	0x75, 0x69, 0x65, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x64, 0x61, 0x74, 0x65, 0x6c, 0x69, 0x6e, 0x65,
	0x18, 0x0c, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x64, 0x61, 0x74, 0x65, 0x6c, 0x69, 0x6e, 0x65,
	0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x18, 0x0d, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x12, 0x1d, 0x0a, 0x0a, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x5f,
	0x77, 0x61, 0x69, 0x74, 0x18, 0x0e, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x74, 0x6f, 0x74, 0x61,
	0x6c, 0x57, 0x61, 0x69, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e,
	0x18, 0x0f, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12,
	0x18, 0x0a, 0x07, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x64, 0x18, 0x10, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x07, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x6d, 0x6f, 0x6e,
	0x65, 0x79, 0x18, 0x11, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x6d, 0x6f, 0x6e, 0x65, 0x79, 0x12,
	0x1d, 0x0a, 0x0a, 0x6d, 0x6f, 0x6e, 0x65, 0x79, 0x5f, 0x77, 0x65, 0x65, 0x6b, 0x18, 0x12, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x09, 0x6d, 0x6f, 0x6e, 0x65, 0x79, 0x57, 0x65, 0x65, 0x6b, 0x12, 0x23,
	0x0a, 0x0d, 0x6f, 0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x5f, 0x65, 0x6e, 0x6f, 0x75, 0x67, 0x68, 0x18,
	0x13, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0c, 0x6f, 0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x45, 0x6e, 0x6f,
	0x75, 0x67, 0x68, 0x12, 0x19, 0x0a, 0x08, 0x74, 0x6d, 0x70, 0x5f, 0x69, 0x63, 0x6f, 0x6e, 0x18,
	0x14, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x74, 0x6d, 0x70, 0x49, 0x63, 0x6f, 0x6e, 0x12, 0x19,
	0x0a, 0x08, 0x74, 0x6d, 0x70, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x15, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x74, 0x6d, 0x70, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x27, 0x0a, 0x0f, 0x74, 0x6d, 0x70,
	0x5f, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x16, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0e, 0x74, 0x6d, 0x70, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69,
	0x6f, 0x6e, 0x42, 0x0b, 0x5a, 0x09, 0x2e, 0x2e, 0x2f, 0x61, 0x70, 0x70, 0x2f, 0x70, 0x62, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_entity_xs_fleet_proto_rawDescOnce sync.Once
	file_entity_xs_fleet_proto_rawDescData = file_entity_xs_fleet_proto_rawDesc
)

func file_entity_xs_fleet_proto_rawDescGZIP() []byte {
	file_entity_xs_fleet_proto_rawDescOnce.Do(func() {
		file_entity_xs_fleet_proto_rawDescData = protoimpl.X.CompressGZIP(file_entity_xs_fleet_proto_rawDescData)
	})
	return file_entity_xs_fleet_proto_rawDescData
}

var file_entity_xs_fleet_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_entity_xs_fleet_proto_goTypes = []interface{}{
	(*EntityXsFleet)(nil), // 0: pb.EntityXsFleet
}
var file_entity_xs_fleet_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_entity_xs_fleet_proto_init() }
func file_entity_xs_fleet_proto_init() {
	if File_entity_xs_fleet_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_entity_xs_fleet_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EntityXsFleet); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_entity_xs_fleet_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_entity_xs_fleet_proto_goTypes,
		DependencyIndexes: file_entity_xs_fleet_proto_depIdxs,
		MessageInfos:      file_entity_xs_fleet_proto_msgTypes,
	}.Build()
	File_entity_xs_fleet_proto = out.File
	file_entity_xs_fleet_proto_rawDesc = nil
	file_entity_xs_fleet_proto_goTypes = nil
	file_entity_xs_fleet_proto_depIdxs = nil
}
