// ==========================================================================
// This is auto-generated by gf cli tool. DO NOT EDIT THIS FILE MANUALLY.
// 重要! 增加数据库字段，只能向后增加，否则不能使用工具生成proto
// ==========================================================================

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.17.3
// source: entity_xs_chatroom_charm_hour.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EntityXsChatroomCharmHour struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	//@inject_tag: orm:"id,primary"
	Id uint32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty" orm:"id,primary"` //
	//@inject_tag: orm:"day_hour"
	DayHour uint32 `protobuf:"varint,2,opt,name=day_hour,json=dayHour,proto3" json:"day_hour,omitempty" orm:"day_hour"` //
	//@inject_tag: orm:"type"
	Type string `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty" orm:"type"` // 频道类别
	//@inject_tag: orm:"rid"
	Rid uint32 `protobuf:"varint,4,opt,name=rid,proto3" json:"rid,omitempty" orm:"rid"` //
	//@inject_tag: orm:"room_creator"
	RoomCreator uint32 `protobuf:"varint,5,opt,name=room_creator,json=roomCreator,proto3" json:"room_creator,omitempty" orm:"room_creator"` // 房主uid
	//@inject_tag: orm:"room_name"
	RoomName string `protobuf:"bytes,6,opt,name=room_name,json=roomName,proto3" json:"room_name,omitempty" orm:"room_name"` //
	//@inject_tag: orm:"charm"
	Charm uint32 `protobuf:"varint,7,opt,name=charm,proto3" json:"charm,omitempty" orm:"charm"` // 当前小时实时魅力值
	//@inject_tag: orm:"prev_charm"
	PrevCharm uint32 `protobuf:"varint,8,opt,name=prev_charm,json=prevCharm,proto3" json:"prev_charm,omitempty" orm:"prev_charm"` // 当前小时上次实时魅力值
	//@inject_tag: orm:"real_rank"
	RealRank uint32 `protobuf:"varint,9,opt,name=real_rank,json=realRank,proto3" json:"real_rank,omitempty" orm:"real_rank"` // 当前小时实时排名
	//@inject_tag: orm:"prev_hour_charm"
	PrevHourCharm uint32 `protobuf:"varint,10,opt,name=prev_hour_charm,json=prevHourCharm,proto3" json:"prev_hour_charm,omitempty" orm:"prev_hour_charm"` // 上个小时的魅力值
	//@inject_tag: orm:"prev_real_rank"
	PrevRealRank uint32 `protobuf:"varint,11,opt,name=prev_real_rank,json=prevRealRank,proto3" json:"prev_real_rank,omitempty" orm:"prev_real_rank"` // 当前小时上次实时排名
	//@inject_tag: orm:"prev_hour_rank"
	PrevHourRank uint32 `protobuf:"varint,12,opt,name=prev_hour_rank,json=prevHourRank,proto3" json:"prev_hour_rank,omitempty" orm:"prev_hour_rank"` // 上个小时的排名
	//@inject_tag: orm:"update_time"
	UpdateTime uint32 `protobuf:"varint,13,opt,name=update_time,json=updateTime,proto3" json:"update_time,omitempty" orm:"update_time"` //
	//@inject_tag: orm:"create_time"
	CreateTime uint32 `protobuf:"varint,14,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty" orm:"create_time"` //
	//@inject_tag: orm:"is_sync"
	IsSync uint32 `protobuf:"varint,15,opt,name=is_sync,json=isSync,proto3" json:"is_sync,omitempty" orm:"is_sync"` // 本次魅力值变更是否已同步
	//@inject_tag: orm:"app_id"
	AppId uint32 `protobuf:"varint,16,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty" orm:"app_id"` //
}

func (x *EntityXsChatroomCharmHour) Reset() {
	*x = EntityXsChatroomCharmHour{}
	if protoimpl.UnsafeEnabled {
		mi := &file_entity_xs_chatroom_charm_hour_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EntityXsChatroomCharmHour) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EntityXsChatroomCharmHour) ProtoMessage() {}

func (x *EntityXsChatroomCharmHour) ProtoReflect() protoreflect.Message {
	mi := &file_entity_xs_chatroom_charm_hour_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EntityXsChatroomCharmHour.ProtoReflect.Descriptor instead.
func (*EntityXsChatroomCharmHour) Descriptor() ([]byte, []int) {
	return file_entity_xs_chatroom_charm_hour_proto_rawDescGZIP(), []int{0}
}

func (x *EntityXsChatroomCharmHour) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *EntityXsChatroomCharmHour) GetDayHour() uint32 {
	if x != nil {
		return x.DayHour
	}
	return 0
}

func (x *EntityXsChatroomCharmHour) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *EntityXsChatroomCharmHour) GetRid() uint32 {
	if x != nil {
		return x.Rid
	}
	return 0
}

func (x *EntityXsChatroomCharmHour) GetRoomCreator() uint32 {
	if x != nil {
		return x.RoomCreator
	}
	return 0
}

func (x *EntityXsChatroomCharmHour) GetRoomName() string {
	if x != nil {
		return x.RoomName
	}
	return ""
}

func (x *EntityXsChatroomCharmHour) GetCharm() uint32 {
	if x != nil {
		return x.Charm
	}
	return 0
}

func (x *EntityXsChatroomCharmHour) GetPrevCharm() uint32 {
	if x != nil {
		return x.PrevCharm
	}
	return 0
}

func (x *EntityXsChatroomCharmHour) GetRealRank() uint32 {
	if x != nil {
		return x.RealRank
	}
	return 0
}

func (x *EntityXsChatroomCharmHour) GetPrevHourCharm() uint32 {
	if x != nil {
		return x.PrevHourCharm
	}
	return 0
}

func (x *EntityXsChatroomCharmHour) GetPrevRealRank() uint32 {
	if x != nil {
		return x.PrevRealRank
	}
	return 0
}

func (x *EntityXsChatroomCharmHour) GetPrevHourRank() uint32 {
	if x != nil {
		return x.PrevHourRank
	}
	return 0
}

func (x *EntityXsChatroomCharmHour) GetUpdateTime() uint32 {
	if x != nil {
		return x.UpdateTime
	}
	return 0
}

func (x *EntityXsChatroomCharmHour) GetCreateTime() uint32 {
	if x != nil {
		return x.CreateTime
	}
	return 0
}

func (x *EntityXsChatroomCharmHour) GetIsSync() uint32 {
	if x != nil {
		return x.IsSync
	}
	return 0
}

func (x *EntityXsChatroomCharmHour) GetAppId() uint32 {
	if x != nil {
		return x.AppId
	}
	return 0
}

var File_entity_xs_chatroom_charm_hour_proto protoreflect.FileDescriptor

var file_entity_xs_chatroom_charm_hour_proto_rawDesc = []byte{
	0x0a, 0x23, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x5f, 0x78, 0x73, 0x5f, 0x63, 0x68, 0x61, 0x74,
	0x72, 0x6f, 0x6f, 0x6d, 0x5f, 0x63, 0x68, 0x61, 0x72, 0x6d, 0x5f, 0x68, 0x6f, 0x75, 0x72, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70, 0x62, 0x22, 0xe4, 0x03, 0x0a, 0x19, 0x45, 0x6e,
	0x74, 0x69, 0x74, 0x79, 0x58, 0x73, 0x43, 0x68, 0x61, 0x74, 0x72, 0x6f, 0x6f, 0x6d, 0x43, 0x68,
	0x61, 0x72, 0x6d, 0x48, 0x6f, 0x75, 0x72, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x02, 0x69, 0x64, 0x12, 0x19, 0x0a, 0x08, 0x64, 0x61, 0x79, 0x5f, 0x68,
	0x6f, 0x75, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x07, 0x64, 0x61, 0x79, 0x48, 0x6f,
	0x75, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x72, 0x69, 0x64, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x03, 0x72, 0x69, 0x64, 0x12, 0x21, 0x0a, 0x0c, 0x72, 0x6f, 0x6f, 0x6d,
	0x5f, 0x63, 0x72, 0x65, 0x61, 0x74, 0x6f, 0x72, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0b,
	0x72, 0x6f, 0x6f, 0x6d, 0x43, 0x72, 0x65, 0x61, 0x74, 0x6f, 0x72, 0x12, 0x1b, 0x0a, 0x09, 0x72,
	0x6f, 0x6f, 0x6d, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x72, 0x6f, 0x6f, 0x6d, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x68, 0x61, 0x72,
	0x6d, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x63, 0x68, 0x61, 0x72, 0x6d, 0x12, 0x1d,
	0x0a, 0x0a, 0x70, 0x72, 0x65, 0x76, 0x5f, 0x63, 0x68, 0x61, 0x72, 0x6d, 0x18, 0x08, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x09, 0x70, 0x72, 0x65, 0x76, 0x43, 0x68, 0x61, 0x72, 0x6d, 0x12, 0x1b, 0x0a,
	0x09, 0x72, 0x65, 0x61, 0x6c, 0x5f, 0x72, 0x61, 0x6e, 0x6b, 0x18, 0x09, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x08, 0x72, 0x65, 0x61, 0x6c, 0x52, 0x61, 0x6e, 0x6b, 0x12, 0x26, 0x0a, 0x0f, 0x70, 0x72,
	0x65, 0x76, 0x5f, 0x68, 0x6f, 0x75, 0x72, 0x5f, 0x63, 0x68, 0x61, 0x72, 0x6d, 0x18, 0x0a, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x0d, 0x70, 0x72, 0x65, 0x76, 0x48, 0x6f, 0x75, 0x72, 0x43, 0x68, 0x61,
	0x72, 0x6d, 0x12, 0x24, 0x0a, 0x0e, 0x70, 0x72, 0x65, 0x76, 0x5f, 0x72, 0x65, 0x61, 0x6c, 0x5f,
	0x72, 0x61, 0x6e, 0x6b, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0c, 0x70, 0x72, 0x65, 0x76,
	0x52, 0x65, 0x61, 0x6c, 0x52, 0x61, 0x6e, 0x6b, 0x12, 0x24, 0x0a, 0x0e, 0x70, 0x72, 0x65, 0x76,
	0x5f, 0x68, 0x6f, 0x75, 0x72, 0x5f, 0x72, 0x61, 0x6e, 0x6b, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x0c, 0x70, 0x72, 0x65, 0x76, 0x48, 0x6f, 0x75, 0x72, 0x52, 0x61, 0x6e, 0x6b, 0x12, 0x1f,
	0x0a, 0x0b, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x0d, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x0a, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x12,
	0x1f, 0x0a, 0x0b, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x0e,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65,
	0x12, 0x17, 0x0a, 0x07, 0x69, 0x73, 0x5f, 0x73, 0x79, 0x6e, 0x63, 0x18, 0x0f, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x06, 0x69, 0x73, 0x53, 0x79, 0x6e, 0x63, 0x12, 0x15, 0x0a, 0x06, 0x61, 0x70, 0x70,
	0x5f, 0x69, 0x64, 0x18, 0x10, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x61, 0x70, 0x70, 0x49, 0x64,
	0x42, 0x0b, 0x5a, 0x09, 0x2e, 0x2e, 0x2f, 0x61, 0x70, 0x70, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_entity_xs_chatroom_charm_hour_proto_rawDescOnce sync.Once
	file_entity_xs_chatroom_charm_hour_proto_rawDescData = file_entity_xs_chatroom_charm_hour_proto_rawDesc
)

func file_entity_xs_chatroom_charm_hour_proto_rawDescGZIP() []byte {
	file_entity_xs_chatroom_charm_hour_proto_rawDescOnce.Do(func() {
		file_entity_xs_chatroom_charm_hour_proto_rawDescData = protoimpl.X.CompressGZIP(file_entity_xs_chatroom_charm_hour_proto_rawDescData)
	})
	return file_entity_xs_chatroom_charm_hour_proto_rawDescData
}

var file_entity_xs_chatroom_charm_hour_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_entity_xs_chatroom_charm_hour_proto_goTypes = []interface{}{
	(*EntityXsChatroomCharmHour)(nil), // 0: pb.EntityXsChatroomCharmHour
}
var file_entity_xs_chatroom_charm_hour_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_entity_xs_chatroom_charm_hour_proto_init() }
func file_entity_xs_chatroom_charm_hour_proto_init() {
	if File_entity_xs_chatroom_charm_hour_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_entity_xs_chatroom_charm_hour_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EntityXsChatroomCharmHour); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_entity_xs_chatroom_charm_hour_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_entity_xs_chatroom_charm_hour_proto_goTypes,
		DependencyIndexes: file_entity_xs_chatroom_charm_hour_proto_depIdxs,
		MessageInfos:      file_entity_xs_chatroom_charm_hour_proto_msgTypes,
	}.Build()
	File_entity_xs_chatroom_charm_hour_proto = out.File
	file_entity_xs_chatroom_charm_hour_proto_rawDesc = nil
	file_entity_xs_chatroom_charm_hour_proto_goTypes = nil
	file_entity_xs_chatroom_charm_hour_proto_depIdxs = nil
}
