// ==========================================================================
// This is auto-generated by gf cli tool. DO NOT EDIT THIS FILE MANUALLY.
// 重要! 增加数据库字段，只能向后增加，否则不能使用工具生成proto
// ==========================================================================

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.23.0
// 	protoc        v3.15.5
// source: entity_xs_stranger_reward.proto

package pb

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type EntityXsStrangerReward struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	//@inject_tag: orm:"id,primary"
	Id uint32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty" orm:"id,primary"` // primary key
	//@inject_tag: orm:"sender"
	Sender uint32 `protobuf:"varint,2,opt,name=sender,proto3" json:"sender,omitempty" orm:"sender"` // from
	//@inject_tag: orm:"receiver"
	Receiver uint32 `protobuf:"varint,3,opt,name=receiver,proto3" json:"receiver,omitempty" orm:"receiver"` // to
	//@inject_tag: orm:"last_rid"
	LastRid uint32 `protobuf:"varint,4,opt,name=last_rid,json=lastRid,proto3" json:"last_rid,omitempty" orm:"last_rid"` // 最后一次送礼所在的房间
	//@inject_tag: orm:"last_gift_id"
	LastGiftId uint32 `protobuf:"varint,5,opt,name=last_gift_id,json=lastGiftId,proto3" json:"last_gift_id,omitempty" orm:"last_gift_id"` // 最后一次送礼的ID
	//@inject_tag: orm:"last_gift_num"
	LastGiftNum uint32 `protobuf:"varint,6,opt,name=last_gift_num,json=lastGiftNum,proto3" json:"last_gift_num,omitempty" orm:"last_gift_num"` // 最后一次送礼的个数
	//@inject_tag: orm:"total_money"
	TotalMoney uint32 `protobuf:"varint,7,opt,name=total_money,json=totalMoney,proto3" json:"total_money,omitempty" orm:"total_money"` // 累计金额
	//@inject_tag: orm:"unread_count"
	UnreadCount uint32 `protobuf:"varint,8,opt,name=unread_count,json=unreadCount,proto3" json:"unread_count,omitempty" orm:"unread_count"` // 未读数
	//@inject_tag: orm:"dateline"
	Dateline uint32 `protobuf:"varint,9,opt,name=dateline,proto3" json:"dateline,omitempty" orm:"dateline"` // dateline
	//@inject_tag: orm:"updateline"
	Updateline uint32 `protobuf:"varint,10,opt,name=updateline,proto3" json:"updateline,omitempty" orm:"updateline"` // updateline
}

func (x *EntityXsStrangerReward) Reset() {
	*x = EntityXsStrangerReward{}
	if protoimpl.UnsafeEnabled {
		mi := &file_entity_xs_stranger_reward_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EntityXsStrangerReward) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EntityXsStrangerReward) ProtoMessage() {}

func (x *EntityXsStrangerReward) ProtoReflect() protoreflect.Message {
	mi := &file_entity_xs_stranger_reward_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EntityXsStrangerReward.ProtoReflect.Descriptor instead.
func (*EntityXsStrangerReward) Descriptor() ([]byte, []int) {
	return file_entity_xs_stranger_reward_proto_rawDescGZIP(), []int{0}
}

func (x *EntityXsStrangerReward) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *EntityXsStrangerReward) GetSender() uint32 {
	if x != nil {
		return x.Sender
	}
	return 0
}

func (x *EntityXsStrangerReward) GetReceiver() uint32 {
	if x != nil {
		return x.Receiver
	}
	return 0
}

func (x *EntityXsStrangerReward) GetLastRid() uint32 {
	if x != nil {
		return x.LastRid
	}
	return 0
}

func (x *EntityXsStrangerReward) GetLastGiftId() uint32 {
	if x != nil {
		return x.LastGiftId
	}
	return 0
}

func (x *EntityXsStrangerReward) GetLastGiftNum() uint32 {
	if x != nil {
		return x.LastGiftNum
	}
	return 0
}

func (x *EntityXsStrangerReward) GetTotalMoney() uint32 {
	if x != nil {
		return x.TotalMoney
	}
	return 0
}

func (x *EntityXsStrangerReward) GetUnreadCount() uint32 {
	if x != nil {
		return x.UnreadCount
	}
	return 0
}

func (x *EntityXsStrangerReward) GetDateline() uint32 {
	if x != nil {
		return x.Dateline
	}
	return 0
}

func (x *EntityXsStrangerReward) GetUpdateline() uint32 {
	if x != nil {
		return x.Updateline
	}
	return 0
}

var File_entity_xs_stranger_reward_proto protoreflect.FileDescriptor

var file_entity_xs_stranger_reward_proto_rawDesc = []byte{
	0x0a, 0x1f, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x5f, 0x78, 0x73, 0x5f, 0x73, 0x74, 0x72, 0x61,
	0x6e, 0x67, 0x65, 0x72, 0x5f, 0x72, 0x65, 0x77, 0x61, 0x72, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x02, 0x70, 0x62, 0x22, 0xbd, 0x02, 0x0a, 0x16, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x79,
	0x58, 0x73, 0x53, 0x74, 0x72, 0x61, 0x6e, 0x67, 0x65, 0x72, 0x52, 0x65, 0x77, 0x61, 0x72, 0x64,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x02, 0x69, 0x64,
	0x12, 0x16, 0x0a, 0x06, 0x73, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x06, 0x73, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x12, 0x1a, 0x0a, 0x08, 0x72, 0x65, 0x63, 0x65,
	0x69, 0x76, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x08, 0x72, 0x65, 0x63, 0x65,
	0x69, 0x76, 0x65, 0x72, 0x12, 0x19, 0x0a, 0x08, 0x6c, 0x61, 0x73, 0x74, 0x5f, 0x72, 0x69, 0x64,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x07, 0x6c, 0x61, 0x73, 0x74, 0x52, 0x69, 0x64, 0x12,
	0x20, 0x0a, 0x0c, 0x6c, 0x61, 0x73, 0x74, 0x5f, 0x67, 0x69, 0x66, 0x74, 0x5f, 0x69, 0x64, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0a, 0x6c, 0x61, 0x73, 0x74, 0x47, 0x69, 0x66, 0x74, 0x49,
	0x64, 0x12, 0x22, 0x0a, 0x0d, 0x6c, 0x61, 0x73, 0x74, 0x5f, 0x67, 0x69, 0x66, 0x74, 0x5f, 0x6e,
	0x75, 0x6d, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0b, 0x6c, 0x61, 0x73, 0x74, 0x47, 0x69,
	0x66, 0x74, 0x4e, 0x75, 0x6d, 0x12, 0x1f, 0x0a, 0x0b, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x5f, 0x6d,
	0x6f, 0x6e, 0x65, 0x79, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0a, 0x74, 0x6f, 0x74, 0x61,
	0x6c, 0x4d, 0x6f, 0x6e, 0x65, 0x79, 0x12, 0x21, 0x0a, 0x0c, 0x75, 0x6e, 0x72, 0x65, 0x61, 0x64,
	0x5f, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0b, 0x75, 0x6e,
	0x72, 0x65, 0x61, 0x64, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x64, 0x61, 0x74,
	0x65, 0x6c, 0x69, 0x6e, 0x65, 0x18, 0x09, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x08, 0x64, 0x61, 0x74,
	0x65, 0x6c, 0x69, 0x6e, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x6c,
	0x69, 0x6e, 0x65, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0a, 0x75, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x6c, 0x69, 0x6e, 0x65, 0x42, 0x0b, 0x5a, 0x09, 0x2e, 0x2e, 0x2f, 0x61, 0x70, 0x70, 0x2f,
	0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_entity_xs_stranger_reward_proto_rawDescOnce sync.Once
	file_entity_xs_stranger_reward_proto_rawDescData = file_entity_xs_stranger_reward_proto_rawDesc
)

func file_entity_xs_stranger_reward_proto_rawDescGZIP() []byte {
	file_entity_xs_stranger_reward_proto_rawDescOnce.Do(func() {
		file_entity_xs_stranger_reward_proto_rawDescData = protoimpl.X.CompressGZIP(file_entity_xs_stranger_reward_proto_rawDescData)
	})
	return file_entity_xs_stranger_reward_proto_rawDescData
}

var file_entity_xs_stranger_reward_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_entity_xs_stranger_reward_proto_goTypes = []interface{}{
	(*EntityXsStrangerReward)(nil), // 0: pb.EntityXsStrangerReward
}
var file_entity_xs_stranger_reward_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_entity_xs_stranger_reward_proto_init() }
func file_entity_xs_stranger_reward_proto_init() {
	if File_entity_xs_stranger_reward_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_entity_xs_stranger_reward_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EntityXsStrangerReward); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_entity_xs_stranger_reward_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_entity_xs_stranger_reward_proto_goTypes,
		DependencyIndexes: file_entity_xs_stranger_reward_proto_depIdxs,
		MessageInfos:      file_entity_xs_stranger_reward_proto_msgTypes,
	}.Build()
	File_entity_xs_stranger_reward_proto = out.File
	file_entity_xs_stranger_reward_proto_rawDesc = nil
	file_entity_xs_stranger_reward_proto_goTypes = nil
	file_entity_xs_stranger_reward_proto_depIdxs = nil
}
