// ==========================================================================
// This is auto-generated by gf cli tool. DO NOT EDIT THIS FILE MANUALLY.
// 重要! 增加数据库字段，只能向后增加，否则不能使用工具生成proto
// ==========================================================================

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.15.5
// source: entity_xs_room_data_phase.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EntityXsRoomDataPhase struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	//@inject_tag: orm:"id,primary"
	Id int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty" orm:"id,primary"` //
	//@inject_tag: orm:"rid"
	Rid int32 `protobuf:"varint,2,opt,name=rid,proto3" json:"rid,omitempty" orm:"rid"` // 房间ID
	//@inject_tag: orm:"date_phase"
	DatePhase string `protobuf:"bytes,3,opt,name=date_phase,json=datePhase,proto3" json:"date_phase,omitempty" orm:"date_phase"` // 时段
	//@inject_tag: orm:"enter_info"
	EnterInfo string `protobuf:"bytes,4,opt,name=enter_info,json=enterInfo,proto3" json:"enter_info,omitempty" orm:"enter_info"` // 进房信息
	//@inject_tag: orm:"pay_info"
	PayInfo string `protobuf:"bytes,5,opt,name=pay_info,json=payInfo,proto3" json:"pay_info,omitempty" orm:"pay_info"` // 付费信息
	//@inject_tag: orm:"new_trans_info"
	NewTransInfo string `protobuf:"bytes,6,opt,name=new_trans_info,json=newTransInfo,proto3" json:"new_trans_info,omitempty" orm:"new_trans_info"` // 新转付费信息
	//@inject_tag: orm:"package_info"
	PackageInfo string `protobuf:"bytes,7,opt,name=package_info,json=packageInfo,proto3" json:"package_info,omitempty" orm:"package_info"` // 房间流水信息
	//@inject_tag: orm:"broadcast_info"
	BroadcastInfo string `protobuf:"bytes,8,opt,name=broadcast_info,json=broadcastInfo,proto3" json:"broadcast_info,omitempty" orm:"broadcast_info"` // 开播时长信息
	//@inject_tag: orm:"fans_info"
	FansInfo string `protobuf:"bytes,9,opt,name=fans_info,json=fansInfo,proto3" json:"fans_info,omitempty" orm:"fans_info"` // 新增粉丝信息
	//@inject_tag: orm:"reception_info"
	ReceptionInfo string `protobuf:"bytes,10,opt,name=reception_info,json=receptionInfo,proto3" json:"reception_info,omitempty" orm:"reception_info"` // 接待信息
	//@inject_tag: orm:"create_time"
	CreateTime int32 `protobuf:"varint,11,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty" orm:"create_time"` // 创建时间
}

func (x *EntityXsRoomDataPhase) Reset() {
	*x = EntityXsRoomDataPhase{}
	if protoimpl.UnsafeEnabled {
		mi := &file_entity_xs_room_data_phase_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EntityXsRoomDataPhase) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EntityXsRoomDataPhase) ProtoMessage() {}

func (x *EntityXsRoomDataPhase) ProtoReflect() protoreflect.Message {
	mi := &file_entity_xs_room_data_phase_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EntityXsRoomDataPhase.ProtoReflect.Descriptor instead.
func (*EntityXsRoomDataPhase) Descriptor() ([]byte, []int) {
	return file_entity_xs_room_data_phase_proto_rawDescGZIP(), []int{0}
}

func (x *EntityXsRoomDataPhase) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *EntityXsRoomDataPhase) GetRid() int32 {
	if x != nil {
		return x.Rid
	}
	return 0
}

func (x *EntityXsRoomDataPhase) GetDatePhase() string {
	if x != nil {
		return x.DatePhase
	}
	return ""
}

func (x *EntityXsRoomDataPhase) GetEnterInfo() string {
	if x != nil {
		return x.EnterInfo
	}
	return ""
}

func (x *EntityXsRoomDataPhase) GetPayInfo() string {
	if x != nil {
		return x.PayInfo
	}
	return ""
}

func (x *EntityXsRoomDataPhase) GetNewTransInfo() string {
	if x != nil {
		return x.NewTransInfo
	}
	return ""
}

func (x *EntityXsRoomDataPhase) GetPackageInfo() string {
	if x != nil {
		return x.PackageInfo
	}
	return ""
}

func (x *EntityXsRoomDataPhase) GetBroadcastInfo() string {
	if x != nil {
		return x.BroadcastInfo
	}
	return ""
}

func (x *EntityXsRoomDataPhase) GetFansInfo() string {
	if x != nil {
		return x.FansInfo
	}
	return ""
}

func (x *EntityXsRoomDataPhase) GetReceptionInfo() string {
	if x != nil {
		return x.ReceptionInfo
	}
	return ""
}

func (x *EntityXsRoomDataPhase) GetCreateTime() int32 {
	if x != nil {
		return x.CreateTime
	}
	return 0
}

var File_entity_xs_room_data_phase_proto protoreflect.FileDescriptor

var file_entity_xs_room_data_phase_proto_rawDesc = []byte{
	0x0a, 0x1f, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x5f, 0x78, 0x73, 0x5f, 0x72, 0x6f, 0x6f, 0x6d,
	0x5f, 0x64, 0x61, 0x74, 0x61, 0x5f, 0x70, 0x68, 0x61, 0x73, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x02, 0x70, 0x62, 0x22, 0xe7, 0x02, 0x0a, 0x15, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x79,
	0x58, 0x73, 0x52, 0x6f, 0x6f, 0x6d, 0x44, 0x61, 0x74, 0x61, 0x50, 0x68, 0x61, 0x73, 0x65, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x12,
	0x10, 0x0a, 0x03, 0x72, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x72, 0x69,
	0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x64, 0x61, 0x74, 0x65, 0x5f, 0x70, 0x68, 0x61, 0x73, 0x65, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x64, 0x61, 0x74, 0x65, 0x50, 0x68, 0x61, 0x73, 0x65,
	0x12, 0x1d, 0x0a, 0x0a, 0x65, 0x6e, 0x74, 0x65, 0x72, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x65, 0x6e, 0x74, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x12,
	0x19, 0x0a, 0x08, 0x70, 0x61, 0x79, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x70, 0x61, 0x79, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x24, 0x0a, 0x0e, 0x6e, 0x65,
	0x77, 0x5f, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x06, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0c, 0x6e, 0x65, 0x77, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x49, 0x6e, 0x66, 0x6f,
	0x12, 0x21, 0x0a, 0x0c, 0x70, 0x61, 0x63, 0x6b, 0x61, 0x67, 0x65, 0x5f, 0x69, 0x6e, 0x66, 0x6f,
	0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x70, 0x61, 0x63, 0x6b, 0x61, 0x67, 0x65, 0x49,
	0x6e, 0x66, 0x6f, 0x12, 0x25, 0x0a, 0x0e, 0x62, 0x72, 0x6f, 0x61, 0x64, 0x63, 0x61, 0x73, 0x74,
	0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x62, 0x72, 0x6f,
	0x61, 0x64, 0x63, 0x61, 0x73, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x1b, 0x0a, 0x09, 0x66, 0x61,
	0x6e, 0x73, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x66,
	0x61, 0x6e, 0x73, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x25, 0x0a, 0x0e, 0x72, 0x65, 0x63, 0x65, 0x70,
	0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0d, 0x72, 0x65, 0x63, 0x65, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x1f,
	0x0a, 0x0b, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x0b, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x42,
	0x0b, 0x5a, 0x09, 0x2e, 0x2e, 0x2f, 0x61, 0x70, 0x70, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_entity_xs_room_data_phase_proto_rawDescOnce sync.Once
	file_entity_xs_room_data_phase_proto_rawDescData = file_entity_xs_room_data_phase_proto_rawDesc
)

func file_entity_xs_room_data_phase_proto_rawDescGZIP() []byte {
	file_entity_xs_room_data_phase_proto_rawDescOnce.Do(func() {
		file_entity_xs_room_data_phase_proto_rawDescData = protoimpl.X.CompressGZIP(file_entity_xs_room_data_phase_proto_rawDescData)
	})
	return file_entity_xs_room_data_phase_proto_rawDescData
}

var file_entity_xs_room_data_phase_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_entity_xs_room_data_phase_proto_goTypes = []interface{}{
	(*EntityXsRoomDataPhase)(nil), // 0: pb.EntityXsRoomDataPhase
}
var file_entity_xs_room_data_phase_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_entity_xs_room_data_phase_proto_init() }
func file_entity_xs_room_data_phase_proto_init() {
	if File_entity_xs_room_data_phase_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_entity_xs_room_data_phase_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EntityXsRoomDataPhase); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_entity_xs_room_data_phase_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_entity_xs_room_data_phase_proto_goTypes,
		DependencyIndexes: file_entity_xs_room_data_phase_proto_depIdxs,
		MessageInfos:      file_entity_xs_room_data_phase_proto_msgTypes,
	}.Build()
	File_entity_xs_room_data_phase_proto = out.File
	file_entity_xs_room_data_phase_proto_rawDesc = nil
	file_entity_xs_room_data_phase_proto_goTypes = nil
	file_entity_xs_room_data_phase_proto_depIdxs = nil
}
