// ==========================================================================
// This is auto-generated by gf cli tool. DO NOT EDIT THIS FILE MANUALLY.
// 重要! 增加数据库字段，只能向后增加，否则不能使用工具生成proto
// ==========================================================================

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.15.5
// source: entity_xs_popular_user.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EntityXsPopularUser struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	//@inject_tag: orm:"uid,primary"
	Uid int32 `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty" orm:"uid,primary"` //
	//@inject_tag: orm:"app_id,primary"
	AppId int32 `protobuf:"varint,2,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty" orm:"app_id,primary"` //
	//@inject_tag: orm:"reason"
	Reason string `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty" orm:"reason"` // 认证理由:红人包括 皇帝/国王，平台认证、拥有520+（CP、小甜心）守护、拥有电台黄金守护
	//@inject_tag: orm:"score"
	Score int32 `protobuf:"varint,4,opt,name=score,proto3" json:"score,omitempty" orm:"score"` // 人气
	//@inject_tag: orm:"popular_type"
	PopularType string `protobuf:"bytes,5,opt,name=popular_type,json=popularType,proto3" json:"popular_type,omitempty" orm:"popular_type"` //
	//@inject_tag: orm:"dateline"
	Dateline int32 `protobuf:"varint,6,opt,name=dateline,proto3" json:"dateline,omitempty" orm:"dateline"` //
	//@inject_tag: orm:"level"
	Level int32 `protobuf:"varint,7,opt,name=level,proto3" json:"level,omitempty" orm:"level"` //
}

func (x *EntityXsPopularUser) Reset() {
	*x = EntityXsPopularUser{}
	if protoimpl.UnsafeEnabled {
		mi := &file_entity_xs_popular_user_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EntityXsPopularUser) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EntityXsPopularUser) ProtoMessage() {}

func (x *EntityXsPopularUser) ProtoReflect() protoreflect.Message {
	mi := &file_entity_xs_popular_user_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EntityXsPopularUser.ProtoReflect.Descriptor instead.
func (*EntityXsPopularUser) Descriptor() ([]byte, []int) {
	return file_entity_xs_popular_user_proto_rawDescGZIP(), []int{0}
}

func (x *EntityXsPopularUser) GetUid() int32 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *EntityXsPopularUser) GetAppId() int32 {
	if x != nil {
		return x.AppId
	}
	return 0
}

func (x *EntityXsPopularUser) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *EntityXsPopularUser) GetScore() int32 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *EntityXsPopularUser) GetPopularType() string {
	if x != nil {
		return x.PopularType
	}
	return ""
}

func (x *EntityXsPopularUser) GetDateline() int32 {
	if x != nil {
		return x.Dateline
	}
	return 0
}

func (x *EntityXsPopularUser) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

var File_entity_xs_popular_user_proto protoreflect.FileDescriptor

var file_entity_xs_popular_user_proto_rawDesc = []byte{
	0x0a, 0x1c, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x5f, 0x78, 0x73, 0x5f, 0x70, 0x6f, 0x70, 0x75,
	0x6c, 0x61, 0x72, 0x5f, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02,
	0x70, 0x62, 0x22, 0xc1, 0x01, 0x0a, 0x13, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x58, 0x73, 0x50,
	0x6f, 0x70, 0x75, 0x6c, 0x61, 0x72, 0x55, 0x73, 0x65, 0x72, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x75, 0x69, 0x64, 0x12, 0x15, 0x0a, 0x06,
	0x61, 0x70, 0x70, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x61, 0x70,
	0x70, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x12, 0x14, 0x0a, 0x05, 0x73,
	0x63, 0x6f, 0x72, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x73, 0x63, 0x6f, 0x72,
	0x65, 0x12, 0x21, 0x0a, 0x0c, 0x70, 0x6f, 0x70, 0x75, 0x6c, 0x61, 0x72, 0x5f, 0x74, 0x79, 0x70,
	0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x70, 0x6f, 0x70, 0x75, 0x6c, 0x61, 0x72,
	0x54, 0x79, 0x70, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x64, 0x61, 0x74, 0x65, 0x6c, 0x69, 0x6e, 0x65,
	0x18, 0x06, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x64, 0x61, 0x74, 0x65, 0x6c, 0x69, 0x6e, 0x65,
	0x12, 0x14, 0x0a, 0x05, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x18, 0x07, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x05, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x42, 0x0b, 0x5a, 0x09, 0x2e, 0x2e, 0x2f, 0x61, 0x70, 0x70,
	0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_entity_xs_popular_user_proto_rawDescOnce sync.Once
	file_entity_xs_popular_user_proto_rawDescData = file_entity_xs_popular_user_proto_rawDesc
)

func file_entity_xs_popular_user_proto_rawDescGZIP() []byte {
	file_entity_xs_popular_user_proto_rawDescOnce.Do(func() {
		file_entity_xs_popular_user_proto_rawDescData = protoimpl.X.CompressGZIP(file_entity_xs_popular_user_proto_rawDescData)
	})
	return file_entity_xs_popular_user_proto_rawDescData
}

var file_entity_xs_popular_user_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_entity_xs_popular_user_proto_goTypes = []interface{}{
	(*EntityXsPopularUser)(nil), // 0: pb.EntityXsPopularUser
}
var file_entity_xs_popular_user_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_entity_xs_popular_user_proto_init() }
func file_entity_xs_popular_user_proto_init() {
	if File_entity_xs_popular_user_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_entity_xs_popular_user_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EntityXsPopularUser); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_entity_xs_popular_user_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_entity_xs_popular_user_proto_goTypes,
		DependencyIndexes: file_entity_xs_popular_user_proto_depIdxs,
		MessageInfos:      file_entity_xs_popular_user_proto_msgTypes,
	}.Build()
	File_entity_xs_popular_user_proto = out.File
	file_entity_xs_popular_user_proto_rawDesc = nil
	file_entity_xs_popular_user_proto_goTypes = nil
	file_entity_xs_popular_user_proto_depIdxs = nil
}
