// ==========================================================================
// This is auto-generated by gf cli tool. DO NOT EDIT THIS FILE MANUALLY.
// 重要! 增加数据库字段，只能向后增加，否则不能使用工具生成proto
// ==========================================================================

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.15.5
// source: entity_xs_confess_stage.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EntityXsConfessStage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	//@inject_tag: orm:"id,primary"
	Id uint32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty" orm:"id,primary"` // id
	//@inject_tag: orm:"uid"
	Uid uint32 `protobuf:"varint,2,opt,name=uid,proto3" json:"uid,omitempty" orm:"uid"` // 主动uid
	//@inject_tag: orm:"to_uid"
	ToUid uint32 `protobuf:"varint,3,opt,name=to_uid,json=toUid,proto3" json:"to_uid,omitempty" orm:"to_uid"` // 被动uid
	//@inject_tag: orm:"stage"
	Stage uint32 `protobuf:"varint,4,opt,name=stage,proto3" json:"stage,omitempty" orm:"stage"` // 0遇见你，1喜欢你，2表白，3在一起
	//@inject_tag: orm:"sent"
	Sent uint32 `protobuf:"varint,5,opt,name=sent,proto3" json:"sent,omitempty" orm:"sent"` // 本阶段礼物是否发送，0没有发送，1发送
	//@inject_tag: orm:"create_time"
	CreateTime int32 `protobuf:"varint,6,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty" orm:"create_time"` // 创建时间
	//@inject_tag: orm:"update_time"
	UpdateTime int32 `protobuf:"varint,7,opt,name=update_time,json=updateTime,proto3" json:"update_time,omitempty" orm:"update_time"` // 更新时间
}

func (x *EntityXsConfessStage) Reset() {
	*x = EntityXsConfessStage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_entity_xs_confess_stage_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EntityXsConfessStage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EntityXsConfessStage) ProtoMessage() {}

func (x *EntityXsConfessStage) ProtoReflect() protoreflect.Message {
	mi := &file_entity_xs_confess_stage_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EntityXsConfessStage.ProtoReflect.Descriptor instead.
func (*EntityXsConfessStage) Descriptor() ([]byte, []int) {
	return file_entity_xs_confess_stage_proto_rawDescGZIP(), []int{0}
}

func (x *EntityXsConfessStage) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *EntityXsConfessStage) GetUid() uint32 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *EntityXsConfessStage) GetToUid() uint32 {
	if x != nil {
		return x.ToUid
	}
	return 0
}

func (x *EntityXsConfessStage) GetStage() uint32 {
	if x != nil {
		return x.Stage
	}
	return 0
}

func (x *EntityXsConfessStage) GetSent() uint32 {
	if x != nil {
		return x.Sent
	}
	return 0
}

func (x *EntityXsConfessStage) GetCreateTime() int32 {
	if x != nil {
		return x.CreateTime
	}
	return 0
}

func (x *EntityXsConfessStage) GetUpdateTime() int32 {
	if x != nil {
		return x.UpdateTime
	}
	return 0
}

var File_entity_xs_confess_stage_proto protoreflect.FileDescriptor

var file_entity_xs_confess_stage_proto_rawDesc = []byte{
	0x0a, 0x1d, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x5f, 0x78, 0x73, 0x5f, 0x63, 0x6f, 0x6e, 0x66,
	0x65, 0x73, 0x73, 0x5f, 0x73, 0x74, 0x61, 0x67, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x02, 0x70, 0x62, 0x22, 0xbb, 0x01, 0x0a, 0x14, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x58, 0x73,
	0x43, 0x6f, 0x6e, 0x66, 0x65, 0x73, 0x73, 0x53, 0x74, 0x61, 0x67, 0x65, 0x12, 0x0e, 0x0a, 0x02,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x02, 0x69, 0x64, 0x12, 0x10, 0x0a, 0x03,
	0x75, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x03, 0x75, 0x69, 0x64, 0x12, 0x15,
	0x0a, 0x06, 0x74, 0x6f, 0x5f, 0x75, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05,
	0x74, 0x6f, 0x55, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x67, 0x65, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x73, 0x74, 0x61, 0x67, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x73,
	0x65, 0x6e, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x73, 0x65, 0x6e, 0x74, 0x12,
	0x1f, 0x0a, 0x0b, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x06,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65,
	0x12, 0x1f, 0x0a, 0x0b, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18,
	0x07, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d,
	0x65, 0x42, 0x0b, 0x5a, 0x09, 0x2e, 0x2e, 0x2f, 0x61, 0x70, 0x70, 0x2f, 0x70, 0x62, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_entity_xs_confess_stage_proto_rawDescOnce sync.Once
	file_entity_xs_confess_stage_proto_rawDescData = file_entity_xs_confess_stage_proto_rawDesc
)

func file_entity_xs_confess_stage_proto_rawDescGZIP() []byte {
	file_entity_xs_confess_stage_proto_rawDescOnce.Do(func() {
		file_entity_xs_confess_stage_proto_rawDescData = protoimpl.X.CompressGZIP(file_entity_xs_confess_stage_proto_rawDescData)
	})
	return file_entity_xs_confess_stage_proto_rawDescData
}

var file_entity_xs_confess_stage_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_entity_xs_confess_stage_proto_goTypes = []interface{}{
	(*EntityXsConfessStage)(nil), // 0: pb.EntityXsConfessStage
}
var file_entity_xs_confess_stage_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_entity_xs_confess_stage_proto_init() }
func file_entity_xs_confess_stage_proto_init() {
	if File_entity_xs_confess_stage_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_entity_xs_confess_stage_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EntityXsConfessStage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_entity_xs_confess_stage_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_entity_xs_confess_stage_proto_goTypes,
		DependencyIndexes: file_entity_xs_confess_stage_proto_depIdxs,
		MessageInfos:      file_entity_xs_confess_stage_proto_msgTypes,
	}.Build()
	File_entity_xs_confess_stage_proto = out.File
	file_entity_xs_confess_stage_proto_rawDesc = nil
	file_entity_xs_confess_stage_proto_goTypes = nil
	file_entity_xs_confess_stage_proto_depIdxs = nil
}
