// ==========================================================================
// This is auto-generated by gf cli tool. DO NOT EDIT THIS FILE MANUALLY.
// 重要! 增加数据库字段，只能向后增加，否则不能使用工具生成proto
// ==========================================================================

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.15.5
// source: entity_xs_user_box_data.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EntityXsUserBoxData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	//@inject_tag: orm:"uid,primary"
	Uid int32 `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty" orm:"uid,primary"` //
	//@inject_tag: orm:"total_money"
	TotalMoney uint32 `protobuf:"varint,2,opt,name=total_money,json=totalMoney,proto3" json:"total_money,omitempty" orm:"total_money"` //
	//@inject_tag: orm:"total_return"
	TotalReturn uint32 `protobuf:"varint,3,opt,name=total_return,json=totalReturn,proto3" json:"total_return,omitempty" orm:"total_return"` //
	//@inject_tag: orm:"recent_money"
	RecentMoney uint32 `protobuf:"varint,4,opt,name=recent_money,json=recentMoney,proto3" json:"recent_money,omitempty" orm:"recent_money"` //
	//@inject_tag: orm:"recent_return"
	RecentReturn uint32 `protobuf:"varint,5,opt,name=recent_return,json=recentReturn,proto3" json:"recent_return,omitempty" orm:"recent_return"` //
	//@inject_tag: orm:"dateline"
	Dateline int32 `protobuf:"varint,6,opt,name=dateline,proto3" json:"dateline,omitempty" orm:"dateline"` //
}

func (x *EntityXsUserBoxData) Reset() {
	*x = EntityXsUserBoxData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_entity_xs_user_box_data_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EntityXsUserBoxData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EntityXsUserBoxData) ProtoMessage() {}

func (x *EntityXsUserBoxData) ProtoReflect() protoreflect.Message {
	mi := &file_entity_xs_user_box_data_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EntityXsUserBoxData.ProtoReflect.Descriptor instead.
func (*EntityXsUserBoxData) Descriptor() ([]byte, []int) {
	return file_entity_xs_user_box_data_proto_rawDescGZIP(), []int{0}
}

func (x *EntityXsUserBoxData) GetUid() int32 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *EntityXsUserBoxData) GetTotalMoney() uint32 {
	if x != nil {
		return x.TotalMoney
	}
	return 0
}

func (x *EntityXsUserBoxData) GetTotalReturn() uint32 {
	if x != nil {
		return x.TotalReturn
	}
	return 0
}

func (x *EntityXsUserBoxData) GetRecentMoney() uint32 {
	if x != nil {
		return x.RecentMoney
	}
	return 0
}

func (x *EntityXsUserBoxData) GetRecentReturn() uint32 {
	if x != nil {
		return x.RecentReturn
	}
	return 0
}

func (x *EntityXsUserBoxData) GetDateline() int32 {
	if x != nil {
		return x.Dateline
	}
	return 0
}

var File_entity_xs_user_box_data_proto protoreflect.FileDescriptor

var file_entity_xs_user_box_data_proto_rawDesc = []byte{
	0x0a, 0x1d, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x5f, 0x78, 0x73, 0x5f, 0x75, 0x73, 0x65, 0x72,
	0x5f, 0x62, 0x6f, 0x78, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x02, 0x70, 0x62, 0x22, 0xcf, 0x01, 0x0a, 0x13, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x58, 0x73,
	0x55, 0x73, 0x65, 0x72, 0x42, 0x6f, 0x78, 0x44, 0x61, 0x74, 0x61, 0x12, 0x10, 0x0a, 0x03, 0x75,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x75, 0x69, 0x64, 0x12, 0x1f, 0x0a,
	0x0b, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x5f, 0x6d, 0x6f, 0x6e, 0x65, 0x79, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x0a, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x4d, 0x6f, 0x6e, 0x65, 0x79, 0x12, 0x21,
	0x0a, 0x0c, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x5f, 0x72, 0x65, 0x74, 0x75, 0x72, 0x6e, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x0b, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x52, 0x65, 0x74, 0x75, 0x72,
	0x6e, 0x12, 0x21, 0x0a, 0x0c, 0x72, 0x65, 0x63, 0x65, 0x6e, 0x74, 0x5f, 0x6d, 0x6f, 0x6e, 0x65,
	0x79, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0b, 0x72, 0x65, 0x63, 0x65, 0x6e, 0x74, 0x4d,
	0x6f, 0x6e, 0x65, 0x79, 0x12, 0x23, 0x0a, 0x0d, 0x72, 0x65, 0x63, 0x65, 0x6e, 0x74, 0x5f, 0x72,
	0x65, 0x74, 0x75, 0x72, 0x6e, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0c, 0x72, 0x65, 0x63,
	0x65, 0x6e, 0x74, 0x52, 0x65, 0x74, 0x75, 0x72, 0x6e, 0x12, 0x1a, 0x0a, 0x08, 0x64, 0x61, 0x74,
	0x65, 0x6c, 0x69, 0x6e, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x64, 0x61, 0x74,
	0x65, 0x6c, 0x69, 0x6e, 0x65, 0x42, 0x0b, 0x5a, 0x09, 0x2e, 0x2e, 0x2f, 0x61, 0x70, 0x70, 0x2f,
	0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_entity_xs_user_box_data_proto_rawDescOnce sync.Once
	file_entity_xs_user_box_data_proto_rawDescData = file_entity_xs_user_box_data_proto_rawDesc
)

func file_entity_xs_user_box_data_proto_rawDescGZIP() []byte {
	file_entity_xs_user_box_data_proto_rawDescOnce.Do(func() {
		file_entity_xs_user_box_data_proto_rawDescData = protoimpl.X.CompressGZIP(file_entity_xs_user_box_data_proto_rawDescData)
	})
	return file_entity_xs_user_box_data_proto_rawDescData
}

var file_entity_xs_user_box_data_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_entity_xs_user_box_data_proto_goTypes = []interface{}{
	(*EntityXsUserBoxData)(nil), // 0: pb.EntityXsUserBoxData
}
var file_entity_xs_user_box_data_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_entity_xs_user_box_data_proto_init() }
func file_entity_xs_user_box_data_proto_init() {
	if File_entity_xs_user_box_data_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_entity_xs_user_box_data_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EntityXsUserBoxData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_entity_xs_user_box_data_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_entity_xs_user_box_data_proto_goTypes,
		DependencyIndexes: file_entity_xs_user_box_data_proto_depIdxs,
		MessageInfos:      file_entity_xs_user_box_data_proto_msgTypes,
	}.Build()
	File_entity_xs_user_box_data_proto = out.File
	file_entity_xs_user_box_data_proto_rawDesc = nil
	file_entity_xs_user_box_data_proto_goTypes = nil
	file_entity_xs_user_box_data_proto_depIdxs = nil
}
