// ==========================================================================
// This is auto-generated by gf cli tool. DO NOT EDIT THIS FILE MANUALLY.
// 重要! 增加数据库字段，只能向后增加，否则不能使用工具生成proto
// ==========================================================================

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.15.5
// source: entity_xs_chatroom_rank_pk_list.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EntityXsChatroomRankPkList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	//@inject_tag: orm:"id,primary"
	Id uint32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty" orm:"id,primary"` //
	//@inject_tag: orm:"rid"
	Rid uint32 `protobuf:"varint,2,opt,name=rid,proto3" json:"rid,omitempty" orm:"rid"` // 房间ID
	//@inject_tag: orm:"uid"
	Uid uint32 `protobuf:"varint,3,opt,name=uid,proto3" json:"uid,omitempty" orm:"uid"` // 用户UID
	//@inject_tag: orm:"pk_version"
	PkVersion uint32 `protobuf:"varint,4,opt,name=pk_version,json=pkVersion,proto3" json:"pk_version,omitempty" orm:"pk_version"` // pk版本
	//@inject_tag: orm:"point"
	Point uint32 `protobuf:"varint,5,opt,name=point,proto3" json:"point,omitempty" orm:"point"` // 是否代开PK模式
	//@inject_tag: orm:"create_time"
	CreateTime uint32 `protobuf:"varint,6,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty" orm:"create_time"` // 开启时间
	//@inject_tag: orm:"update_time"
	UpdateTime uint32 `protobuf:"varint,7,opt,name=update_time,json=updateTime,proto3" json:"update_time,omitempty" orm:"update_time"` // 更新时间
}

func (x *EntityXsChatroomRankPkList) Reset() {
	*x = EntityXsChatroomRankPkList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_entity_xs_chatroom_rank_pk_list_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EntityXsChatroomRankPkList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EntityXsChatroomRankPkList) ProtoMessage() {}

func (x *EntityXsChatroomRankPkList) ProtoReflect() protoreflect.Message {
	mi := &file_entity_xs_chatroom_rank_pk_list_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EntityXsChatroomRankPkList.ProtoReflect.Descriptor instead.
func (*EntityXsChatroomRankPkList) Descriptor() ([]byte, []int) {
	return file_entity_xs_chatroom_rank_pk_list_proto_rawDescGZIP(), []int{0}
}

func (x *EntityXsChatroomRankPkList) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *EntityXsChatroomRankPkList) GetRid() uint32 {
	if x != nil {
		return x.Rid
	}
	return 0
}

func (x *EntityXsChatroomRankPkList) GetUid() uint32 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *EntityXsChatroomRankPkList) GetPkVersion() uint32 {
	if x != nil {
		return x.PkVersion
	}
	return 0
}

func (x *EntityXsChatroomRankPkList) GetPoint() uint32 {
	if x != nil {
		return x.Point
	}
	return 0
}

func (x *EntityXsChatroomRankPkList) GetCreateTime() uint32 {
	if x != nil {
		return x.CreateTime
	}
	return 0
}

func (x *EntityXsChatroomRankPkList) GetUpdateTime() uint32 {
	if x != nil {
		return x.UpdateTime
	}
	return 0
}

var File_entity_xs_chatroom_rank_pk_list_proto protoreflect.FileDescriptor

var file_entity_xs_chatroom_rank_pk_list_proto_rawDesc = []byte{
	0x0a, 0x25, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x5f, 0x78, 0x73, 0x5f, 0x63, 0x68, 0x61, 0x74,
	0x72, 0x6f, 0x6f, 0x6d, 0x5f, 0x72, 0x61, 0x6e, 0x6b, 0x5f, 0x70, 0x6b, 0x5f, 0x6c, 0x69, 0x73,
	0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70, 0x62, 0x22, 0xc7, 0x01, 0x0a, 0x1a,
	0x45, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x58, 0x73, 0x43, 0x68, 0x61, 0x74, 0x72, 0x6f, 0x6f, 0x6d,
	0x52, 0x61, 0x6e, 0x6b, 0x50, 0x6b, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x02, 0x69, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x72, 0x69,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x03, 0x72, 0x69, 0x64, 0x12, 0x10, 0x0a, 0x03,
	0x75, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x03, 0x75, 0x69, 0x64, 0x12, 0x1d,
	0x0a, 0x0a, 0x70, 0x6b, 0x5f, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x09, 0x70, 0x6b, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x14, 0x0a,
	0x05, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x70, 0x6f,
	0x69, 0x6e, 0x74, 0x12, 0x1f, 0x0a, 0x0b, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x5f, 0x74, 0x69,
	0x6d, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x54, 0x69, 0x6d, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x5f, 0x74,
	0x69, 0x6d, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0a, 0x75, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x54, 0x69, 0x6d, 0x65, 0x42, 0x0b, 0x5a, 0x09, 0x2e, 0x2e, 0x2f, 0x61, 0x70, 0x70, 0x2f,
	0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_entity_xs_chatroom_rank_pk_list_proto_rawDescOnce sync.Once
	file_entity_xs_chatroom_rank_pk_list_proto_rawDescData = file_entity_xs_chatroom_rank_pk_list_proto_rawDesc
)

func file_entity_xs_chatroom_rank_pk_list_proto_rawDescGZIP() []byte {
	file_entity_xs_chatroom_rank_pk_list_proto_rawDescOnce.Do(func() {
		file_entity_xs_chatroom_rank_pk_list_proto_rawDescData = protoimpl.X.CompressGZIP(file_entity_xs_chatroom_rank_pk_list_proto_rawDescData)
	})
	return file_entity_xs_chatroom_rank_pk_list_proto_rawDescData
}

var file_entity_xs_chatroom_rank_pk_list_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_entity_xs_chatroom_rank_pk_list_proto_goTypes = []interface{}{
	(*EntityXsChatroomRankPkList)(nil), // 0: pb.EntityXsChatroomRankPkList
}
var file_entity_xs_chatroom_rank_pk_list_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_entity_xs_chatroom_rank_pk_list_proto_init() }
func file_entity_xs_chatroom_rank_pk_list_proto_init() {
	if File_entity_xs_chatroom_rank_pk_list_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_entity_xs_chatroom_rank_pk_list_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EntityXsChatroomRankPkList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_entity_xs_chatroom_rank_pk_list_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_entity_xs_chatroom_rank_pk_list_proto_goTypes,
		DependencyIndexes: file_entity_xs_chatroom_rank_pk_list_proto_depIdxs,
		MessageInfos:      file_entity_xs_chatroom_rank_pk_list_proto_msgTypes,
	}.Build()
	File_entity_xs_chatroom_rank_pk_list_proto = out.File
	file_entity_xs_chatroom_rank_pk_list_proto_rawDesc = nil
	file_entity_xs_chatroom_rank_pk_list_proto_goTypes = nil
	file_entity_xs_chatroom_rank_pk_list_proto_depIdxs = nil
}
