// ==========================================================================
// This is auto-generated by gf cli tool. DO NOT EDIT THIS FILE MANUALLY.
// 重要! 增加数据库字段，只能向后增加，否则不能使用工具生成proto
// ==========================================================================

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.9.1
// source: entity_xs_group_user.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EntityXsGroupUser struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	//@inject_tag: orm:"id,primary"
	Id uint32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty" orm:"id,primary"` //
	//@inject_tag: orm:"group_id"
	GroupId uint32 `protobuf:"varint,2,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty" orm:"group_id"` // 群组id
	//@inject_tag: orm:"uid"
	Uid uint32 `protobuf:"varint,3,opt,name=uid,proto3" json:"uid,omitempty" orm:"uid"` // 用户id
	//@inject_tag: orm:"dateline"
	Dateline uint32 `protobuf:"varint,4,opt,name=dateline,proto3" json:"dateline,omitempty" orm:"dateline"` // 加入/退出时间
	//@inject_tag: orm:"deleted"
	Deleted uint32 `protobuf:"varint,5,opt,name=deleted,proto3" json:"deleted,omitempty" orm:"deleted"` // 1自己退出；2为管理删除的；3拉黑了
	//@inject_tag: orm:"forbidden"
	Forbidden uint32 `protobuf:"varint,6,opt,name=forbidden,proto3" json:"forbidden,omitempty" orm:"forbidden"` // 禁言结束时间
	//@inject_tag: orm:"is_tmp"
	IsTmp uint32 `protobuf:"varint,7,opt,name=is_tmp,json=isTmp,proto3" json:"is_tmp,omitempty" orm:"is_tmp"` // 是否是该用户的临时群
	//@inject_tag: orm:"speak"
	Speak uint32 `protobuf:"varint,8,opt,name=speak,proto3" json:"speak,omitempty" orm:"speak"` // 上次发言时间
	//@inject_tag: orm:"nickname"
	Nickname string `protobuf:"bytes,9,opt,name=nickname,proto3" json:"nickname,omitempty" orm:"nickname"` // 群内昵称
	//@inject_tag: orm:"is_manager"
	IsManager uint32 `protobuf:"varint,10,opt,name=is_manager,json=isManager,proto3" json:"is_manager,omitempty" orm:"is_manager"` // 是否为管理员，0不是，1是
}

func (x *EntityXsGroupUser) Reset() {
	*x = EntityXsGroupUser{}
	if protoimpl.UnsafeEnabled {
		mi := &file_entity_xs_group_user_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EntityXsGroupUser) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EntityXsGroupUser) ProtoMessage() {}

func (x *EntityXsGroupUser) ProtoReflect() protoreflect.Message {
	mi := &file_entity_xs_group_user_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EntityXsGroupUser.ProtoReflect.Descriptor instead.
func (*EntityXsGroupUser) Descriptor() ([]byte, []int) {
	return file_entity_xs_group_user_proto_rawDescGZIP(), []int{0}
}

func (x *EntityXsGroupUser) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *EntityXsGroupUser) GetGroupId() uint32 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

func (x *EntityXsGroupUser) GetUid() uint32 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *EntityXsGroupUser) GetDateline() uint32 {
	if x != nil {
		return x.Dateline
	}
	return 0
}

func (x *EntityXsGroupUser) GetDeleted() uint32 {
	if x != nil {
		return x.Deleted
	}
	return 0
}

func (x *EntityXsGroupUser) GetForbidden() uint32 {
	if x != nil {
		return x.Forbidden
	}
	return 0
}

func (x *EntityXsGroupUser) GetIsTmp() uint32 {
	if x != nil {
		return x.IsTmp
	}
	return 0
}

func (x *EntityXsGroupUser) GetSpeak() uint32 {
	if x != nil {
		return x.Speak
	}
	return 0
}

func (x *EntityXsGroupUser) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *EntityXsGroupUser) GetIsManager() uint32 {
	if x != nil {
		return x.IsManager
	}
	return 0
}

var File_entity_xs_group_user_proto protoreflect.FileDescriptor

var file_entity_xs_group_user_proto_rawDesc = []byte{
	0x0a, 0x1a, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x5f, 0x78, 0x73, 0x5f, 0x67, 0x72, 0x6f, 0x75,
	0x70, 0x5f, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70, 0x62,
	0x22, 0x8c, 0x02, 0x0a, 0x11, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x58, 0x73, 0x47, 0x72, 0x6f,
	0x75, 0x70, 0x55, 0x73, 0x65, 0x72, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x02, 0x69, 0x64, 0x12, 0x19, 0x0a, 0x08, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x5f,
	0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x07, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x49,
	0x64, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x03,
	0x75, 0x69, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x64, 0x61, 0x74, 0x65, 0x6c, 0x69, 0x6e, 0x65, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x08, 0x64, 0x61, 0x74, 0x65, 0x6c, 0x69, 0x6e, 0x65, 0x12,
	0x18, 0x0a, 0x07, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x07, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x66, 0x6f, 0x72,
	0x62, 0x69, 0x64, 0x64, 0x65, 0x6e, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x09, 0x66, 0x6f,
	0x72, 0x62, 0x69, 0x64, 0x64, 0x65, 0x6e, 0x12, 0x15, 0x0a, 0x06, 0x69, 0x73, 0x5f, 0x74, 0x6d,
	0x70, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x69, 0x73, 0x54, 0x6d, 0x70, 0x12, 0x14,
	0x0a, 0x05, 0x73, 0x70, 0x65, 0x61, 0x6b, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x73,
	0x70, 0x65, 0x61, 0x6b, 0x12, 0x1a, 0x0a, 0x08, 0x6e, 0x69, 0x63, 0x6b, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6e, 0x69, 0x63, 0x6b, 0x6e, 0x61, 0x6d, 0x65,
	0x12, 0x1d, 0x0a, 0x0a, 0x69, 0x73, 0x5f, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x18, 0x0a,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x09, 0x69, 0x73, 0x4d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x42,
	0x0b, 0x5a, 0x09, 0x2e, 0x2e, 0x2f, 0x61, 0x70, 0x70, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_entity_xs_group_user_proto_rawDescOnce sync.Once
	file_entity_xs_group_user_proto_rawDescData = file_entity_xs_group_user_proto_rawDesc
)

func file_entity_xs_group_user_proto_rawDescGZIP() []byte {
	file_entity_xs_group_user_proto_rawDescOnce.Do(func() {
		file_entity_xs_group_user_proto_rawDescData = protoimpl.X.CompressGZIP(file_entity_xs_group_user_proto_rawDescData)
	})
	return file_entity_xs_group_user_proto_rawDescData
}

var file_entity_xs_group_user_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_entity_xs_group_user_proto_goTypes = []interface{}{
	(*EntityXsGroupUser)(nil), // 0: pb.EntityXsGroupUser
}
var file_entity_xs_group_user_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_entity_xs_group_user_proto_init() }
func file_entity_xs_group_user_proto_init() {
	if File_entity_xs_group_user_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_entity_xs_group_user_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EntityXsGroupUser); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_entity_xs_group_user_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_entity_xs_group_user_proto_goTypes,
		DependencyIndexes: file_entity_xs_group_user_proto_depIdxs,
		MessageInfos:      file_entity_xs_group_user_proto_msgTypes,
	}.Build()
	File_entity_xs_group_user_proto = out.File
	file_entity_xs_group_user_proto_rawDesc = nil
	file_entity_xs_group_user_proto_goTypes = nil
	file_entity_xs_group_user_proto_depIdxs = nil
}
