// ==========================================================================
// This is auto-generated by gf cli tool. DO NOT EDIT THIS FILE MANUALLY.
// 重要! 增加数据库字段，只能向后增加，否则不能使用工具生成proto
// ==========================================================================

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.17.3
// source: entity_xs_chatroom_extend_guess_song.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EntityXsChatroomExtendGuessSong struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	//@inject_tag: orm:"id,primary"
	Id uint32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty" orm:"id,primary"` // Id
	//@inject_tag: orm:"rid,unique"
	Rid uint32 `protobuf:"varint,2,opt,name=rid,proto3" json:"rid,omitempty" orm:"rid,unique"` // 房间ID
	//@inject_tag: orm:"state"
	State string `protobuf:"bytes,3,opt,name=state,proto3" json:"state,omitempty" orm:"state"` // 状态: wait 等待开始, pre_start 开始倒计时, running 进行中, answer 答题阶段, pub_answer 公布答案阶段
	//@inject_tag: orm:"uid"
	Uid uint32 `protobuf:"varint,4,opt,name=uid,proto3" json:"uid,omitempty" orm:"uid"` // 主持人uid
	//@inject_tag: orm:"current_model"
	CurrentModel string `protobuf:"bytes,5,opt,name=current_model,json=currentModel,proto3" json:"current_model,omitempty" orm:"current_model"` // 当前模式: one 单曲播放，ten 十连播放
	//@inject_tag: orm:"song_index"
	SongIndex uint32 `protobuf:"varint,6,opt,name=song_index,json=songIndex,proto3" json:"song_index,omitempty" orm:"song_index"` // 对于十连播模式表示第几题
	//@inject_tag: orm:"group_id"
	GroupId uint32 `protobuf:"varint,7,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty" orm:"group_id"` // 当前使用的分组ID
	//@inject_tag: orm:"song_id"
	SongId uint32 `protobuf:"varint,8,opt,name=song_id,json=songId,proto3" json:"song_id,omitempty" orm:"song_id"` // 当前正在播放的歌曲ID
	//@inject_tag: orm:"pre_song_id"
	PreSongId uint32 `protobuf:"varint,9,opt,name=pre_song_id,json=preSongId,proto3" json:"pre_song_id,omitempty" orm:"pre_song_id"` // 上一首歌ID
	//@inject_tag: orm:"dateline"
	Dateline uint32 `protobuf:"varint,10,opt,name=dateline,proto3" json:"dateline,omitempty" orm:"dateline"` // 当前阶段截止时间(除wait阶段不需要截止时间)
	//@inject_tag: orm:"sec_id"
	SecId uint32 `protobuf:"varint,11,opt,name=sec_id,json=secId,proto3" json:"sec_id,omitempty" orm:"sec_id"` // session_id
	//@inject_tag: orm:"group_range"
	GroupRange string `protobuf:"bytes,12,opt,name=group_range,json=groupRange,proto3" json:"group_range,omitempty" orm:"group_range"` // 分组范围
}

func (x *EntityXsChatroomExtendGuessSong) Reset() {
	*x = EntityXsChatroomExtendGuessSong{}
	if protoimpl.UnsafeEnabled {
		mi := &file_entity_xs_chatroom_extend_guess_song_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EntityXsChatroomExtendGuessSong) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EntityXsChatroomExtendGuessSong) ProtoMessage() {}

func (x *EntityXsChatroomExtendGuessSong) ProtoReflect() protoreflect.Message {
	mi := &file_entity_xs_chatroom_extend_guess_song_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EntityXsChatroomExtendGuessSong.ProtoReflect.Descriptor instead.
func (*EntityXsChatroomExtendGuessSong) Descriptor() ([]byte, []int) {
	return file_entity_xs_chatroom_extend_guess_song_proto_rawDescGZIP(), []int{0}
}

func (x *EntityXsChatroomExtendGuessSong) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *EntityXsChatroomExtendGuessSong) GetRid() uint32 {
	if x != nil {
		return x.Rid
	}
	return 0
}

func (x *EntityXsChatroomExtendGuessSong) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *EntityXsChatroomExtendGuessSong) GetUid() uint32 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *EntityXsChatroomExtendGuessSong) GetCurrentModel() string {
	if x != nil {
		return x.CurrentModel
	}
	return ""
}

func (x *EntityXsChatroomExtendGuessSong) GetSongIndex() uint32 {
	if x != nil {
		return x.SongIndex
	}
	return 0
}

func (x *EntityXsChatroomExtendGuessSong) GetGroupId() uint32 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

func (x *EntityXsChatroomExtendGuessSong) GetSongId() uint32 {
	if x != nil {
		return x.SongId
	}
	return 0
}

func (x *EntityXsChatroomExtendGuessSong) GetPreSongId() uint32 {
	if x != nil {
		return x.PreSongId
	}
	return 0
}

func (x *EntityXsChatroomExtendGuessSong) GetDateline() uint32 {
	if x != nil {
		return x.Dateline
	}
	return 0
}

func (x *EntityXsChatroomExtendGuessSong) GetSecId() uint32 {
	if x != nil {
		return x.SecId
	}
	return 0
}

func (x *EntityXsChatroomExtendGuessSong) GetGroupRange() string {
	if x != nil {
		return x.GroupRange
	}
	return ""
}

var File_entity_xs_chatroom_extend_guess_song_proto protoreflect.FileDescriptor

var file_entity_xs_chatroom_extend_guess_song_proto_rawDesc = []byte{
	0x0a, 0x2a, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x5f, 0x78, 0x73, 0x5f, 0x63, 0x68, 0x61, 0x74,
	0x72, 0x6f, 0x6f, 0x6d, 0x5f, 0x65, 0x78, 0x74, 0x65, 0x6e, 0x64, 0x5f, 0x67, 0x75, 0x65, 0x73,
	0x73, 0x5f, 0x73, 0x6f, 0x6e, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70, 0x62,
	0x22, 0xd7, 0x02, 0x0a, 0x1f, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x58, 0x73, 0x43, 0x68, 0x61,
	0x74, 0x72, 0x6f, 0x6f, 0x6d, 0x45, 0x78, 0x74, 0x65, 0x6e, 0x64, 0x47, 0x75, 0x65, 0x73, 0x73,
	0x53, 0x6f, 0x6e, 0x67, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x02, 0x69, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x72, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x03, 0x72, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x12, 0x10, 0x0a, 0x03,
	0x75, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x03, 0x75, 0x69, 0x64, 0x12, 0x23,
	0x0a, 0x0d, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x5f, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x4d, 0x6f,
	0x64, 0x65, 0x6c, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x6f, 0x6e, 0x67, 0x5f, 0x69, 0x6e, 0x64, 0x65,
	0x78, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x09, 0x73, 0x6f, 0x6e, 0x67, 0x49, 0x6e, 0x64,
	0x65, 0x78, 0x12, 0x19, 0x0a, 0x08, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x5f, 0x69, 0x64, 0x18, 0x07,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x07, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x49, 0x64, 0x12, 0x17, 0x0a,
	0x07, 0x73, 0x6f, 0x6e, 0x67, 0x5f, 0x69, 0x64, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06,
	0x73, 0x6f, 0x6e, 0x67, 0x49, 0x64, 0x12, 0x1e, 0x0a, 0x0b, 0x70, 0x72, 0x65, 0x5f, 0x73, 0x6f,
	0x6e, 0x67, 0x5f, 0x69, 0x64, 0x18, 0x09, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x09, 0x70, 0x72, 0x65,
	0x53, 0x6f, 0x6e, 0x67, 0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x64, 0x61, 0x74, 0x65, 0x6c, 0x69,
	0x6e, 0x65, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x08, 0x64, 0x61, 0x74, 0x65, 0x6c, 0x69,
	0x6e, 0x65, 0x12, 0x15, 0x0a, 0x06, 0x73, 0x65, 0x63, 0x5f, 0x69, 0x64, 0x18, 0x0b, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x05, 0x73, 0x65, 0x63, 0x49, 0x64, 0x12, 0x1f, 0x0a, 0x0b, 0x67, 0x72, 0x6f,
	0x75, 0x70, 0x5f, 0x72, 0x61, 0x6e, 0x67, 0x65, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a,
	0x67, 0x72, 0x6f, 0x75, 0x70, 0x52, 0x61, 0x6e, 0x67, 0x65, 0x42, 0x0b, 0x5a, 0x09, 0x2e, 0x2e,
	0x2f, 0x61, 0x70, 0x70, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_entity_xs_chatroom_extend_guess_song_proto_rawDescOnce sync.Once
	file_entity_xs_chatroom_extend_guess_song_proto_rawDescData = file_entity_xs_chatroom_extend_guess_song_proto_rawDesc
)

func file_entity_xs_chatroom_extend_guess_song_proto_rawDescGZIP() []byte {
	file_entity_xs_chatroom_extend_guess_song_proto_rawDescOnce.Do(func() {
		file_entity_xs_chatroom_extend_guess_song_proto_rawDescData = protoimpl.X.CompressGZIP(file_entity_xs_chatroom_extend_guess_song_proto_rawDescData)
	})
	return file_entity_xs_chatroom_extend_guess_song_proto_rawDescData
}

var file_entity_xs_chatroom_extend_guess_song_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_entity_xs_chatroom_extend_guess_song_proto_goTypes = []interface{}{
	(*EntityXsChatroomExtendGuessSong)(nil), // 0: pb.EntityXsChatroomExtendGuessSong
}
var file_entity_xs_chatroom_extend_guess_song_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_entity_xs_chatroom_extend_guess_song_proto_init() }
func file_entity_xs_chatroom_extend_guess_song_proto_init() {
	if File_entity_xs_chatroom_extend_guess_song_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_entity_xs_chatroom_extend_guess_song_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EntityXsChatroomExtendGuessSong); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_entity_xs_chatroom_extend_guess_song_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_entity_xs_chatroom_extend_guess_song_proto_goTypes,
		DependencyIndexes: file_entity_xs_chatroom_extend_guess_song_proto_depIdxs,
		MessageInfos:      file_entity_xs_chatroom_extend_guess_song_proto_msgTypes,
	}.Build()
	File_entity_xs_chatroom_extend_guess_song_proto = out.File
	file_entity_xs_chatroom_extend_guess_song_proto_rawDesc = nil
	file_entity_xs_chatroom_extend_guess_song_proto_goTypes = nil
	file_entity_xs_chatroom_extend_guess_song_proto_depIdxs = nil
}
