// ==========================================================================
// This is auto-generated by gf cli tool. DO NOT EDIT THIS FILE MANUALLY.
// 重要! 增加数据库字段，只能向后增加，否则不能使用工具生成proto
// ==========================================================================

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.15.5
// source: entity_xs_kol_fans_member.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EntityXsKolFansMember struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	//@inject_tag: orm:"id,primary"
	Id uint32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty" orm:"id,primary"` //
	//@inject_tag: orm:"kfg_id"
	KfgId uint32 `protobuf:"varint,2,opt,name=kfg_id,json=kfgId,proto3" json:"kfg_id,omitempty" orm:"kfg_id"` // 粉丝团基础id
	//@inject_tag: orm:"uid"
	Uid uint32 `protobuf:"varint,3,opt,name=uid,proto3" json:"uid,omitempty" orm:"uid"` // 粉丝团成员uid
	//@inject_tag: orm:"state"
	State uint32 `protobuf:"varint,4,opt,name=state,proto3" json:"state,omitempty" orm:"state"` // 状态，0：退出，1：加入
	//@inject_tag: orm:"register_time"
	RegisterTime uint32 `protobuf:"varint,5,opt,name=register_time,json=registerTime,proto3" json:"register_time,omitempty" orm:"register_time"` // 注册时间
	//@inject_tag: orm:"create_time"
	CreateTime uint32 `protobuf:"varint,6,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty" orm:"create_time"` //
	//@inject_tag: orm:"update_time"
	UpdateTime int64 `protobuf:"varint,7,opt,name=update_time,json=updateTime,proto3" json:"update_time,omitempty" orm:"update_time"` //
}

func (x *EntityXsKolFansMember) Reset() {
	*x = EntityXsKolFansMember{}
	if protoimpl.UnsafeEnabled {
		mi := &file_entity_xs_kol_fans_member_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EntityXsKolFansMember) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EntityXsKolFansMember) ProtoMessage() {}

func (x *EntityXsKolFansMember) ProtoReflect() protoreflect.Message {
	mi := &file_entity_xs_kol_fans_member_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EntityXsKolFansMember.ProtoReflect.Descriptor instead.
func (*EntityXsKolFansMember) Descriptor() ([]byte, []int) {
	return file_entity_xs_kol_fans_member_proto_rawDescGZIP(), []int{0}
}

func (x *EntityXsKolFansMember) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *EntityXsKolFansMember) GetKfgId() uint32 {
	if x != nil {
		return x.KfgId
	}
	return 0
}

func (x *EntityXsKolFansMember) GetUid() uint32 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *EntityXsKolFansMember) GetState() uint32 {
	if x != nil {
		return x.State
	}
	return 0
}

func (x *EntityXsKolFansMember) GetRegisterTime() uint32 {
	if x != nil {
		return x.RegisterTime
	}
	return 0
}

func (x *EntityXsKolFansMember) GetCreateTime() uint32 {
	if x != nil {
		return x.CreateTime
	}
	return 0
}

func (x *EntityXsKolFansMember) GetUpdateTime() int64 {
	if x != nil {
		return x.UpdateTime
	}
	return 0
}

var File_entity_xs_kol_fans_member_proto protoreflect.FileDescriptor

var file_entity_xs_kol_fans_member_proto_rawDesc = []byte{
	0x0a, 0x1f, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x5f, 0x78, 0x73, 0x5f, 0x6b, 0x6f, 0x6c, 0x5f,
	0x66, 0x61, 0x6e, 0x73, 0x5f, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x02, 0x70, 0x62, 0x22, 0xcd, 0x01, 0x0a, 0x15, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x79,
	0x58, 0x73, 0x4b, 0x6f, 0x6c, 0x46, 0x61, 0x6e, 0x73, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x02, 0x69, 0x64, 0x12,
	0x15, 0x0a, 0x06, 0x6b, 0x66, 0x67, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52,
	0x05, 0x6b, 0x66, 0x67, 0x49, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x03, 0x75, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x74,
	0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x12, 0x23,
	0x0a, 0x0d, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0c, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x54,
	0x69, 0x6d, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x5f, 0x74, 0x69,
	0x6d, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x54, 0x69, 0x6d, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x5f, 0x74,
	0x69, 0x6d, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x75, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x54, 0x69, 0x6d, 0x65, 0x42, 0x0b, 0x5a, 0x09, 0x2e, 0x2e, 0x2f, 0x61, 0x70, 0x70, 0x2f,
	0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_entity_xs_kol_fans_member_proto_rawDescOnce sync.Once
	file_entity_xs_kol_fans_member_proto_rawDescData = file_entity_xs_kol_fans_member_proto_rawDesc
)

func file_entity_xs_kol_fans_member_proto_rawDescGZIP() []byte {
	file_entity_xs_kol_fans_member_proto_rawDescOnce.Do(func() {
		file_entity_xs_kol_fans_member_proto_rawDescData = protoimpl.X.CompressGZIP(file_entity_xs_kol_fans_member_proto_rawDescData)
	})
	return file_entity_xs_kol_fans_member_proto_rawDescData
}

var file_entity_xs_kol_fans_member_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_entity_xs_kol_fans_member_proto_goTypes = []interface{}{
	(*EntityXsKolFansMember)(nil), // 0: pb.EntityXsKolFansMember
}
var file_entity_xs_kol_fans_member_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_entity_xs_kol_fans_member_proto_init() }
func file_entity_xs_kol_fans_member_proto_init() {
	if File_entity_xs_kol_fans_member_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_entity_xs_kol_fans_member_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EntityXsKolFansMember); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_entity_xs_kol_fans_member_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_entity_xs_kol_fans_member_proto_goTypes,
		DependencyIndexes: file_entity_xs_kol_fans_member_proto_depIdxs,
		MessageInfos:      file_entity_xs_kol_fans_member_proto_msgTypes,
	}.Build()
	File_entity_xs_kol_fans_member_proto = out.File
	file_entity_xs_kol_fans_member_proto_rawDesc = nil
	file_entity_xs_kol_fans_member_proto_goTypes = nil
	file_entity_xs_kol_fans_member_proto_depIdxs = nil
}
