// ==========================================================================
// This is auto-generated by gf cli tool. DO NOT EDIT THIS FILE MANUALLY.
// 重要! 增加数据库字段，只能向后增加，否则不能使用工具生成proto
// ==========================================================================

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.15.5
// source: entity_xs_user_platform.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EntityXsUserPlatform struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	//@inject_tag: orm:"uid"
	Uid uint32 `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty" orm:"uid"` //
	//@inject_tag: orm:"app_id"
	AppId int32 `protobuf:"varint,2,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty" orm:"app_id"` //
	//@inject_tag: orm:"platform"
	Platform string `protobuf:"bytes,3,opt,name=platform,proto3" json:"platform,omitempty" orm:"platform"` //
	//@inject_tag: orm:"key"
	Key string `protobuf:"bytes,4,opt,name=key,proto3" json:"key,omitempty" orm:"key"` //
	//@inject_tag: orm:"open_id"
	OpenId string `protobuf:"bytes,5,opt,name=open_id,json=openId,proto3" json:"open_id,omitempty" orm:"open_id"` //
	//@inject_tag: orm:"icon"
	Icon string `protobuf:"bytes,6,opt,name=icon,proto3" json:"icon,omitempty" orm:"icon"` //
	//@inject_tag: orm:"nickname"
	Nickname string `protobuf:"bytes,7,opt,name=nickname,proto3" json:"nickname,omitempty" orm:"nickname"` //
	//@inject_tag: orm:"sex"
	Sex uint32 `protobuf:"varint,8,opt,name=sex,proto3" json:"sex,omitempty" orm:"sex"` //
	//@inject_tag: orm:"dateline"
	Dateline uint32 `protobuf:"varint,9,opt,name=dateline,proto3" json:"dateline,omitempty" orm:"dateline"` //
	//@inject_tag: orm:"id,primary"
	Id int32 `protobuf:"varint,10,opt,name=id,proto3" json:"id,omitempty" orm:"id,primary"` //
}

func (x *EntityXsUserPlatform) Reset() {
	*x = EntityXsUserPlatform{}
	if protoimpl.UnsafeEnabled {
		mi := &file_entity_xs_user_platform_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EntityXsUserPlatform) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EntityXsUserPlatform) ProtoMessage() {}

func (x *EntityXsUserPlatform) ProtoReflect() protoreflect.Message {
	mi := &file_entity_xs_user_platform_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EntityXsUserPlatform.ProtoReflect.Descriptor instead.
func (*EntityXsUserPlatform) Descriptor() ([]byte, []int) {
	return file_entity_xs_user_platform_proto_rawDescGZIP(), []int{0}
}

func (x *EntityXsUserPlatform) GetUid() uint32 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *EntityXsUserPlatform) GetAppId() int32 {
	if x != nil {
		return x.AppId
	}
	return 0
}

func (x *EntityXsUserPlatform) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *EntityXsUserPlatform) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *EntityXsUserPlatform) GetOpenId() string {
	if x != nil {
		return x.OpenId
	}
	return ""
}

func (x *EntityXsUserPlatform) GetIcon() string {
	if x != nil {
		return x.Icon
	}
	return ""
}

func (x *EntityXsUserPlatform) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *EntityXsUserPlatform) GetSex() uint32 {
	if x != nil {
		return x.Sex
	}
	return 0
}

func (x *EntityXsUserPlatform) GetDateline() uint32 {
	if x != nil {
		return x.Dateline
	}
	return 0
}

func (x *EntityXsUserPlatform) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

var File_entity_xs_user_platform_proto protoreflect.FileDescriptor

var file_entity_xs_user_platform_proto_rawDesc = []byte{
	0x0a, 0x1d, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x5f, 0x78, 0x73, 0x5f, 0x75, 0x73, 0x65, 0x72,
	0x5f, 0x70, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x02, 0x70, 0x62, 0x22, 0xf4, 0x01, 0x0a, 0x14, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x58, 0x73,
	0x55, 0x73, 0x65, 0x72, 0x50, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x12, 0x10, 0x0a, 0x03,
	0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x03, 0x75, 0x69, 0x64, 0x12, 0x15,
	0x0a, 0x06, 0x61, 0x70, 0x70, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05,
	0x61, 0x70, 0x70, 0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72,
	0x6d, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72,
	0x6d, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03,
	0x6b, 0x65, 0x79, 0x12, 0x17, 0x0a, 0x07, 0x6f, 0x70, 0x65, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6f, 0x70, 0x65, 0x6e, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04,
	0x69, 0x63, 0x6f, 0x6e, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x69, 0x63, 0x6f, 0x6e,
	0x12, 0x1a, 0x0a, 0x08, 0x6e, 0x69, 0x63, 0x6b, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x07, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x6e, 0x69, 0x63, 0x6b, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x10, 0x0a, 0x03,
	0x73, 0x65, 0x78, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x03, 0x73, 0x65, 0x78, 0x12, 0x1a,
	0x0a, 0x08, 0x64, 0x61, 0x74, 0x65, 0x6c, 0x69, 0x6e, 0x65, 0x18, 0x09, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x08, 0x64, 0x61, 0x74, 0x65, 0x6c, 0x69, 0x6e, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x0a, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x42, 0x0b, 0x5a, 0x09, 0x2e, 0x2e,
	0x2f, 0x61, 0x70, 0x70, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_entity_xs_user_platform_proto_rawDescOnce sync.Once
	file_entity_xs_user_platform_proto_rawDescData = file_entity_xs_user_platform_proto_rawDesc
)

func file_entity_xs_user_platform_proto_rawDescGZIP() []byte {
	file_entity_xs_user_platform_proto_rawDescOnce.Do(func() {
		file_entity_xs_user_platform_proto_rawDescData = protoimpl.X.CompressGZIP(file_entity_xs_user_platform_proto_rawDescData)
	})
	return file_entity_xs_user_platform_proto_rawDescData
}

var file_entity_xs_user_platform_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_entity_xs_user_platform_proto_goTypes = []interface{}{
	(*EntityXsUserPlatform)(nil), // 0: pb.EntityXsUserPlatform
}
var file_entity_xs_user_platform_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_entity_xs_user_platform_proto_init() }
func file_entity_xs_user_platform_proto_init() {
	if File_entity_xs_user_platform_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_entity_xs_user_platform_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EntityXsUserPlatform); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_entity_xs_user_platform_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_entity_xs_user_platform_proto_goTypes,
		DependencyIndexes: file_entity_xs_user_platform_proto_depIdxs,
		MessageInfos:      file_entity_xs_user_platform_proto_msgTypes,
	}.Build()
	File_entity_xs_user_platform_proto = out.File
	file_entity_xs_user_platform_proto_rawDesc = nil
	file_entity_xs_user_platform_proto_goTypes = nil
	file_entity_xs_user_platform_proto_depIdxs = nil
}
