// ==========================================================================
// This is auto-generated by gf cli tool. DO NOT EDIT THIS FILE MANUALLY.
// ==========================================================================

package internal

// XsAttributionRewardUser is the golang structure for table xs_attribution_reward_user.
type XsAttributionRewardUser struct {
	ID             uint32 `orm:"id,primary"       json:"id"`               // 自增id
	UID            uint32 `orm:"uid,unique"       json:"uid"`              // 大R用户id
	Level          uint32 `orm:"level"            json:"level"`            // 大R等级 1:消费5000RMB 2:消费10000RMB 3:消费20000RMB
	Deleted        uint32 `orm:"deleted"          json:"deleted"`          // 是否被删除 0:正常 1:被删除
	Status         uint32 `orm:"status"           json:"status"`           // 领取状态 0:未领取 1:已领取
	RewardPrettyID uint32 `orm:"reward_pretty_id" json:"reward_pretty_id"` // 奖励的靓号
	RewardGetTime  uint32 `orm:"reward_get_time"  json:"reward_get_time"`  // 礼包领取时间
	RewardTime     uint32 `orm:"reward_time"      json:"reward_time"`      // 礼包发放时间
	UpdateTime     uint32 `orm:"update_time"      json:"update_time"`      // 更新时间
}
