// ==========================================================================
// This is auto-generated by gf cli tool. DO NOT EDIT THIS FILE MANUALLY.
// ==========================================================================

package internal

// XsCategoryTag is the golang structure for table xs_category_tag.
type XsCategoryTag struct {
	Tid     uint32 `orm:"tid,primary" json:"tid"`     //
	Cid     uint32 `orm:"cid"         json:"cid"`     //
	Title   string `orm:"title"       json:"title"`   //
	Deleted uint32 `orm:"deleted"     json:"deleted"` //
	Sex     uint32 `orm:"sex"         json:"sex"`     //
}
