// ==========================================================================
// This is auto-generated by gf cli tool. DO NOT EDIT THIS FILE MANUALLY.
// ==========================================================================

package internal

// XsCategoryPrice is the golang structure for table xs_category_price.
type XsCategoryPrice struct {
	ID      uint32 `orm:"id,primary" json:"id"`      //
	Cid     uint32 `orm:"cid"        json:"cid"`     //
	Price   uint32 `orm:"price"      json:"price"`   // 原价
	Num     uint32 `orm:"num"        json:"num"`     // 需要接单多少，才能使用
	Deleted uint32 `orm:"deleted"    json:"deleted"` //
}
