// ==========================================================================
// This is auto-generated by gf cli tool. DO NOT EDIT THIS FILE MANUALLY.
// ==========================================================================

package internal

// XsCommodityTag is the golang structure for table xs_commodity_tag.
type XsCommodityTag struct {
	ID        uint32 `orm:"id,primary"  json:"id"`         // 主键id
	Name      string `orm:"name,unique" json:"name"`       // 标签名称
	Icon      string `orm:"icon"        json:"icon"`       // icon url地址
	Remark    string `orm:"remark"      json:"remark"`     // 标签备注
	CreatedAt int32  `orm:"created_at"  json:"created_at"` // 创建时间
	UpdatedAt int32  `orm:"updated_at"  json:"updated_at"` // 更新时间
	AppID     uint32 `orm:"app_id"      json:"app_id"`     // 限定app_id
}
