// ==========================================================================
// This is auto-generated by gf cli tool. DO NOT EDIT THIS FILE MANUALLY.
// ==========================================================================

package internal

// XsCommodityRecommend is the golang structure for table xs_commodity_recommend.
type XsCommodityRecommend struct {
	ID         uint32 `orm:"id,primary" json:"id"`         // 主键id
	Cid        int32  `orm:"cid"        json:"cid"`        // 商品ID
	Type       string `orm:"type"       json:"type"`       // 推荐类型(new-上新, rcmd-推荐)
	Weight     string `orm:"weight"     json:"weight"`     // 推荐排序权重
	Dateline   int32  `orm:"dateline"   json:"dateline"`   // 创建时间
	Updateline int32  `orm:"updateline" json:"updateline"` // 更新时间
	AppID      uint32 `orm:"app_id"     json:"app_id"`     // 限定app_id
}
