// ==========================================================================
// This is auto-generated by gf cli tool. DO NOT EDIT THIS FILE MANUALLY.
// ==========================================================================

package internal

// XsChatroomExtendWolfHistory is the golang structure for table xs_chatroom_extend_wolf_history.
type XsChatroomExtendWolfHistory struct {
	UID           int32  `orm:"uid,primary"     json:"uid"`             //
	Total         int32  `orm:"total"           json:"total"`           // 总场次
	Win           int32  `orm:"win"             json:"win"`             // 胜利场次
	Dateline      int32  `orm:"dateline"        json:"dateline"`        //
	GoodWin       int32  `orm:"goodWin"         json:"good_win"`        //
	Level         uint32 `orm:"level"           json:"level"`           // 狼人杀等级
	Exp           uint32 `orm:"exp"             json:"exp"`             // 经验值
	IsAnswerOver  uint32 `orm:"isAnswerOver"    json:"is_answer_over"`  // 是否答完过引导题:0未答题，1-新手，2-未通过初级测试，3-已通过初级测试，4-未通过高级测试，5-已通过高级测试
	IsJoinMachine uint32 `orm:"is_join_machine" json:"is_join_machine"` // 是否进入过人机局
}
