// ==========================================================================
// This is auto-generated by gf cli tool. DO NOT EDIT THIS FILE MANUALLY.
// ==========================================================================

package internal

// XsConsumeTodo is the golang structure for table xs_consume_todo.
type XsConsumeTodo struct {
	ID         uint64 `orm:"id,primary"          json:"id"`          // 自增id
	UID        uint32 `orm:"uid"                 json:"uid"`         // 用户id
	Ctype      int32  `orm:"ctype"               json:"ctype"`       // 场景类型
	RequestID  uint64 `orm:"request_id"          json:"request_id"`  // 请求id
	Params     string `orm:"params"              json:"params"`      // 参数
	Status     int32  `orm:"status"              json:"status"`      // 状态 0-未完成，1-已完成，2-不支持的场景类型，3-参数非法
	RetryCnt   int32  `orm:"retry_cnt"           json:"retry_cnt"`   // 重试次数
	UpdateTime int64  `orm:"update_time"         json:"update_time"` // 更新时间
	CreateTime int64  `orm:"create_time,primary" json:"create_time"` // 创建时间
}
