// ==========================================================================
// This is auto-generated by gf cli tool. DO NOT EDIT THIS FILE MANUALLY.
// ==========================================================================

package internal

// XsChatroomFansTaskCredit is the golang structure for table xs_chatroom_fans_task_credit.
type XsChatroomFansTaskCredit struct {
	ID         uint32 `orm:"id,primary"  json:"id"`          //
	Rid        uint32 `orm:"rid"         json:"rid"`         //
	UID        uint32 `orm:"uid"         json:"uid"`         //
	WeekTime   int32  `orm:"week_time"   json:"week_time"`   //
	StarsCount uint32 `orm:"stars_count" json:"stars_count"` //
	Credit     uint32 `orm:"credit"      json:"credit"`      //
	Dateline   uint32 `orm:"dateline"    json:"dateline"`    //
}
