// ==========================================================================
// This is auto-generated by gf cli tool. DO NOT EDIT THIS FILE MANUALLY.
// ==========================================================================

package internal

// XsConsumeLotteryStock is the golang structure for table xs_consume_lottery_stock.
type XsConsumeLotteryStock struct {
	ID         uint32 `orm:"id,primary"   json:"id"`          //
	PcID       uint32 `orm:"pc_id,unique" json:"pc_id"`       // bbc_benefit_pool_commodity.id
	PoolID     uint32 `orm:"pool_id"      json:"pool_id"`     // 奖池的id
	StockNum   uint32 `orm:"stock_num"    json:"stock_num"`   // 库存的数量
	CreateTime int64  `orm:"create_time"  json:"create_time"` //
	UpdateTime int64  `orm:"update_time"  json:"update_time"` //
}
