// ==========================================================================
// This is auto-generated by gf cli tool. DO NOT EDIT THIS FILE MANUALLY.
// ==========================================================================

package internal

// XsChatroomRankPk is the golang structure for table xs_chatroom_rank_pk.
type XsChatroomRankPk struct {
	ID         uint32 `orm:"id,primary"  json:"id"`          //
	Rid        uint32 `orm:"rid,unique"  json:"rid"`         // 房间ID
	Switch     uint32 `orm:"switch"      json:"switch"`      // 是否代开PK模式
	AutoMic    uint32 `orm:"auto_mic"    json:"auto_mic"`    // 是否自由点歌
	PkVersion  uint32 `orm:"pk_version"  json:"pk_version"`  // pk版本
	CreateTime uint32 `orm:"create_time" json:"create_time"` // 开启时间
	UpdateTime uint32 `orm:"update_time" json:"update_time"` // 更新时间
}
