// ==========================================================================
// This is auto-generated by gf cli tool. DO NOT EDIT THIS FILE MANUALLY.
// ==========================================================================

package internal

// XsChatRoomExp is the golang structure for table xs_chat_room_exp.
type XsChatRoomExp struct {
	ID       uint32 `orm:"id,primary" json:"id"`       //
	UID      uint32 `orm:"uid"        json:"uid"`      //
	ExpType  string `orm:"exp_type"   json:"exp_type"` // sign -签到 online -在线 gift—送礼物 onMicro-上麦
	RoomExp  uint32 `orm:"room_exp"   json:"room_exp"` // 个人房经验值
	Dateline uint32 `orm:"dateline"   json:"dateline"` // 更新时间
}
