// ==========================================================================
// This is auto-generated by gf cli tool. DO NOT EDIT THIS FILE MANUALLY.
// ==========================================================================

package internal

// XsCommodityGroup is the golang structure for table xs_commodity_group.
type XsCommodityGroup struct {
	GroupID    uint32 `orm:"group_id,primary" json:"group_id"`   //
	GroupName  string `orm:"group_name"       json:"group_name"` //
	Dateline   uint32 `orm:"dateline"         json:"dateline"`   //
	Updateline uint32 `orm:"updateline"       json:"updateline"` //
	IsSpecial  uint32 `orm:"is_special"       json:"is_special"` // 是否特殊物品分组：0否，1是
	AppID      uint32 `orm:"app_id"           json:"app_id"`     // 限定app_id
}
