// ==========================================================================
// This is auto-generated by gf cli tool. DO NOT EDIT THIS FILE MANUALLY.
// ==========================================================================

package internal

// XsGroupTour is the golang structure for table xs_group_tour.
type XsGroupTour struct {
	ID         int32 `orm:"id,primary"     json:"id"`         // 自增主键
	GroupID    int32 `orm:"groupId,unique" json:"group_id"`   // 关联群ID
	Captain    int32 `orm:"captain,unique" json:"captain"`    // 团长ID
	Rid        int32 `orm:"rid"            json:"rid"`        // 默认房间ID
	Quiet      int32 `orm:"quiet"          json:"quiet"`      // 团长关闭房间麦状态，0 表示打开，1表示关闭
	Dateline   int32 `orm:"dateline"       json:"dateline"`   // 记录创建时间
	Updateline int32 `orm:"updateline"     json:"updateline"` // 记录更新时间
}
