// ==========================================================================
// This is auto-generated by gf cli tool. DO NOT EDIT THIS FILE MANUALLY.
// ==========================================================================

package internal

// XsMentorExp is the golang structure for table xs_mentor_exp.
type XsMentorExp struct {
	ID               uint32 `orm:"id,primary"         json:"id"`                 //
	UID              uint32 `orm:"uid,unique"         json:"uid"`                // 师父uid
	Level            uint32 `orm:"level"              json:"level"`              // 名师等级
	NotGraduateNum   uint32 `orm:"not_graduate_num"   json:"not_graduate_num"`   // 目前没有出师的徒弟数目
	TotalDiscipleNum uint32 `orm:"total_disciple_num" json:"total_disciple_num"` // 包含出师和没出师的，没有解除师徒关系的人数
	LeftDiscipleNum  uint32 `orm:"left_disciple_num"  json:"left_disciple_num"`  // 可用徒弟的数量
	HasGraduateNum   uint32 `orm:"has_graduate_num"   json:"has_graduate_num"`   // 已经出师的徒弟数量
	MentorExp        uint32 `orm:"mentor_exp"         json:"mentor_exp"`         // 名师经验
	CreateTime       uint32 `orm:"create_time"        json:"create_time"`        //
	UpdateTime       uint32 `orm:"update_time"        json:"update_time"`        //
	ExtraDiscipleNum uint32 `orm:"extra_disciple_num" json:"extra_disciple_num"` // 额外增加的可收徒弟数量
}
