// ==========================================================================
// This is auto-generated by gf cli tool. DO NOT EDIT THIS FILE MANUALLY.
// ==========================================================================

package internal

// XsOnlineEarnRelation is the golang structure for table xs_online_earn_relation.
type XsOnlineEarnRelation struct {
	ID             uint32 `orm:"id,primary"       json:"id"`               //
	AgentUID       uint32 `orm:"agent_uid"        json:"agent_uid"`        // 经纪人uid
	ArtistUID      uint32 `orm:"artist_uid"       json:"artist_uid"`       // 艺人uid
	SignTime       uint32 `orm:"sign_time"        json:"sign_time"`        // 最近一次签约时间
	EndTime        uint32 `orm:"end_time"         json:"end_time"`         // 签约到期时间
	FreeRenewalNum uint32 `orm:"free_renewal_num" json:"free_renewal_num"` // 此次签约已免费续约次数
	Contribution   uint32 `orm:"contribution"     json:"contribution"`     // 此次签约艺人收礼带来贡献（单位钻）
	CreateTime     uint32 `orm:"create_time"      json:"create_time"`      //
	UpdateTime     uint32 `orm:"update_time"      json:"update_time"`      //
}
