// ==========================================================================
// This is auto-generated by gf cli tool. DO NOT EDIT THIS FILE MANUALLY.
// ==========================================================================

package internal

// XsRoomUserRandMusicList is the golang structure for table xs_room_user_rand_music_list.
type XsRoomUserRandMusicList struct {
	ID         uint32 `orm:"id,primary"  json:"id"`          //
	UID        uint32 `orm:"uid,unique"  json:"uid"`         // 用户uid
	OrderCount uint32 `orm:"order_count" json:"order_count"` // 被点次数
	PlayCount  uint32 `orm:"play_count"  json:"play_count"`  // 唱歌次数
}
