// ==========================================================================
// This is auto-generated by gf cli tool. DO NOT EDIT THIS FILE MANUALLY.
// ==========================================================================

package internal

// XsReport is the golang structure for table xs_report.
type XsReport struct {
	ID       int32  `orm:"id,primary" json:"id"`       //
	UID      int32  `orm:"uid"        json:"uid"`      // 举报人
	To       int32  `orm:"to"         json:"to"`       // 被举报人
	Rid      int32  `orm:"rid"        json:"rid"`      // 举报房间号,不为0时，to表示房间创建者id
	Type     int32  `orm:"type"       json:"type"`     // 举报类型
	Dateline int32  `orm:"dateline"   json:"dateline"` // 时间
	Desc     string `orm:"desc"       json:"desc"`     // 理由
	P1       string `orm:"p1"         json:"p_1"`      //
	P2       string `orm:"p2"         json:"p_2"`      //
	P3       string `orm:"p3"         json:"p_3"`      //
	P4       string `orm:"p4"         json:"p_4"`      //
	P5       string `orm:"p5"         json:"p_5"`      //
	P6       string `orm:"p6"         json:"p_6"`      //
	P7       string `orm:"p7"         json:"p_7"`      //
	P8       string `orm:"p8"         json:"p_8"`      //
	State    int32  `orm:"state"      json:"state"`    // 0：待处理，1：正在处理，2：处理完成
	Category int32  `orm:"category"   json:"category"` // 0-表示个人/房间/朋友圈举报 1-交友卡举报
}
