// ==========================================================================
// This is auto-generated by gf cli tool. DO NOT EDIT THIS FILE MANUALLY.
// ==========================================================================

package internal

import (
	"github.com/gogf/gf/os/gtime"
)

// XsRoomLiveGiftbag is the golang structure for table xs_room_live_giftbag.
type XsRoomLiveGiftbag struct {
	ID         uint32      `orm:"id,primary"  json:"id"`          //
	UID        uint32      `orm:"uid"         json:"uid"`         // 主播uid
	Cid        uint32      `orm:"cid,unique"  json:"cid"`         // 物品cid
	SourceCid  uint32      `orm:"source_cid"  json:"source_cid"`  // 被复制的物品cid
	State      uint32      `orm:"state"       json:"state"`       // 状态，0：不在用，1：在用
	CreateTime uint32      `orm:"create_time" json:"create_time"` //
	UpdateTime *gtime.Time `orm:"update_time" json:"update_time"` //
}
