// ==========================================================================
// This is auto-generated by gf cli tool. DO NOT EDIT THIS FILE MANUALLY.
// ==========================================================================

package internal

// XsRoomVipCard is the golang structure for table xs_room_vip_card.
type XsRoomVipCard struct {
	ID                uint32 `orm:"id,primary"          json:"id"`                  // 主键，会员卡id
	UID               uint32 `orm:"uid"                 json:"uid"`                 // 用户id
	Rid               uint32 `orm:"rid"                 json:"rid"`                 // 房间id
	Expends           uint32 `orm:"expends"             json:"expends"`             // 消费金额，单位分
	Level             uint32 `orm:"level"               json:"level"`               // 贵宾等级，和bbc_chatroom_screen_tag_config.id有对应关系
	LastAttenuateTime int32  `orm:"last_attenuate_time" json:"last_attenuate_time"` // 上次衰减时间: 衰减时和消费时都会更新
	TopOnce           uint32 `orm:"top_once"            json:"top_once"`            // 是否曾达到过第一名，0-否，1-是
}
