// ==========================================================================
// This is auto-generated by gf cli tool. DO NOT EDIT THIS FILE MANUALLY.
// ==========================================================================

package internal

// XsSmallAccount is the golang structure for table xs_small_account.
type XsSmallAccount struct {
	ID       uint32 `orm:"id,primary" json:"id"`       // 自增id
	Mac      string `orm:"mac"        json:"mac"`      // Mac地址
	UID      uint32 `orm:"uid"        json:"uid"`      // uid
	State    uint32 `orm:"state"      json:"state"`    // 0无登录态 1有登录态
	Dateline int32  `orm:"dateline"   json:"dateline"` // 时间戳
	AppID    int32  `orm:"app_id"     json:"app_id"`   // app_id, 默认为伴伴
}
