// ==========================================================================
// This is auto-generated by gf cli tool. DO NOT EDIT THIS FILE MANUALLY.
// ==========================================================================

package internal

// XsTagCate is the golang structure for table xs_tag_cate.
type XsTagCate struct {
	ID        uint32 `orm:"id,primary" json:"id"`         //
	Name      string `orm:"name"       json:"name"`       //
	LabelIcon string `orm:"label_icon" json:"label_icon"` //
	Type      string `orm:"type"       json:"type"`       //
	Ordering  uint32 `orm:"ordering"   json:"ordering"`   //
	Deleted   uint32 `orm:"deleted"    json:"deleted"`    //
	Dateline  uint32 `orm:"dateline"   json:"dateline"`   //
}
