// ==========================================================================
// This is auto-generated by gf cli tool. DO NOT EDIT THIS FILE MANUALLY.
// ==========================================================================

package internal

// XsUserTitleBenefitSetting is the golang structure for table xs_user_title_benefit_setting.
type XsUserTitleBenefitSetting struct {
	ID         uint32 `orm:"id,primary"  json:"id"`          // 自增ID
	UID        uint32 `orm:"uid,unique"  json:"uid"`         // 用户uid
	SofaLevel  uint32 `orm:"sofa_level"  json:"sofa_level"`  // 佩戴的宝座等级
	CreateTime uint32 `orm:"create_time" json:"create_time"` // 创建时间
	UpdateTime uint32 `orm:"update_time" json:"update_time"` // 更新时间
}
