// ==========================================================================
// This is auto-generated by gf cli tool. DO NOT EDIT THIS FILE MANUALLY.
// ==========================================================================

package internal

// XsUserTitleNew is the golang structure for table xs_user_title_new.
type XsUserTitleNew struct {
	ID             int32 `orm:"id,primary"      json:"id"`              //
	UID            int32 `orm:"uid,unique"      json:"uid"`             // 用户id
	AppID          int32 `orm:"app_id"          json:"app_id"`          //
	Level          int32 `orm:"level"           json:"level"`           // 爵位等级[1, 9]
	Growth         int32 `orm:"growth"          json:"growth"`          // 成长值
	EffectiveTime  int32 `orm:"effective_time"  json:"effective_time"`  // 保级到期时间
	SubscribeTime  int32 `orm:"subscribe_time"  json:"subscribe_time"`  // 订阅到期时间
	EffectiveValue int32 `orm:"effective_value" json:"effective_value"` // 保级期内收到的成长值
}
