// ==========================================================================
// This is auto-generated by gf cli tool. DO NOT EDIT THIS FILE MANUALLY.
// ==========================================================================

package internal

// XsUserLike is the golang structure for table xs_user_like.
type XsUserLike struct {
	ID         int32  `orm:"id,primary" json:"id"`         //
	UID        int32  `orm:"uid"        json:"uid"`        // 用户ID
	LikeUID    int32  `orm:"like_uid"   json:"like_uid"`   // 喜欢的用户ID
	Degree     string `orm:"degree"     json:"degree"`     // 喜欢的程度
	Likeline   int32  `orm:"likeline"   json:"likeline"`   // 滑动喜欢的时间
	Chatline   int32  `orm:"chatline"   json:"chatline"`   // 进入私信列表的时间
	Viewline   int32  `orm:"viewline"   json:"viewline"`   // 浏览我喜欢的页面时间
	Dateline   int32  `orm:"dateline"   json:"dateline"`   // 记录创建时间
	Updateline int32  `orm:"updateline" json:"updateline"` // 记录更新时间
}
