// ==========================================================================
// This is auto-generated by gf cli tool. DO NOT EDIT THIS FILE MANUALLY.
// ==========================================================================

package internal

// XsUserMoneyEntry is the golang structure for table xs_user_money_entry.
type XsUserMoneyEntry struct {
	ID          uint32 `orm:"id,primary"   json:"id"`           //
	UID         uint32 `orm:"uid,unique"   json:"uid"`          // 用户的uid
	RebateMoney uint32 `orm:"rebate_money" json:"rebate_money"` // 到我们这里的钱
	TotalMoney  uint32 `orm:"total_money"  json:"total_money"`  // 用户端充值金额的钱
	CreateTime  uint32 `orm:"create_time"  json:"create_time"`  //
	UpdateTime  uint32 `orm:"update_time"  json:"update_time"`  //
}
