// ==========================================================================
// This is auto-generated by gf cli tool. DO NOT EDIT THIS FILE MANUALLY.
// ==========================================================================

package internal

// XsUserAddrBook is the golang structure for table xs_user_addr_book.
type XsUserAddrBook struct {
	ID         int32  `orm:"id,primary"  json:"id"`          //
	UID        uint32 `orm:"uid"         json:"uid"`         // 用户uid
	AppID      int32  `orm:"app_id"      json:"app_id"`      // APP_ID
	Mobile     string `orm:"mobile"      json:"mobile"`      // 联系人手机号
	Name       string `orm:"name"        json:"name"`        // 联系人姓名
	Redpoint   uint32 `orm:"redpoint"    json:"redpoint"`    // 是否显示未读红点，0不显示，1显示
	Register   uint32 `orm:"register"    json:"register"`    // 是否已注册，0未注册，1已注册
	RegUID     uint32 `orm:"reg_uid"     json:"reg_uid"`     // 联系人uid
	RegTime    uint32 `orm:"reg_time"    json:"reg_time"`    // 注册时间
	CreateTime uint32 `orm:"create_time" json:"create_time"` // 创建时间
	UpdateTime uint32 `orm:"update_time" json:"update_time"` // 更新时间
}
