// ==========================================================================
// This is auto-generated by gf cli tool. DO NOT EDIT THIS FILE MANUALLY.
// ==========================================================================

package internal

// XsUserViability is the golang structure for table xs_user_viability.
type XsUserViability struct {
	ID        uint32 `orm:"id,primary" json:"id"`         // 自增id
	UID       uint32 `orm:"uid"        json:"uid"`        // 用户ID
	SubAppID  uint32 `orm:"sub_app_id" json:"sub_app_id"` // 子app 0:伴伴 1:嗨歌
	Viability uint32 `orm:"viability"  json:"viability"`  // 活跃值
	Drawed    uint32 `orm:"drawed"     json:"drawed"`     // 奖励领取,按位读写,目前11级
	Dateline  uint32 `orm:"dateline"   json:"dateline"`   // 更新时间
}
