// ==========================================================================
// This is auto-generated by gf cli tool. DO NOT EDIT THIS FILE MANUALLY.
// ==========================================================================

package internal

// XsUserBankcard is the golang structure for table xs_user_bankcard.
type XsUserBankcard struct {
	ID           int32  `orm:"id,primary"   json:"id"`           //
	AppID        int32  `orm:"app_id"       json:"app_id"`       //
	UID          int32  `orm:"uid,unique"   json:"uid"`          //
	Name         string `orm:"name"         json:"name"`         // 银行卡户名
	Bankname     string `orm:"bankname"     json:"bankname"`     // 银行名
	Bankcity     string `orm:"bankcity"     json:"bankcity"`     // 银行开户地
	Bankposition string `orm:"bankposition" json:"bankposition"` // 银行支行名
	Banknum      string `orm:"banknum"      json:"banknum"`      // 银行卡号
	State        int32  `orm:"state"        json:"state"`        // 1待审核，2审核不通过，3审核通过
	Dateline     int32  `orm:"dateline"     json:"dateline"`     //
	UpdateTime   int32  `orm:"update_time"  json:"update_time"`  //
}
