// ==========================================================================
// This is auto-generated by gf cli tool. DO NOT EDIT THIS FILE MANUALLY.
// ==========================================================================

package internal

// XsUserVideo is the golang structure for table xs_user_video.
type XsUserVideo struct {
	UID              uint32 `orm:"uid,primary"       json:"uid"`               //
	Path             string `orm:"path"              json:"path"`              //
	Cover            string `orm:"cover"             json:"cover"`             //
	Duration         uint32 `orm:"duration"          json:"duration"`          //
	State            uint32 `orm:"state"             json:"state"`             // 0 待审核 1 不通过 2 通过
	Reason           string `orm:"reason"            json:"reason"`            //
	Dateline         uint32 `orm:"dateline"          json:"dateline"`          //
	DatelineComplete uint32 `orm:"dateline_complete" json:"dateline_complete"` // 最后一次审核通过时间
}
