// ==========================================================================
// This is auto-generated by gf cli tool. DO NOT EDIT THIS FILE MANUALLY.
// ==========================================================================

package internal

// XsUserTacitRecord is the golang structure for table xs_user_tacit_record.
type XsUserTacitRecord struct {
	ID         uint32 `orm:"id,primary" json:"id"`         // primary key
	UID1       int32  `orm:"uid1"       json:"uid_1"`      // litter uid
	UID2       int32  `orm:"uid2"       json:"uid_2"`      // bigger uid
	Value      int64  `orm:"value"      json:"value"`      // 默契值
	Annotation string `orm:"annotation" json:"annotation"` // 默契值变化说明
	Dateline   int32  `orm:"dateline"   json:"dateline"`   // 事件发生时间点
}
