// ==========================================================================
// This is auto-generated by gf cli tool. DO NOT EDIT THIS FILE MANUALLY.
// ==========================================================================

package internal

// XsUserCreditScore is the golang structure for table xs_user_credit_score.
type XsUserCreditScore struct {
	ID       int32 `orm:"id,primary" json:"id"`       //
	UID      int32 `orm:"uid,unique" json:"uid"`      //
	Score    int32 `orm:"score"      json:"score"`    // 信誉度
	Dateline int32 `orm:"dateline"   json:"dateline"` //
}
