// ==========================================================================
// This is auto-generated by gf cli tool. DO NOT EDIT THIS FILE MANUALLY.
// ==========================================================================

package internal

// XsUserMissionCredit is the golang structure for table xs_user_mission_credit.
type XsUserMissionCredit struct {
	ID           uint32 `orm:"id,primary"    json:"id"`            //
	UID          int32  `orm:"uid"           json:"uid"`           // 用户id
	Season       int32  `orm:"season"        json:"season"`        // 赛季
	UpgradeAward int32  `orm:"upgrade_award" json:"upgrade_award"` // 是否升级奖励
	Credit       int32  `orm:"credit"        json:"credit"`        // 任务积分
	TicketNum    int32  `orm:"ticket_num"    json:"ticket_num"`    // 卡券数量
	Utime        int32  `orm:"utime"         json:"utime"`         // 更新时间
}
