// ==========================================================================
// This is auto-generated by gf cli tool. DO NOT EDIT THIS FILE MANUALLY.
// ==========================================================================

package internal

// XsUserBox is the golang structure for table xs_user_box.
type XsUserBox struct {
	UID                 int32  `orm:"uid,primary"           json:"uid"`                   //
	Type                string `orm:"type,primary"          json:"type"`                  // 开箱的类型
	Num                 int32  `orm:"num"                   json:"num"`                   // 累计开箱的数量
	TotalMoney          int32  `orm:"total_money"           json:"total_money"`           // 开箱消费总钱数
	LastRefreshCid      int32  `orm:"last_refresh_cid"      json:"last_refresh_cid"`      // 上次刷新出的物品id
	LastRefreshDateline int32  `orm:"last_refresh_dateline" json:"last_refresh_dateline"` // 上次刷新时间
	Record              string `orm:"record"                json:"record"`                // 开箱记录，记录可能开出物品的累计次数，用于防脸黑
	Dateline            int32  `orm:"dateline"              json:"dateline"`              //
	LastRefreshSubCid   int32  `orm:"last_refresh_sub_cid"  json:"last_refresh_sub_cid"`  //
	FetchRecord         string `orm:"fetch_record"          json:"fetch_record"`          //
}
