// ==========================================================================
// This is auto-generated by gf cli tool. DO NOT EDIT THIS FILE MANUALLY.
// ==========================================================================

package internal

// XsUserPhotoMark is the golang structure for table xs_user_photo_mark.
type XsUserPhotoMark struct {
	ID     int32  `orm:"id,primary" json:"id"`     //
	UID    int32  `orm:"uid"        json:"uid"`    // 用户UID
	Header uint32 `orm:"header"     json:"header"` // 是否清晰显示头像
	Ctime  int32  `orm:"ctime"      json:"ctime"`  // 创建时间
	Icon   string `orm:"icon"       json:"icon"`   //
}
