// ==========================================================================
// This is auto-generated by gf cli tool. DO NOT EDIT THIS FILE MANUALLY.
// ==========================================================================

package internal

// XsUserTacit is the golang structure for table xs_user_tacit.
type XsUserTacit struct {
	ID         uint32 `orm:"id,primary"  json:"id"`          // primary key
	Prefix     string `orm:"prefix"      json:"prefix"`      // primary key
	UID1       int32  `orm:"uid1"        json:"uid_1"`       // litter uid
	UID2       int32  `orm:"uid2"        json:"uid_2"`       // bigger uid
	Value      int64  `orm:"value"       json:"value"`       // 默契值
	WeekIncr   int64  `orm:"week_incr"   json:"week_incr"`   // 周增加值
	Week       int64  `orm:"week"        json:"week"`        // weekly 所属周 格式yyyyww
	DayIncr    int64  `orm:"day_incr"    json:"day_incr"`    // 日增加值
	Day        int64  `orm:"day"         json:"day"`         // daily 所增加日 格式 yyyyMMdd
	FieldLevel int32  `orm:"field_level" json:"field_level"` // 第几次更新值
	Dateline   int32  `orm:"dateline"    json:"dateline"`    // dateline
	Updateline int32  `orm:"updateline"  json:"updateline"`  // updateline
}
