// ==========================================================================
// This is auto-generated by gf cli tool. DO NOT EDIT THIS FILE MANUALLY.
// ==========================================================================

package internal

// XsUserInvisible is the golang structure for table xs_user_invisible.
type XsUserInvisible struct {
	ID         uint32 `orm:"id,primary"  json:"id"`          // 自增ID
	UID        uint32 `orm:"uid"         json:"uid"`         // 用户ID
	PckID      uint32 `orm:"pck_id"      json:"pck_id"`      // 权益礼包ID
	Num        uint32 `orm:"num"         json:"num"`         // 购买数量
	CreateTime uint32 `orm:"create_time" json:"create_time"` // 购买时间
}
