// ==========================================================================
// This is auto-generated by gf cli tool. DO NOT EDIT THIS FILE MANUALLY.
// ==========================================================================

package internal

// XsUserTransferReason is the golang structure for table xs_user_transfer_reason.
type XsUserTransferReason struct {
	ID             uint32 `orm:"id,primary"      json:"id"`              //
	Puid           uint32 `orm:"puid"            json:"puid"`            // 陪陪UID
	Cuid           uint32 `orm:"cuid,unique"     json:"cuid"`            // 消费用户UID
	RegistDateline uint32 `orm:"regist_dateline" json:"regist_dateline"` // 注册时间
	Ctime          uint32 `orm:"ctime"           json:"ctime"`           // 归因间
}
