// ==========================================================================
// This is auto-generated by gf cli tool. DO NOT EDIT THIS FILE MANUALLY.
// ==========================================================================

package internal

// XsUserCashAccount is the golang structure for table xs_user_cash_account.
type XsUserCashAccount struct {
	UID      uint32 `orm:"uid,primary" json:"uid"`      //
	AppID    int32  `orm:"app_id"      json:"app_id"`   //
	Platform string `orm:"platform"    json:"platform"` //
	Account  string `orm:"account"     json:"account"`  // 支付宝账号
	Name     string `orm:"name"        json:"name"`     // 真实姓名
}
