// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.19.4
// source: user/user_profile_message.proto

package user

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

//获取单个请求请求
type ReqUserProfile struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	//需要查询的用户UID
	Uid uint32 `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	//需要返回哪些字段，为空的话，表示所有字段名
	Fields []string `protobuf:"bytes,2,rep,name=fields,proto3" json:"fields,omitempty"`
}

func (x *ReqUserProfile) Reset() {
	*x = ReqUserProfile{}
	if protoimpl.UnsafeEnabled {
		mi := &file_user_user_profile_message_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqUserProfile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqUserProfile) ProtoMessage() {}

func (x *ReqUserProfile) ProtoReflect() protoreflect.Message {
	mi := &file_user_user_profile_message_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqUserProfile.ProtoReflect.Descriptor instead.
func (*ReqUserProfile) Descriptor() ([]byte, []int) {
	return file_user_user_profile_message_proto_rawDescGZIP(), []int{0}
}

func (x *ReqUserProfile) GetUid() uint32 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *ReqUserProfile) GetFields() []string {
	if x != nil {
		return x.Fields
	}
	return nil
}

//获取批量请求
type ReqUserProfiles struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	//批量请求用户UID集合
	Uids []uint32 `protobuf:"varint,1,rep,packed,name=uids,proto3" json:"uids,omitempty"`
	//需要返回哪些字段，为空的话，表示所有字段名
	Fields []string `protobuf:"bytes,2,rep,name=fields,proto3" json:"fields,omitempty"`
}

func (x *ReqUserProfiles) Reset() {
	*x = ReqUserProfiles{}
	if protoimpl.UnsafeEnabled {
		mi := &file_user_user_profile_message_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqUserProfiles) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqUserProfiles) ProtoMessage() {}

func (x *ReqUserProfiles) ProtoReflect() protoreflect.Message {
	mi := &file_user_user_profile_message_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqUserProfiles.ProtoReflect.Descriptor instead.
func (*ReqUserProfiles) Descriptor() ([]byte, []int) {
	return file_user_user_profile_message_proto_rawDescGZIP(), []int{1}
}

func (x *ReqUserProfiles) GetUids() []uint32 {
	if x != nil {
		return x.Uids
	}
	return nil
}

func (x *ReqUserProfiles) GetFields() []string {
	if x != nil {
		return x.Fields
	}
	return nil
}

//验证用户登录令牌合法性
type ReqUserAuth struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	//当前登录用户令牌
	Token string `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
}

func (x *ReqUserAuth) Reset() {
	*x = ReqUserAuth{}
	if protoimpl.UnsafeEnabled {
		mi := &file_user_user_profile_message_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqUserAuth) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqUserAuth) ProtoMessage() {}

func (x *ReqUserAuth) ProtoReflect() protoreflect.Message {
	mi := &file_user_user_profile_message_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqUserAuth.ProtoReflect.Descriptor instead.
func (*ReqUserAuth) Descriptor() ([]byte, []int) {
	return file_user_user_profile_message_proto_rawDescGZIP(), []int{2}
}

func (x *ReqUserAuth) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

//返回验证用户信息
type RepUserAuth struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uid      uint32 `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Time     uint32 `protobuf:"varint,2,opt,name=time,proto3" json:"time,omitempty"`
	AppId    uint32 `protobuf:"varint,3,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	Salt     string `protobuf:"bytes,4,opt,name=salt,proto3" json:"salt,omitempty"`
	Platform string `protobuf:"bytes,5,opt,name=platform,proto3" json:"platform,omitempty"`
	Channel  string `protobuf:"bytes,6,opt,name=channel,proto3" json:"channel,omitempty"`
}

func (x *RepUserAuth) Reset() {
	*x = RepUserAuth{}
	if protoimpl.UnsafeEnabled {
		mi := &file_user_user_profile_message_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RepUserAuth) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RepUserAuth) ProtoMessage() {}

func (x *RepUserAuth) ProtoReflect() protoreflect.Message {
	mi := &file_user_user_profile_message_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RepUserAuth.ProtoReflect.Descriptor instead.
func (*RepUserAuth) Descriptor() ([]byte, []int) {
	return file_user_user_profile_message_proto_rawDescGZIP(), []int{3}
}

func (x *RepUserAuth) GetUid() uint32 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *RepUserAuth) GetTime() uint32 {
	if x != nil {
		return x.Time
	}
	return 0
}

func (x *RepUserAuth) GetAppId() uint32 {
	if x != nil {
		return x.AppId
	}
	return 0
}

func (x *RepUserAuth) GetSalt() string {
	if x != nil {
		return x.Salt
	}
	return ""
}

func (x *RepUserAuth) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *RepUserAuth) GetChannel() string {
	if x != nil {
		return x.Channel
	}
	return ""
}

//申请令牌
type ReqUserToken struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uid      uint32 `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	AppId    uint32 `protobuf:"varint,2,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	Platform string `protobuf:"bytes,3,opt,name=platform,proto3" json:"platform,omitempty"` // app or web
	Channel  string `protobuf:"bytes,4,opt,name=channel,proto3" json:"channel,omitempty"`   // 可选
}

func (x *ReqUserToken) Reset() {
	*x = ReqUserToken{}
	if protoimpl.UnsafeEnabled {
		mi := &file_user_user_profile_message_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqUserToken) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqUserToken) ProtoMessage() {}

func (x *ReqUserToken) ProtoReflect() protoreflect.Message {
	mi := &file_user_user_profile_message_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqUserToken.ProtoReflect.Descriptor instead.
func (*ReqUserToken) Descriptor() ([]byte, []int) {
	return file_user_user_profile_message_proto_rawDescGZIP(), []int{4}
}

func (x *ReqUserToken) GetUid() uint32 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *ReqUserToken) GetAppId() uint32 {
	if x != nil {
		return x.AppId
	}
	return 0
}

func (x *ReqUserToken) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *ReqUserToken) GetChannel() string {
	if x != nil {
		return x.Channel
	}
	return ""
}

//返回令牌
type RepUserToken struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Token string `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
}

func (x *RepUserToken) Reset() {
	*x = RepUserToken{}
	if protoimpl.UnsafeEnabled {
		mi := &file_user_user_profile_message_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RepUserToken) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RepUserToken) ProtoMessage() {}

func (x *RepUserToken) ProtoReflect() protoreflect.Message {
	mi := &file_user_user_profile_message_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RepUserToken.ProtoReflect.Descriptor instead.
func (*RepUserToken) Descriptor() ([]byte, []int) {
	return file_user_user_profile_message_proto_rawDescGZIP(), []int{5}
}

func (x *RepUserToken) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

//返回多个用户信息
type RepUserProfiles struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *RepUserProfiles) Reset() {
	*x = RepUserProfiles{}
	if protoimpl.UnsafeEnabled {
		mi := &file_user_user_profile_message_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RepUserProfiles) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RepUserProfiles) ProtoMessage() {}

func (x *RepUserProfiles) ProtoReflect() protoreflect.Message {
	mi := &file_user_user_profile_message_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RepUserProfiles.ProtoReflect.Descriptor instead.
func (*RepUserProfiles) Descriptor() ([]byte, []int) {
	return file_user_user_profile_message_proto_rawDescGZIP(), []int{6}
}

type ReqUsersBitMap struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	//批量请求用户UID集合
	Uids []uint32 `protobuf:"varint,1,rep,packed,name=uids,proto3" json:"uids,omitempty"`
}

func (x *ReqUsersBitMap) Reset() {
	*x = ReqUsersBitMap{}
	if protoimpl.UnsafeEnabled {
		mi := &file_user_user_profile_message_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqUsersBitMap) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqUsersBitMap) ProtoMessage() {}

func (x *ReqUsersBitMap) ProtoReflect() protoreflect.Message {
	mi := &file_user_user_profile_message_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqUsersBitMap.ProtoReflect.Descriptor instead.
func (*ReqUsersBitMap) Descriptor() ([]byte, []int) {
	return file_user_user_profile_message_proto_rawDescGZIP(), []int{7}
}

func (x *ReqUsersBitMap) GetUids() []uint32 {
	if x != nil {
		return x.Uids
	}
	return nil
}

type UserBitMapItem struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uid uint32 `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
}

func (x *UserBitMapItem) Reset() {
	*x = UserBitMapItem{}
	if protoimpl.UnsafeEnabled {
		mi := &file_user_user_profile_message_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserBitMapItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserBitMapItem) ProtoMessage() {}

func (x *UserBitMapItem) ProtoReflect() protoreflect.Message {
	mi := &file_user_user_profile_message_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserBitMapItem.ProtoReflect.Descriptor instead.
func (*UserBitMapItem) Descriptor() ([]byte, []int) {
	return file_user_user_profile_message_proto_rawDescGZIP(), []int{8}
}

func (x *UserBitMapItem) GetUid() uint32 {
	if x != nil {
		return x.Uid
	}
	return 0
}

type RepUsersBitMap struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data []*UserBitMapItem `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
}

func (x *RepUsersBitMap) Reset() {
	*x = RepUsersBitMap{}
	if protoimpl.UnsafeEnabled {
		mi := &file_user_user_profile_message_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RepUsersBitMap) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RepUsersBitMap) ProtoMessage() {}

func (x *RepUsersBitMap) ProtoReflect() protoreflect.Message {
	mi := &file_user_user_profile_message_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RepUsersBitMap.ProtoReflect.Descriptor instead.
func (*RepUsersBitMap) Descriptor() ([]byte, []int) {
	return file_user_user_profile_message_proto_rawDescGZIP(), []int{9}
}

func (x *RepUsersBitMap) GetData() []*UserBitMapItem {
	if x != nil {
		return x.Data
	}
	return nil
}

type ReqGetUserIpInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ip string `protobuf:"bytes,1,opt,name=Ip,proto3" json:"Ip,omitempty"` //ip地址10.10.10.10
}

func (x *ReqGetUserIpInfo) Reset() {
	*x = ReqGetUserIpInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_user_user_profile_message_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqGetUserIpInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqGetUserIpInfo) ProtoMessage() {}

func (x *ReqGetUserIpInfo) ProtoReflect() protoreflect.Message {
	mi := &file_user_user_profile_message_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqGetUserIpInfo.ProtoReflect.Descriptor instead.
func (*ReqGetUserIpInfo) Descriptor() ([]byte, []int) {
	return file_user_user_profile_message_proto_rawDescGZIP(), []int{10}
}

func (x *ReqGetUserIpInfo) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

type RepGetUserIpInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Country  string `protobuf:"bytes,1,opt,name=country,proto3" json:"country,omitempty"`   //国家
	Code     string `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`         //code，我也不知道是啥@zeng.gang
	Province string `protobuf:"bytes,3,opt,name=province,proto3" json:"province,omitempty"` //省
	City     string `protobuf:"bytes,4,opt,name=city,proto3" json:"city,omitempty"`         //城市
	Telecom  string `protobuf:"bytes,5,opt,name=telecom,proto3" json:"telecom,omitempty"`   //通信商
}

func (x *RepGetUserIpInfo) Reset() {
	*x = RepGetUserIpInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_user_user_profile_message_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RepGetUserIpInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RepGetUserIpInfo) ProtoMessage() {}

func (x *RepGetUserIpInfo) ProtoReflect() protoreflect.Message {
	mi := &file_user_user_profile_message_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RepGetUserIpInfo.ProtoReflect.Descriptor instead.
func (*RepGetUserIpInfo) Descriptor() ([]byte, []int) {
	return file_user_user_profile_message_proto_rawDescGZIP(), []int{11}
}

func (x *RepGetUserIpInfo) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

func (x *RepGetUserIpInfo) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *RepGetUserIpInfo) GetProvince() string {
	if x != nil {
		return x.Province
	}
	return ""
}

func (x *RepGetUserIpInfo) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *RepGetUserIpInfo) GetTelecom() string {
	if x != nil {
		return x.Telecom
	}
	return ""
}

//返回多人设置信息
type RepUserSettings struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *RepUserSettings) Reset() {
	*x = RepUserSettings{}
	if protoimpl.UnsafeEnabled {
		mi := &file_user_user_profile_message_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RepUserSettings) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RepUserSettings) ProtoMessage() {}

func (x *RepUserSettings) ProtoReflect() protoreflect.Message {
	mi := &file_user_user_profile_message_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RepUserSettings.ProtoReflect.Descriptor instead.
func (*RepUserSettings) Descriptor() ([]byte, []int) {
	return file_user_user_profile_message_proto_rawDescGZIP(), []int{12}
}

type ReqNeedVerify struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uid uint32 `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
}

func (x *ReqNeedVerify) Reset() {
	*x = ReqNeedVerify{}
	if protoimpl.UnsafeEnabled {
		mi := &file_user_user_profile_message_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqNeedVerify) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqNeedVerify) ProtoMessage() {}

func (x *ReqNeedVerify) ProtoReflect() protoreflect.Message {
	mi := &file_user_user_profile_message_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqNeedVerify.ProtoReflect.Descriptor instead.
func (*ReqNeedVerify) Descriptor() ([]byte, []int) {
	return file_user_user_profile_message_proto_rawDescGZIP(), []int{13}
}

func (x *ReqNeedVerify) GetUid() uint32 {
	if x != nil {
		return x.Uid
	}
	return 0
}

type RepNeedVerify struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Res     uint32 `protobuf:"varint,2,opt,name=res,proto3" json:"res,omitempty"`
}

func (x *RepNeedVerify) Reset() {
	*x = RepNeedVerify{}
	if protoimpl.UnsafeEnabled {
		mi := &file_user_user_profile_message_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RepNeedVerify) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RepNeedVerify) ProtoMessage() {}

func (x *RepNeedVerify) ProtoReflect() protoreflect.Message {
	mi := &file_user_user_profile_message_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RepNeedVerify.ProtoReflect.Descriptor instead.
func (*RepNeedVerify) Descriptor() ([]byte, []int) {
	return file_user_user_profile_message_proto_rawDescGZIP(), []int{14}
}

func (x *RepNeedVerify) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RepNeedVerify) GetRes() uint32 {
	if x != nil {
		return x.Res
	}
	return 0
}

var File_user_user_profile_message_proto protoreflect.FileDescriptor

var file_user_user_profile_message_proto_rawDesc = []byte{
	0x0a, 0x1f, 0x75, 0x73, 0x65, 0x72, 0x2f, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x70, 0x72, 0x6f, 0x66,
	0x69, 0x6c, 0x65, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x0c, 0x72, 0x62, 0x70, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x22,
	0x3a, 0x0a, 0x0e, 0x52, 0x65, 0x71, 0x55, 0x73, 0x65, 0x72, 0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c,
	0x65, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x03,
	0x75, 0x69, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x73, 0x18, 0x02, 0x20,
	0x03, 0x28, 0x09, 0x52, 0x06, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x73, 0x22, 0x3d, 0x0a, 0x0f, 0x52,
	0x65, 0x71, 0x55, 0x73, 0x65, 0x72, 0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x73, 0x12, 0x12,
	0x0a, 0x04, 0x75, 0x69, 0x64, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0d, 0x52, 0x04, 0x75, 0x69,
	0x64, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x73, 0x18, 0x02, 0x20, 0x03,
	0x28, 0x09, 0x52, 0x06, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x73, 0x22, 0x23, 0x0a, 0x0b, 0x52, 0x65,
	0x71, 0x55, 0x73, 0x65, 0x72, 0x41, 0x75, 0x74, 0x68, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b,
	0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x22,
	0x94, 0x01, 0x0a, 0x0b, 0x52, 0x65, 0x70, 0x55, 0x73, 0x65, 0x72, 0x41, 0x75, 0x74, 0x68, 0x12,
	0x10, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x03, 0x75, 0x69,
	0x64, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52,
	0x04, 0x74, 0x69, 0x6d, 0x65, 0x12, 0x15, 0x0a, 0x06, 0x61, 0x70, 0x70, 0x5f, 0x69, 0x64, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x61, 0x70, 0x70, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04,
	0x73, 0x61, 0x6c, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x73, 0x61, 0x6c, 0x74,
	0x12, 0x1a, 0x0a, 0x08, 0x70, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x70, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x12, 0x18, 0x0a, 0x07,
	0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63,
	0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x22, 0x6d, 0x0a, 0x0c, 0x52, 0x65, 0x71, 0x55, 0x73, 0x65,
	0x72, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x03, 0x75, 0x69, 0x64, 0x12, 0x15, 0x0a, 0x06, 0x61, 0x70, 0x70, 0x5f,
	0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x61, 0x70, 0x70, 0x49, 0x64, 0x12,
	0x1a, 0x0a, 0x08, 0x70, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x70, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x12, 0x18, 0x0a, 0x07, 0x63,
	0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x68,
	0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x22, 0x24, 0x0a, 0x0c, 0x52, 0x65, 0x70, 0x55, 0x73, 0x65, 0x72,
	0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x22, 0x11, 0x0a, 0x0f, 0x52,
	0x65, 0x70, 0x55, 0x73, 0x65, 0x72, 0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x73, 0x22, 0x24,
	0x0a, 0x0e, 0x52, 0x65, 0x71, 0x55, 0x73, 0x65, 0x72, 0x73, 0x42, 0x69, 0x74, 0x4d, 0x61, 0x70,
	0x12, 0x12, 0x0a, 0x04, 0x75, 0x69, 0x64, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0d, 0x52, 0x04,
	0x75, 0x69, 0x64, 0x73, 0x22, 0x22, 0x0a, 0x0e, 0x55, 0x73, 0x65, 0x72, 0x42, 0x69, 0x74, 0x4d,
	0x61, 0x70, 0x49, 0x74, 0x65, 0x6d, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x03, 0x75, 0x69, 0x64, 0x22, 0x42, 0x0a, 0x0e, 0x52, 0x65, 0x70, 0x55,
	0x73, 0x65, 0x72, 0x73, 0x42, 0x69, 0x74, 0x4d, 0x61, 0x70, 0x12, 0x30, 0x0a, 0x04, 0x64, 0x61,
	0x74, 0x61, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x72, 0x62, 0x70, 0x2e, 0x72,
	0x70, 0x63, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x42, 0x69, 0x74, 0x4d,
	0x61, 0x70, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x22, 0x0a, 0x10,
	0x52, 0x65, 0x71, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x49, 0x70, 0x49, 0x6e, 0x66, 0x6f,
	0x12, 0x0e, 0x0a, 0x02, 0x49, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x49, 0x70,
	0x22, 0x8a, 0x01, 0x0a, 0x10, 0x52, 0x65, 0x70, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x49,
	0x70, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x72, 0x79,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x72, 0x79, 0x12,
	0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x63,
	0x6f, 0x64, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x72, 0x6f, 0x76, 0x69, 0x6e, 0x63, 0x65, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x72, 0x6f, 0x76, 0x69, 0x6e, 0x63, 0x65, 0x12,
	0x12, 0x0a, 0x04, 0x63, 0x69, 0x74, 0x79, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x63,
	0x69, 0x74, 0x79, 0x12, 0x18, 0x0a, 0x07, 0x74, 0x65, 0x6c, 0x65, 0x63, 0x6f, 0x6d, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x74, 0x65, 0x6c, 0x65, 0x63, 0x6f, 0x6d, 0x22, 0x11, 0x0a,
	0x0f, 0x52, 0x65, 0x70, 0x55, 0x73, 0x65, 0x72, 0x53, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x73,
	0x22, 0x21, 0x0a, 0x0d, 0x52, 0x65, 0x71, 0x4e, 0x65, 0x65, 0x64, 0x56, 0x65, 0x72, 0x69, 0x66,
	0x79, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x03,
	0x75, 0x69, 0x64, 0x22, 0x3b, 0x0a, 0x0d, 0x52, 0x65, 0x70, 0x4e, 0x65, 0x65, 0x64, 0x56, 0x65,
	0x72, 0x69, 0x66, 0x79, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x12, 0x10,
	0x0a, 0x03, 0x72, 0x65, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x03, 0x72, 0x65, 0x73,
	0x42, 0x32, 0x5a, 0x30, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6f,
	0x6c, 0x61, 0x6f, 0x6c, 0x61, 0x2d, 0x63, 0x68, 0x61, 0x74, 0x2f, 0x72, 0x62, 0x70, 0x2d, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x67, 0x65, 0x6e, 0x5f, 0x70, 0x62, 0x2f, 0x72, 0x70, 0x63, 0x2f,
	0x75, 0x73, 0x65, 0x72, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_user_user_profile_message_proto_rawDescOnce sync.Once
	file_user_user_profile_message_proto_rawDescData = file_user_user_profile_message_proto_rawDesc
)

func file_user_user_profile_message_proto_rawDescGZIP() []byte {
	file_user_user_profile_message_proto_rawDescOnce.Do(func() {
		file_user_user_profile_message_proto_rawDescData = protoimpl.X.CompressGZIP(file_user_user_profile_message_proto_rawDescData)
	})
	return file_user_user_profile_message_proto_rawDescData
}

var file_user_user_profile_message_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_user_user_profile_message_proto_goTypes = []interface{}{
	(*ReqUserProfile)(nil),   // 0: rbp.rpc.user.ReqUserProfile
	(*ReqUserProfiles)(nil),  // 1: rbp.rpc.user.ReqUserProfiles
	(*ReqUserAuth)(nil),      // 2: rbp.rpc.user.ReqUserAuth
	(*RepUserAuth)(nil),      // 3: rbp.rpc.user.RepUserAuth
	(*ReqUserToken)(nil),     // 4: rbp.rpc.user.ReqUserToken
	(*RepUserToken)(nil),     // 5: rbp.rpc.user.RepUserToken
	(*RepUserProfiles)(nil),  // 6: rbp.rpc.user.RepUserProfiles
	(*ReqUsersBitMap)(nil),   // 7: rbp.rpc.user.ReqUsersBitMap
	(*UserBitMapItem)(nil),   // 8: rbp.rpc.user.UserBitMapItem
	(*RepUsersBitMap)(nil),   // 9: rbp.rpc.user.RepUsersBitMap
	(*ReqGetUserIpInfo)(nil), // 10: rbp.rpc.user.ReqGetUserIpInfo
	(*RepGetUserIpInfo)(nil), // 11: rbp.rpc.user.RepGetUserIpInfo
	(*RepUserSettings)(nil),  // 12: rbp.rpc.user.RepUserSettings
	(*ReqNeedVerify)(nil),    // 13: rbp.rpc.user.ReqNeedVerify
	(*RepNeedVerify)(nil),    // 14: rbp.rpc.user.RepNeedVerify
}
var file_user_user_profile_message_proto_depIdxs = []int32{
	8, // 0: rbp.rpc.user.RepUsersBitMap.data:type_name -> rbp.rpc.user.UserBitMapItem
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_user_user_profile_message_proto_init() }
func file_user_user_profile_message_proto_init() {
	if File_user_user_profile_message_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_user_user_profile_message_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReqUserProfile); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_user_user_profile_message_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReqUserProfiles); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_user_user_profile_message_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReqUserAuth); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_user_user_profile_message_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RepUserAuth); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_user_user_profile_message_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReqUserToken); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_user_user_profile_message_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RepUserToken); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_user_user_profile_message_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RepUserProfiles); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_user_user_profile_message_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReqUsersBitMap); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_user_user_profile_message_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserBitMapItem); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_user_user_profile_message_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RepUsersBitMap); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_user_user_profile_message_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReqGetUserIpInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_user_user_profile_message_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RepGetUserIpInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_user_user_profile_message_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RepUserSettings); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_user_user_profile_message_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReqNeedVerify); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_user_user_profile_message_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RepNeedVerify); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_user_user_profile_message_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_user_user_profile_message_proto_goTypes,
		DependencyIndexes: file_user_user_profile_message_proto_depIdxs,
		MessageInfos:      file_user_user_profile_message_proto_msgTypes,
	}.Build()
	File_user_user_profile_message_proto = out.File
	file_user_user_profile_message_proto_rawDesc = nil
	file_user_user_profile_message_proto_goTypes = nil
	file_user_user_profile_message_proto_depIdxs = nil
}
